// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *BandwidthServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Email) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GraphingInterface) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GraphingQueue) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GraphingResource) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MacServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MacServerPing) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MacServerWinbox) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Netwatch) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Sniffer) Hub() {}
