// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Certificate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CertificateScepServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Clock) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Identity) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Led) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LedSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Logging) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoggingAction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Note) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NtpClient) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NtpServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouterboardButtonMode) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouterboardButtonReset) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouterboardButtonWps) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouterboardSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouterboardUsb) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Scheduler) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Script) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserAaa) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserSshkeys) Hub() {}
