// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RouterboardSettingsInitParameters struct {

	// (Boolean) An option to enable firmware upgrade automatically after the RouterOS upgrade.
	// An option to enable firmware upgrade automatically after the RouterOS upgrade.
	AutoUpgrade *bool `json:"autoUpgrade,omitempty" tf:"auto_upgrade,omitempty"`

	// (Number) An option to choose the onboard RS232 speed in bits per second.
	// An option to choose the onboard RS232 speed in bits per second.
	BaudRate *int64 `json:"baudRate,omitempty" tf:"baud_rate,omitempty"`

	// (String) A delay for a keystroke while booting.
	// A delay for a keystroke while booting.
	BootDelay *string `json:"bootDelay,omitempty" tf:"boot_delay,omitempty"`

	// boot`, `flash-boot-once-then-nand`, `nand-if-fail-then-ethernet`, `nand-only`, `try-ethernet-once-then-nand`.
	// An option to choose the way RouterBOOT loads the operating system. Possible values: `ethernet`, `flash-boot`, `flash-boot-once-then-nand`, `nand-if-fail-then-ethernet`, `nand-only`, `try-ethernet-once-then-nand`.
	BootDevice *string `json:"bootDevice,omitempty" tf:"boot_device,omitempty"`

	// os`, `swos`.
	// An option to choose the booting operating system for CRS3xx series switches. Possible values: `router-os`, `swos`.
	BootOs *string `json:"bootOs,omitempty" tf:"boot_os,omitempty"`

	// (String) Boot protocol to use. Possible values: `bootp`, `dhcp`.
	// Boot protocol to use. Possible values: `bootp`, `dhcp`.
	BootProtocol *string `json:"bootProtocol,omitempty" tf:"boot_protocol,omitempty"`

	// (String) An option to change the CPU frequency of the device.
	// An option to change the CPU frequency of the device.
	CPUFrequency *string `json:"cpuFrequency,omitempty" tf:"cpu_frequency,omitempty"`

	// save`, `regular`.
	// An option whether to enter CPU suspend mode in HTL instruction. Possible values: `power-save`, `regular`.
	CPUMode *string `json:"cpuMode,omitempty" tf:"cpu_mode,omitempty"`

	// (Boolean) An option to enable reset via the onboard jumper.
	// An option to enable reset via the onboard jumper.
	EnableJumperReset *bool `json:"enableJumperReset,omitempty" tf:"enable_jumper_reset,omitempty"`

	// key`, `delete-key`.
	// An option to set which key will cause the BIOS to enter configuration mode during boot delay. Possible values: `any-key`, `delete-key`.
	EnterSetupOn *string `json:"enterSetupOn,omitempty" tf:"enter_setup_on,omitempty"`

	// (Boolean) An option to use the backup RouterBOOT.
	// An option to use the backup RouterBOOT.
	ForceBackupBooter *bool `json:"forceBackupBooter,omitempty" tf:"force_backup_booter,omitempty"`

	// (String) An option to set a delay before the USB port is initialized. Used for mPCIe modems with RB9xx series devices only.
	// An option to set a delay before the USB port is initialized. Used for mPCIe modems with RB9xx series devices only.
	InitDelay *string `json:"initDelay,omitempty" tf:"init_delay,omitempty"`

	// (String) An option to change the memory data rate of the device. Values depend on the model.
	// An option to change the memory data rate of the device. Values depend on the model.
	MemoryDataRate *string `json:"memoryDataRate,omitempty" tf:"memory_data_rate,omitempty"`

	// (String) An option to change the memory frequency of the device. Values depend on the model.
	// An option to change the memory frequency of the device. Values depend on the model.
	MemoryFrequency *string `json:"memoryFrequency,omitempty" tf:"memory_frequency,omitempty"`

	// (String) An option to enable preboot `etherboot`, which runs before the regular boot device.
	// An option to enable preboot `etherboot`, which runs before the regular boot device.
	PrebootEtherboot *string `json:"prebootEtherboot,omitempty" tf:"preboot_etherboot,omitempty"`

	// etherboot` to accept only from the specified Netinstall server.
	// An option to instruct `preboot-etherboot` to accept only from the specified Netinstall server.
	PrebootEtherbootServer *string `json:"prebootEtherbootServer,omitempty" tf:"preboot_etherboot_server,omitempty"`

	// (String) An option to disable any access to the RouterBOOT configuration settings over a console cable and disables the operation of the reset button to change the boot mode (Netinstall will be disabled). Possible values: `disabled`, `enabled`.
	// An option to disable any access to the RouterBOOT configuration settings over a console cable and disables the operation of the reset button to change the boot mode (Netinstall will be disabled). Possible values: `disabled`, `enabled`.
	ProtectedRouterboot *string `json:"protectedRouterboot,omitempty" tf:"protected_routerboot,omitempty"`

	// on for longer than the specified time but less than `reformat_hold_button_max.`
	// An option to enable resetting everything by pressing the button at power-on for longer than the specified time but less than `reformat_hold_button_max.`
	ReformatHoldButton *string `json:"reformatHoldButton,omitempty" tf:"reformat_hold_button,omitempty"`

	// (String) See `reformat_hold_button`.
	// See `reformat_hold_button`.
	ReformatHoldButtonMax *string `json:"reformatHoldButtonMax,omitempty" tf:"reformat_hold_button_max,omitempty"`

	// low TX power for high antenna gain devices.
	// An option to enable extra-low TX power for high antenna gain devices.
	RegulatoryDomainCe *bool `json:"regulatoryDomainCe,omitempty" tf:"regulatory_domain_ce,omitempty"`

	// (Boolean) An option to turn off output on the serial console and beeping sounds during booting.
	// An option to turn off output on the serial console and beeping sounds during booting.
	SilentBoot *bool `json:"silentBoot,omitempty" tf:"silent_boot,omitempty"`
}

type RouterboardSettingsObservation struct {

	// (Boolean) An option to enable firmware upgrade automatically after the RouterOS upgrade.
	// An option to enable firmware upgrade automatically after the RouterOS upgrade.
	AutoUpgrade *bool `json:"autoUpgrade,omitempty" tf:"auto_upgrade,omitempty"`

	// (Number) An option to choose the onboard RS232 speed in bits per second.
	// An option to choose the onboard RS232 speed in bits per second.
	BaudRate *int64 `json:"baudRate,omitempty" tf:"baud_rate,omitempty"`

	// (String) A delay for a keystroke while booting.
	// A delay for a keystroke while booting.
	BootDelay *string `json:"bootDelay,omitempty" tf:"boot_delay,omitempty"`

	// boot`, `flash-boot-once-then-nand`, `nand-if-fail-then-ethernet`, `nand-only`, `try-ethernet-once-then-nand`.
	// An option to choose the way RouterBOOT loads the operating system. Possible values: `ethernet`, `flash-boot`, `flash-boot-once-then-nand`, `nand-if-fail-then-ethernet`, `nand-only`, `try-ethernet-once-then-nand`.
	BootDevice *string `json:"bootDevice,omitempty" tf:"boot_device,omitempty"`

	// os`, `swos`.
	// An option to choose the booting operating system for CRS3xx series switches. Possible values: `router-os`, `swos`.
	BootOs *string `json:"bootOs,omitempty" tf:"boot_os,omitempty"`

	// (String) Boot protocol to use. Possible values: `bootp`, `dhcp`.
	// Boot protocol to use. Possible values: `bootp`, `dhcp`.
	BootProtocol *string `json:"bootProtocol,omitempty" tf:"boot_protocol,omitempty"`

	// (String) An option to change the CPU frequency of the device.
	// An option to change the CPU frequency of the device.
	CPUFrequency *string `json:"cpuFrequency,omitempty" tf:"cpu_frequency,omitempty"`

	// save`, `regular`.
	// An option whether to enter CPU suspend mode in HTL instruction. Possible values: `power-save`, `regular`.
	CPUMode *string `json:"cpuMode,omitempty" tf:"cpu_mode,omitempty"`

	// (Boolean) An option to enable reset via the onboard jumper.
	// An option to enable reset via the onboard jumper.
	EnableJumperReset *bool `json:"enableJumperReset,omitempty" tf:"enable_jumper_reset,omitempty"`

	// key`, `delete-key`.
	// An option to set which key will cause the BIOS to enter configuration mode during boot delay. Possible values: `any-key`, `delete-key`.
	EnterSetupOn *string `json:"enterSetupOn,omitempty" tf:"enter_setup_on,omitempty"`

	// (Boolean) An option to use the backup RouterBOOT.
	// An option to use the backup RouterBOOT.
	ForceBackupBooter *bool `json:"forceBackupBooter,omitempty" tf:"force_backup_booter,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) An option to set a delay before the USB port is initialized. Used for mPCIe modems with RB9xx series devices only.
	// An option to set a delay before the USB port is initialized. Used for mPCIe modems with RB9xx series devices only.
	InitDelay *string `json:"initDelay,omitempty" tf:"init_delay,omitempty"`

	// (String) An option to change the memory data rate of the device. Values depend on the model.
	// An option to change the memory data rate of the device. Values depend on the model.
	MemoryDataRate *string `json:"memoryDataRate,omitempty" tf:"memory_data_rate,omitempty"`

	// (String) An option to change the memory frequency of the device. Values depend on the model.
	// An option to change the memory frequency of the device. Values depend on the model.
	MemoryFrequency *string `json:"memoryFrequency,omitempty" tf:"memory_frequency,omitempty"`

	// (String) An option to enable preboot `etherboot`, which runs before the regular boot device.
	// An option to enable preboot `etherboot`, which runs before the regular boot device.
	PrebootEtherboot *string `json:"prebootEtherboot,omitempty" tf:"preboot_etherboot,omitempty"`

	// etherboot` to accept only from the specified Netinstall server.
	// An option to instruct `preboot-etherboot` to accept only from the specified Netinstall server.
	PrebootEtherbootServer *string `json:"prebootEtherbootServer,omitempty" tf:"preboot_etherboot_server,omitempty"`

	// (String) An option to disable any access to the RouterBOOT configuration settings over a console cable and disables the operation of the reset button to change the boot mode (Netinstall will be disabled). Possible values: `disabled`, `enabled`.
	// An option to disable any access to the RouterBOOT configuration settings over a console cable and disables the operation of the reset button to change the boot mode (Netinstall will be disabled). Possible values: `disabled`, `enabled`.
	ProtectedRouterboot *string `json:"protectedRouterboot,omitempty" tf:"protected_routerboot,omitempty"`

	// on for longer than the specified time but less than `reformat_hold_button_max.`
	// An option to enable resetting everything by pressing the button at power-on for longer than the specified time but less than `reformat_hold_button_max.`
	ReformatHoldButton *string `json:"reformatHoldButton,omitempty" tf:"reformat_hold_button,omitempty"`

	// (String) See `reformat_hold_button`.
	// See `reformat_hold_button`.
	ReformatHoldButtonMax *string `json:"reformatHoldButtonMax,omitempty" tf:"reformat_hold_button_max,omitempty"`

	// low TX power for high antenna gain devices.
	// An option to enable extra-low TX power for high antenna gain devices.
	RegulatoryDomainCe *bool `json:"regulatoryDomainCe,omitempty" tf:"regulatory_domain_ce,omitempty"`

	// (Boolean) An option to turn off output on the serial console and beeping sounds during booting.
	// An option to turn off output on the serial console and beeping sounds during booting.
	SilentBoot *bool `json:"silentBoot,omitempty" tf:"silent_boot,omitempty"`
}

type RouterboardSettingsParameters struct {

	// (Boolean) An option to enable firmware upgrade automatically after the RouterOS upgrade.
	// An option to enable firmware upgrade automatically after the RouterOS upgrade.
	// +kubebuilder:validation:Optional
	AutoUpgrade *bool `json:"autoUpgrade,omitempty" tf:"auto_upgrade,omitempty"`

	// (Number) An option to choose the onboard RS232 speed in bits per second.
	// An option to choose the onboard RS232 speed in bits per second.
	// +kubebuilder:validation:Optional
	BaudRate *int64 `json:"baudRate,omitempty" tf:"baud_rate,omitempty"`

	// (String) A delay for a keystroke while booting.
	// A delay for a keystroke while booting.
	// +kubebuilder:validation:Optional
	BootDelay *string `json:"bootDelay,omitempty" tf:"boot_delay,omitempty"`

	// boot`, `flash-boot-once-then-nand`, `nand-if-fail-then-ethernet`, `nand-only`, `try-ethernet-once-then-nand`.
	// An option to choose the way RouterBOOT loads the operating system. Possible values: `ethernet`, `flash-boot`, `flash-boot-once-then-nand`, `nand-if-fail-then-ethernet`, `nand-only`, `try-ethernet-once-then-nand`.
	// +kubebuilder:validation:Optional
	BootDevice *string `json:"bootDevice,omitempty" tf:"boot_device,omitempty"`

	// os`, `swos`.
	// An option to choose the booting operating system for CRS3xx series switches. Possible values: `router-os`, `swos`.
	// +kubebuilder:validation:Optional
	BootOs *string `json:"bootOs,omitempty" tf:"boot_os,omitempty"`

	// (String) Boot protocol to use. Possible values: `bootp`, `dhcp`.
	// Boot protocol to use. Possible values: `bootp`, `dhcp`.
	// +kubebuilder:validation:Optional
	BootProtocol *string `json:"bootProtocol,omitempty" tf:"boot_protocol,omitempty"`

	// (String) An option to change the CPU frequency of the device.
	// An option to change the CPU frequency of the device.
	// +kubebuilder:validation:Optional
	CPUFrequency *string `json:"cpuFrequency,omitempty" tf:"cpu_frequency,omitempty"`

	// save`, `regular`.
	// An option whether to enter CPU suspend mode in HTL instruction. Possible values: `power-save`, `regular`.
	// +kubebuilder:validation:Optional
	CPUMode *string `json:"cpuMode,omitempty" tf:"cpu_mode,omitempty"`

	// (Boolean) An option to enable reset via the onboard jumper.
	// An option to enable reset via the onboard jumper.
	// +kubebuilder:validation:Optional
	EnableJumperReset *bool `json:"enableJumperReset,omitempty" tf:"enable_jumper_reset,omitempty"`

	// key`, `delete-key`.
	// An option to set which key will cause the BIOS to enter configuration mode during boot delay. Possible values: `any-key`, `delete-key`.
	// +kubebuilder:validation:Optional
	EnterSetupOn *string `json:"enterSetupOn,omitempty" tf:"enter_setup_on,omitempty"`

	// (Boolean) An option to use the backup RouterBOOT.
	// An option to use the backup RouterBOOT.
	// +kubebuilder:validation:Optional
	ForceBackupBooter *bool `json:"forceBackupBooter,omitempty" tf:"force_backup_booter,omitempty"`

	// (String) An option to set a delay before the USB port is initialized. Used for mPCIe modems with RB9xx series devices only.
	// An option to set a delay before the USB port is initialized. Used for mPCIe modems with RB9xx series devices only.
	// +kubebuilder:validation:Optional
	InitDelay *string `json:"initDelay,omitempty" tf:"init_delay,omitempty"`

	// (String) An option to change the memory data rate of the device. Values depend on the model.
	// An option to change the memory data rate of the device. Values depend on the model.
	// +kubebuilder:validation:Optional
	MemoryDataRate *string `json:"memoryDataRate,omitempty" tf:"memory_data_rate,omitempty"`

	// (String) An option to change the memory frequency of the device. Values depend on the model.
	// An option to change the memory frequency of the device. Values depend on the model.
	// +kubebuilder:validation:Optional
	MemoryFrequency *string `json:"memoryFrequency,omitempty" tf:"memory_frequency,omitempty"`

	// (String) An option to enable preboot `etherboot`, which runs before the regular boot device.
	// An option to enable preboot `etherboot`, which runs before the regular boot device.
	// +kubebuilder:validation:Optional
	PrebootEtherboot *string `json:"prebootEtherboot,omitempty" tf:"preboot_etherboot,omitempty"`

	// etherboot` to accept only from the specified Netinstall server.
	// An option to instruct `preboot-etherboot` to accept only from the specified Netinstall server.
	// +kubebuilder:validation:Optional
	PrebootEtherbootServer *string `json:"prebootEtherbootServer,omitempty" tf:"preboot_etherboot_server,omitempty"`

	// (String) An option to disable any access to the RouterBOOT configuration settings over a console cable and disables the operation of the reset button to change the boot mode (Netinstall will be disabled). Possible values: `disabled`, `enabled`.
	// An option to disable any access to the RouterBOOT configuration settings over a console cable and disables the operation of the reset button to change the boot mode (Netinstall will be disabled). Possible values: `disabled`, `enabled`.
	// +kubebuilder:validation:Optional
	ProtectedRouterboot *string `json:"protectedRouterboot,omitempty" tf:"protected_routerboot,omitempty"`

	// on for longer than the specified time but less than `reformat_hold_button_max.`
	// An option to enable resetting everything by pressing the button at power-on for longer than the specified time but less than `reformat_hold_button_max.`
	// +kubebuilder:validation:Optional
	ReformatHoldButton *string `json:"reformatHoldButton,omitempty" tf:"reformat_hold_button,omitempty"`

	// (String) See `reformat_hold_button`.
	// See `reformat_hold_button`.
	// +kubebuilder:validation:Optional
	ReformatHoldButtonMax *string `json:"reformatHoldButtonMax,omitempty" tf:"reformat_hold_button_max,omitempty"`

	// low TX power for high antenna gain devices.
	// An option to enable extra-low TX power for high antenna gain devices.
	// +kubebuilder:validation:Optional
	RegulatoryDomainCe *bool `json:"regulatoryDomainCe,omitempty" tf:"regulatory_domain_ce,omitempty"`

	// (Boolean) An option to turn off output on the serial console and beeping sounds during booting.
	// An option to turn off output on the serial console and beeping sounds during booting.
	// +kubebuilder:validation:Optional
	SilentBoot *bool `json:"silentBoot,omitempty" tf:"silent_boot,omitempty"`
}

// RouterboardSettingsSpec defines the desired state of RouterboardSettings
type RouterboardSettingsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RouterboardSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RouterboardSettingsInitParameters `json:"initProvider,omitempty"`
}

// RouterboardSettingsStatus defines the observed state of RouterboardSettings.
type RouterboardSettingsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RouterboardSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RouterboardSettings is the Schema for the RouterboardSettingss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type RouterboardSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RouterboardSettingsSpec   `json:"spec"`
	Status            RouterboardSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RouterboardSettingsList contains a list of RouterboardSettingss
type RouterboardSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RouterboardSettings `json:"items"`
}

// Repository type metadata.
var (
	RouterboardSettings_Kind             = "RouterboardSettings"
	RouterboardSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RouterboardSettings_Kind}.String()
	RouterboardSettings_KindAPIVersion   = RouterboardSettings_Kind + "." + CRDGroupVersion.String()
	RouterboardSettings_GroupVersionKind = CRDGroupVersion.WithKind(RouterboardSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&RouterboardSettings{}, &RouterboardSettingsList{})
}
