// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type UserAaaInitParameters struct {

	// (Boolean) An option that enables accounting for users.
	// An option that enables accounting for users.
	Accounting *bool `json:"accounting,omitempty" tf:"accounting,omitempty"`

	// (String) The user group that is used by default for users authenticated via a RADIUS server.
	// The user group that is used by default for users authenticated via a RADIUS server.
	DefaultGroup *string `json:"defaultGroup,omitempty" tf:"default_group,omitempty"`

	// (Set of String) A set of groups that are not allowed for users authenticated by RADIUS.
	// A set of groups that are not allowed for users authenticated by RADIUS.
	// +listType=set
	ExcludeGroups []*string `json:"excludeGroups,omitempty" tf:"exclude_groups,omitempty"`

	// Update messages.
	// Interval between scheduled RADIUS Interim-Update messages.
	InterimUpdate *string `json:"interimUpdate,omitempty" tf:"interim_update,omitempty"`

	// (Boolean) An option whether to use RADIUS server.
	// An option whether to use RADIUS server.
	UseRadius *bool `json:"useRadius,omitempty" tf:"use_radius,omitempty"`
}

type UserAaaObservation struct {

	// (Boolean) An option that enables accounting for users.
	// An option that enables accounting for users.
	Accounting *bool `json:"accounting,omitempty" tf:"accounting,omitempty"`

	// (String) The user group that is used by default for users authenticated via a RADIUS server.
	// The user group that is used by default for users authenticated via a RADIUS server.
	DefaultGroup *string `json:"defaultGroup,omitempty" tf:"default_group,omitempty"`

	// (Set of String) A set of groups that are not allowed for users authenticated by RADIUS.
	// A set of groups that are not allowed for users authenticated by RADIUS.
	// +listType=set
	ExcludeGroups []*string `json:"excludeGroups,omitempty" tf:"exclude_groups,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Update messages.
	// Interval between scheduled RADIUS Interim-Update messages.
	InterimUpdate *string `json:"interimUpdate,omitempty" tf:"interim_update,omitempty"`

	// (Boolean) An option whether to use RADIUS server.
	// An option whether to use RADIUS server.
	UseRadius *bool `json:"useRadius,omitempty" tf:"use_radius,omitempty"`
}

type UserAaaParameters struct {

	// (Boolean) An option that enables accounting for users.
	// An option that enables accounting for users.
	// +kubebuilder:validation:Optional
	Accounting *bool `json:"accounting,omitempty" tf:"accounting,omitempty"`

	// (String) The user group that is used by default for users authenticated via a RADIUS server.
	// The user group that is used by default for users authenticated via a RADIUS server.
	// +kubebuilder:validation:Optional
	DefaultGroup *string `json:"defaultGroup,omitempty" tf:"default_group,omitempty"`

	// (Set of String) A set of groups that are not allowed for users authenticated by RADIUS.
	// A set of groups that are not allowed for users authenticated by RADIUS.
	// +kubebuilder:validation:Optional
	// +listType=set
	ExcludeGroups []*string `json:"excludeGroups,omitempty" tf:"exclude_groups,omitempty"`

	// Update messages.
	// Interval between scheduled RADIUS Interim-Update messages.
	// +kubebuilder:validation:Optional
	InterimUpdate *string `json:"interimUpdate,omitempty" tf:"interim_update,omitempty"`

	// (Boolean) An option whether to use RADIUS server.
	// An option whether to use RADIUS server.
	// +kubebuilder:validation:Optional
	UseRadius *bool `json:"useRadius,omitempty" tf:"use_radius,omitempty"`
}

// UserAaaSpec defines the desired state of UserAaa
type UserAaaSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserAaaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserAaaInitParameters `json:"initProvider,omitempty"`
}

// UserAaaStatus defines the observed state of UserAaa.
type UserAaaStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserAaaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserAaa is the Schema for the UserAaas API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type UserAaa struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserAaaSpec   `json:"spec"`
	Status            UserAaaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserAaaList contains a list of UserAaas
type UserAaaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserAaa `json:"items"`
}

// Repository type metadata.
var (
	UserAaa_Kind             = "UserAaa"
	UserAaa_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserAaa_Kind}.String()
	UserAaa_KindAPIVersion   = UserAaa_Kind + "." + CRDGroupVersion.String()
	UserAaa_GroupVersionKind = CRDGroupVersion.WithKind(UserAaa_Kind)
)

func init() {
	SchemeBuilder.Register(&UserAaa{}, &UserAaaList{})
}
