apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/ip.routeros.m.sindrip.io_firewallfiltermenus.yaml
  - crd/routeros.m.sindrip.io_providerconfigs.yaml
  - crd/routeros.m.sindrip.io_providerconfigusages.yaml
  - rbac/role.yaml
  - rbac/service_account.yaml
  - rbac/role_binding.yaml
