apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/ip.routeros.sindrip.io_firewallfiltermenus.yaml
  - rbac/role.yaml
  - rbac/service_account.yaml
  - rbac/role_binding.yaml
