apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-routeros-native
rules:
  - apiGroups:
      - ip.routeros.sindrip.io
    resources:
      - firewallfiltermenus
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ip.routeros.sindrip.io
    resources:
      - firewallfiltermenus/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ip.routeros.sindrip.io
    resources:
      - firewallfiltermenus/finalizers
    verbs:
      - update
  - apiGroups:
      - routeros.sindrip.io
    resources:
      - providerconfigs
    verbs:
      - get
  - apiGroups:
      - routeros.sindrip.io
    resources:
      - providerconfigusages
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
