// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DHCPServerOptionSetsInitParameters struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The name of the DHCPv6 option.
	// The name of the DHCPv6 option.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) The list of options.
	// The list of options.
	// +listType=set
	Options []*string `json:"options,omitempty" tf:"options,omitempty"`
}

type DHCPServerOptionSetsObservation struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the DHCPv6 option.
	// The name of the DHCPv6 option.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) The list of options.
	// The list of options.
	// +listType=set
	Options []*string `json:"options,omitempty" tf:"options,omitempty"`
}

type DHCPServerOptionSetsParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The name of the DHCPv6 option.
	// The name of the DHCPv6 option.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) The list of options.
	// The list of options.
	// +kubebuilder:validation:Optional
	// +listType=set
	Options []*string `json:"options,omitempty" tf:"options,omitempty"`
}

// DHCPServerOptionSetsSpec defines the desired state of DHCPServerOptionSets
type DHCPServerOptionSetsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DHCPServerOptionSetsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DHCPServerOptionSetsInitParameters `json:"initProvider,omitempty"`
}

// DHCPServerOptionSetsStatus defines the observed state of DHCPServerOptionSets.
type DHCPServerOptionSetsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DHCPServerOptionSetsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DHCPServerOptionSets is the Schema for the DHCPServerOptionSetss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type DHCPServerOptionSets struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DHCPServerOptionSetsSpec   `json:"spec"`
	Status DHCPServerOptionSetsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DHCPServerOptionSetsList contains a list of DHCPServerOptionSetss
type DHCPServerOptionSetsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DHCPServerOptionSets `json:"items"`
}

// Repository type metadata.
var (
	DHCPServerOptionSets_Kind             = "DHCPServerOptionSets"
	DHCPServerOptionSets_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DHCPServerOptionSets_Kind}.String()
	DHCPServerOptionSets_KindAPIVersion   = DHCPServerOptionSets_Kind + "." + CRDGroupVersion.String()
	DHCPServerOptionSets_GroupVersionKind = CRDGroupVersion.WithKind(DHCPServerOptionSets_Kind)
)

func init() {
	SchemeBuilder.Register(&DHCPServerOptionSets{}, &DHCPServerOptionSetsList{})
}
