// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetRouterosDeviceModel sets provided value as "routeros.device.model" attribute.
func (rb *ResourceBuilder) SetRouterosDeviceModel(val string) {
	if rb.config.RouterosDeviceModel.Enabled {
		rb.res.Attributes().PutStr("routeros.device.model", val)
	}
}

// SetRouterosDeviceSerial sets provided value as "routeros.device.serial" attribute.
func (rb *ResourceBuilder) SetRouterosDeviceSerial(val string) {
	if rb.config.RouterosDeviceSerial.Enabled {
		rb.res.Attributes().PutStr("routeros.device.serial", val)
	}
}

// SetRouterosOsVersion sets provided value as "routeros.os.version" attribute.
func (rb *ResourceBuilder) SetRouterosOsVersion(val string) {
	if rb.config.RouterosOsVersion.Enabled {
		rb.res.Attributes().PutStr("routeros.os.version", val)
	}
}

// SetServiceInstanceID sets provided value as "service.instance.id" attribute.
func (rb *ResourceBuilder) SetServiceInstanceID(val string) {
	if rb.config.ServiceInstanceID.Enabled {
		rb.res.Attributes().PutStr("service.instance.id", val)
	}
}

// SetServiceName sets provided value as "service.name" attribute.
func (rb *ResourceBuilder) SetServiceName(val string) {
	if rb.config.ServiceName.Enabled {
		rb.res.Attributes().PutStr("service.name", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
