// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EthernetSwitchPortIsolationInitParameters struct {

	// (String) Forces ingress traffic to be forwarded to a specific interface. Multiple interfaces can be specified by separating them with a comma.
	// Forces ingress traffic to be forwarded to a specific interface. Multiple interfaces can be specified by separating them with a comma.
	ForwardingOverride *string `json:"forwardingOverride,omitempty" tf:"forwarding_override,omitempty"`

	// (String) Port name.
	// Port name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EthernetSwitchPortIsolationObservation struct {

	// (String) Forces ingress traffic to be forwarded to a specific interface. Multiple interfaces can be specified by separating them with a comma.
	// Forces ingress traffic to be forwarded to a specific interface. Multiple interfaces can be specified by separating them with a comma.
	ForwardingOverride *string `json:"forwardingOverride,omitempty" tf:"forwarding_override,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	Invalid *bool `json:"invalid,omitempty" tf:"invalid,omitempty"`

	// (String) Port name.
	// Port name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the switch.
	// Name of the switch.
	Switch *string `json:"switch,omitempty" tf:"switch,omitempty"`
}

type EthernetSwitchPortIsolationParameters struct {

	// (String) Forces ingress traffic to be forwarded to a specific interface. Multiple interfaces can be specified by separating them with a comma.
	// Forces ingress traffic to be forwarded to a specific interface. Multiple interfaces can be specified by separating them with a comma.
	// +kubebuilder:validation:Optional
	ForwardingOverride *string `json:"forwardingOverride,omitempty" tf:"forwarding_override,omitempty"`

	// (String) Port name.
	// Port name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// EthernetSwitchPortIsolationSpec defines the desired state of EthernetSwitchPortIsolation
type EthernetSwitchPortIsolationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EthernetSwitchPortIsolationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EthernetSwitchPortIsolationInitParameters `json:"initProvider,omitempty"`
}

// EthernetSwitchPortIsolationStatus defines the observed state of EthernetSwitchPortIsolation.
type EthernetSwitchPortIsolationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EthernetSwitchPortIsolationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EthernetSwitchPortIsolation is the Schema for the EthernetSwitchPortIsolations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type EthernetSwitchPortIsolation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EthernetSwitchPortIsolationSpec   `json:"spec"`
	Status EthernetSwitchPortIsolationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EthernetSwitchPortIsolationList contains a list of EthernetSwitchPortIsolations
type EthernetSwitchPortIsolationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EthernetSwitchPortIsolation `json:"items"`
}

// Repository type metadata.
var (
	EthernetSwitchPortIsolation_Kind             = "EthernetSwitchPortIsolation"
	EthernetSwitchPortIsolation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EthernetSwitchPortIsolation_Kind}.String()
	EthernetSwitchPortIsolation_KindAPIVersion   = EthernetSwitchPortIsolation_Kind + "." + CRDGroupVersion.String()
	EthernetSwitchPortIsolation_GroupVersionKind = CRDGroupVersion.WithKind(EthernetSwitchPortIsolation_Kind)
)

func init() {
	SchemeBuilder.Register(&EthernetSwitchPortIsolation{}, &EthernetSwitchPortIsolationList{})
}
