// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EthernetSwitchCrsEgressVlanTagInitParameters struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Set of String) Ports that are tagged in egress.
	// Ports that are tagged in egress.
	// +listType=set
	TaggedPorts []*string `json:"taggedPorts,omitempty" tf:"tagged_ports,omitempty"`

	// (Number) VLAN ID which is tagged in egress.
	// VLAN ID which is tagged in egress.
	VlanID *int64 `json:"vlanId,omitempty" tf:"vlan_id,omitempty"`
}

type EthernetSwitchCrsEgressVlanTagObservation struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Boolean) Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	Dynamic *bool `json:"dynamic,omitempty" tf:"dynamic,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) Ports that are tagged in egress.
	// Ports that are tagged in egress.
	// +listType=set
	TaggedPorts []*string `json:"taggedPorts,omitempty" tf:"tagged_ports,omitempty"`

	// (Number) VLAN ID which is tagged in egress.
	// VLAN ID which is tagged in egress.
	VlanID *int64 `json:"vlanId,omitempty" tf:"vlan_id,omitempty"`
}

type EthernetSwitchCrsEgressVlanTagParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Set of String) Ports that are tagged in egress.
	// Ports that are tagged in egress.
	// +kubebuilder:validation:Optional
	// +listType=set
	TaggedPorts []*string `json:"taggedPorts,omitempty" tf:"tagged_ports,omitempty"`

	// (Number) VLAN ID which is tagged in egress.
	// VLAN ID which is tagged in egress.
	// +kubebuilder:validation:Optional
	VlanID *int64 `json:"vlanId,omitempty" tf:"vlan_id,omitempty"`
}

// EthernetSwitchCrsEgressVlanTagSpec defines the desired state of EthernetSwitchCrsEgressVlanTag
type EthernetSwitchCrsEgressVlanTagSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EthernetSwitchCrsEgressVlanTagParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EthernetSwitchCrsEgressVlanTagInitParameters `json:"initProvider,omitempty"`
}

// EthernetSwitchCrsEgressVlanTagStatus defines the observed state of EthernetSwitchCrsEgressVlanTag.
type EthernetSwitchCrsEgressVlanTagStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EthernetSwitchCrsEgressVlanTagObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EthernetSwitchCrsEgressVlanTag is the Schema for the EthernetSwitchCrsEgressVlanTags API. Resource for managing CRS (Cloud Router Switch) series device properties.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type EthernetSwitchCrsEgressVlanTag struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EthernetSwitchCrsEgressVlanTagSpec   `json:"spec"`
	Status            EthernetSwitchCrsEgressVlanTagStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EthernetSwitchCrsEgressVlanTagList contains a list of EthernetSwitchCrsEgressVlanTags
type EthernetSwitchCrsEgressVlanTagList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EthernetSwitchCrsEgressVlanTag `json:"items"`
}

// Repository type metadata.
var (
	EthernetSwitchCrsEgressVlanTag_Kind             = "EthernetSwitchCrsEgressVlanTag"
	EthernetSwitchCrsEgressVlanTag_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EthernetSwitchCrsEgressVlanTag_Kind}.String()
	EthernetSwitchCrsEgressVlanTag_KindAPIVersion   = EthernetSwitchCrsEgressVlanTag_Kind + "." + CRDGroupVersion.String()
	EthernetSwitchCrsEgressVlanTag_GroupVersionKind = CRDGroupVersion.WithKind(EthernetSwitchCrsEgressVlanTag_Kind)
)

func init() {
	SchemeBuilder.Register(&EthernetSwitchCrsEgressVlanTag{}, &EthernetSwitchCrsEgressVlanTagList{})
}
