// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type InterfaceListMemberInitParameters struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String)
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (String)
	List *string `json:"list,omitempty" tf:"list,omitempty"`
}

type InterfaceListMemberObservation struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Boolean)
	Dynamic *bool `json:"dynamic,omitempty" tf:"dynamic,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (String)
	List *string `json:"list,omitempty" tf:"list,omitempty"`
}

type InterfaceListMemberParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	List *string `json:"list,omitempty" tf:"list,omitempty"`
}

// InterfaceListMemberSpec defines the desired state of InterfaceListMember
type InterfaceListMemberSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InterfaceListMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InterfaceListMemberInitParameters `json:"initProvider,omitempty"`
}

// InterfaceListMemberStatus defines the observed state of InterfaceListMember.
type InterfaceListMemberStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               InterfaceListMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InterfaceListMember is the Schema for the InterfaceListMembers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type InterfaceListMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interface) || (has(self.initProvider) && has(self.initProvider.interface))",message="spec.forProvider.interface is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.list) || (has(self.initProvider) && has(self.initProvider.list))",message="spec.forProvider.list is a required parameter"
	Spec   InterfaceListMemberSpec   `json:"spec"`
	Status InterfaceListMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InterfaceListMemberList contains a list of InterfaceListMembers
type InterfaceListMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InterfaceListMember `json:"items"`
}

// Repository type metadata.
var (
	InterfaceListMember_Kind             = "InterfaceListMember"
	InterfaceListMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InterfaceListMember_Kind}.String()
	InterfaceListMember_KindAPIVersion   = InterfaceListMember_Kind + "." + CRDGroupVersion.String()
	InterfaceListMember_GroupVersionKind = CRDGroupVersion.WithKind(InterfaceListMember_Kind)
)

func init() {
	SchemeBuilder.Register(&InterfaceListMember{}, &InterfaceListMemberList{})
}
