// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WireguardPeerInitParameters struct {

	// all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses.
	// List of IP (v4 or v6) addresses with CIDR masks from which incoming traffic for this peer is allowed and to which outgoing traffic for this peer is directed. The catch-all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses.
	AllowedAddress []*string `json:"allowedAddress,omitempty" tf:"allowed_address,omitempty"`

	// (String) When imported using a qr code for a client (for example, a phone), then this address for the wg interface is set on that device.
	// When imported using a qr code for a client (for example, a phone), then this address for the wg interface is set on that device.
	ClientAddress *string `json:"clientAddress,omitempty" tf:"client_address,omitempty"`

	// (String) Specify when using WireGuard Server as a VPN gateway for peer traffic.
	// Specify when using WireGuard Server as a VPN gateway for peer traffic.
	ClientDNS *string `json:"clientDns,omitempty" tf:"client_dns,omitempty"`

	// (String) The IP address and port number of the WireGuard Server.
	// The IP address and port number of the WireGuard Server.
	ClientEndpoint *string `json:"clientEndpoint,omitempty" tf:"client_endpoint,omitempty"`

	// keepalive but from peer side.
	// Same as persistent-keepalive but from peer side.
	ClientKeepalive *string `json:"clientKeepalive,omitempty" tf:"client_keepalive,omitempty"`

	// (Number) The local port upon which this WireGuard tunnel will listen for incoming traffic from peers, and the port from which it will source outgoing packets.
	// The local port upon which this WireGuard tunnel will listen for incoming traffic from peers, and the port from which it will source outgoing packets.
	ClientListenPort *int64 `json:"clientListenPort,omitempty" tf:"client_listen_port,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) An endpoint IP or hostname can be left blank to allow remote connection from any address.
	// An endpoint IP or hostname can be left blank to allow remote connection from any address.
	EndpointAddress *string `json:"endpointAddress,omitempty" tf:"endpoint_address,omitempty"`

	// (String) An endpoint port can be left blank to allow remote connection from any port.
	// An endpoint port can be left blank to allow remote connection from any port.
	EndpointPort *string `json:"endpointPort,omitempty" tf:"endpoint_port,omitempty"`

	// (String) Name of the interface.
	// Name of the interface.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// address` or `current-endpoint-address` causing unnecessary system logs to be written.
	// Specifies if peer is intended to be connection initiator or only responder. Should be used on WireGuard devices that are used as `servers` for other devices as clients to connect to. Otherwise router will all repeatedly try to connect `endpoint-address` or `current-endpoint-address` causing unnecessary system logs to be written.
	IsResponder *bool `json:"isResponder,omitempty" tf:"is_responder,omitempty"`

	// (String) Name of the tunnel.
	// Name of the tunnel.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid persistently. For example, if the interface very rarely sends traffic, but it might at anytime receive traffic from a peer, and it is behind NAT, the interface might benefit from having a persistent keepalive interval of 25 seconds.
	// A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid persistently. For example, if the interface very rarely sends traffic, but it might at anytime receive traffic from a peer, and it is behind NAT, the interface might benefit from having a persistent keepalive interval of 25 seconds.
	PersistentKeepalive *string `json:"persistentKeepalive,omitempty" tf:"persistent_keepalive,omitempty"`

	// key cryptography to be mixed into the already existing public-key cryptography, for post-quantum resistance.
	// A **base64** preshared key. Optional, and may be omitted. This option adds an additional layer of symmetric-key cryptography to be mixed into the already existing public-key cryptography, for post-quantum resistance.
	PresharedKeySecretRef *v2.LocalSecretKeySelector `json:"presharedKeySecretRef,omitempty" tf:"-"`

	// (String) A base64 private key. If not specified, it will be automatically generated upon interface creation.
	// A base64 private key. If not specified, it will be automatically generated upon interface creation.
	PrivateKeySecretRef *v2.LocalSecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`

	// (String) The remote peer's calculated public key.
	// The remote peer's calculated public key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`
}

type WireguardPeerObservation struct {

	// all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses.
	// List of IP (v4 or v6) addresses with CIDR masks from which incoming traffic for this peer is allowed and to which outgoing traffic for this peer is directed. The catch-all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses.
	AllowedAddress []*string `json:"allowedAddress,omitempty" tf:"allowed_address,omitempty"`

	// (String) When imported using a qr code for a client (for example, a phone), then this address for the wg interface is set on that device.
	// When imported using a qr code for a client (for example, a phone), then this address for the wg interface is set on that device.
	ClientAddress *string `json:"clientAddress,omitempty" tf:"client_address,omitempty"`

	// (String) Specify when using WireGuard Server as a VPN gateway for peer traffic.
	// Specify when using WireGuard Server as a VPN gateway for peer traffic.
	ClientDNS *string `json:"clientDns,omitempty" tf:"client_dns,omitempty"`

	// (String) The IP address and port number of the WireGuard Server.
	// The IP address and port number of the WireGuard Server.
	ClientEndpoint *string `json:"clientEndpoint,omitempty" tf:"client_endpoint,omitempty"`

	// keepalive but from peer side.
	// Same as persistent-keepalive but from peer side.
	ClientKeepalive *string `json:"clientKeepalive,omitempty" tf:"client_keepalive,omitempty"`

	// (Number) The local port upon which this WireGuard tunnel will listen for incoming traffic from peers, and the port from which it will source outgoing packets.
	// The local port upon which this WireGuard tunnel will listen for incoming traffic from peers, and the port from which it will source outgoing packets.
	ClientListenPort *int64 `json:"clientListenPort,omitempty" tf:"client_listen_port,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The most recent source IP address of correctly authenticated packets from the peer.
	// The most recent source IP address of correctly authenticated packets from the peer.
	CurrentEndpointAddress *string `json:"currentEndpointAddress,omitempty" tf:"current_endpoint_address,omitempty"`

	// (Number) The most recent source IP port of correctly authenticated packets from the peer.
	// The most recent source IP port of correctly authenticated packets from the peer.
	CurrentEndpointPort *int64 `json:"currentEndpointPort,omitempty" tf:"current_endpoint_port,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Boolean) Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	Dynamic *bool `json:"dynamic,omitempty" tf:"dynamic,omitempty"`

	// (String) An endpoint IP or hostname can be left blank to allow remote connection from any address.
	// An endpoint IP or hostname can be left blank to allow remote connection from any address.
	EndpointAddress *string `json:"endpointAddress,omitempty" tf:"endpoint_address,omitempty"`

	// (String) An endpoint port can be left blank to allow remote connection from any port.
	// An endpoint port can be left blank to allow remote connection from any port.
	EndpointPort *string `json:"endpointPort,omitempty" tf:"endpoint_port,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the interface.
	// Name of the interface.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// address` or `current-endpoint-address` causing unnecessary system logs to be written.
	// Specifies if peer is intended to be connection initiator or only responder. Should be used on WireGuard devices that are used as `servers` for other devices as clients to connect to. Otherwise router will all repeatedly try to connect `endpoint-address` or `current-endpoint-address` causing unnecessary system logs to be written.
	IsResponder *bool `json:"isResponder,omitempty" tf:"is_responder,omitempty"`

	// (String) Time in seconds after the last successful handshake.
	// Time in seconds after the last successful handshake.
	LastHandshake *string `json:"lastHandshake,omitempty" tf:"last_handshake,omitempty"`

	// (String) Name of the tunnel.
	// Name of the tunnel.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid persistently. For example, if the interface very rarely sends traffic, but it might at anytime receive traffic from a peer, and it is behind NAT, the interface might benefit from having a persistent keepalive interval of 25 seconds.
	// A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid persistently. For example, if the interface very rarely sends traffic, but it might at anytime receive traffic from a peer, and it is behind NAT, the interface might benefit from having a persistent keepalive interval of 25 seconds.
	PersistentKeepalive *string `json:"persistentKeepalive,omitempty" tf:"persistent_keepalive,omitempty"`

	// (String) The remote peer's calculated public key.
	// The remote peer's calculated public key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (String) The total amount of bytes received from the peer.
	// The total amount of bytes received from the peer.
	Rx *string `json:"rx,omitempty" tf:"rx,omitempty"`

	// (String) The total amount of bytes transmitted to the peer.
	// The total amount of bytes transmitted to the peer.
	Tx *string `json:"tx,omitempty" tf:"tx,omitempty"`
}

type WireguardPeerParameters struct {

	// all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses.
	// List of IP (v4 or v6) addresses with CIDR masks from which incoming traffic for this peer is allowed and to which outgoing traffic for this peer is directed. The catch-all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses.
	// +kubebuilder:validation:Optional
	AllowedAddress []*string `json:"allowedAddress,omitempty" tf:"allowed_address,omitempty"`

	// (String) When imported using a qr code for a client (for example, a phone), then this address for the wg interface is set on that device.
	// When imported using a qr code for a client (for example, a phone), then this address for the wg interface is set on that device.
	// +kubebuilder:validation:Optional
	ClientAddress *string `json:"clientAddress,omitempty" tf:"client_address,omitempty"`

	// (String) Specify when using WireGuard Server as a VPN gateway for peer traffic.
	// Specify when using WireGuard Server as a VPN gateway for peer traffic.
	// +kubebuilder:validation:Optional
	ClientDNS *string `json:"clientDns,omitempty" tf:"client_dns,omitempty"`

	// (String) The IP address and port number of the WireGuard Server.
	// The IP address and port number of the WireGuard Server.
	// +kubebuilder:validation:Optional
	ClientEndpoint *string `json:"clientEndpoint,omitempty" tf:"client_endpoint,omitempty"`

	// keepalive but from peer side.
	// Same as persistent-keepalive but from peer side.
	// +kubebuilder:validation:Optional
	ClientKeepalive *string `json:"clientKeepalive,omitempty" tf:"client_keepalive,omitempty"`

	// (Number) The local port upon which this WireGuard tunnel will listen for incoming traffic from peers, and the port from which it will source outgoing packets.
	// The local port upon which this WireGuard tunnel will listen for incoming traffic from peers, and the port from which it will source outgoing packets.
	// +kubebuilder:validation:Optional
	ClientListenPort *int64 `json:"clientListenPort,omitempty" tf:"client_listen_port,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) An endpoint IP or hostname can be left blank to allow remote connection from any address.
	// An endpoint IP or hostname can be left blank to allow remote connection from any address.
	// +kubebuilder:validation:Optional
	EndpointAddress *string `json:"endpointAddress,omitempty" tf:"endpoint_address,omitempty"`

	// (String) An endpoint port can be left blank to allow remote connection from any port.
	// An endpoint port can be left blank to allow remote connection from any port.
	// +kubebuilder:validation:Optional
	EndpointPort *string `json:"endpointPort,omitempty" tf:"endpoint_port,omitempty"`

	// (String) Name of the interface.
	// Name of the interface.
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// address` or `current-endpoint-address` causing unnecessary system logs to be written.
	// Specifies if peer is intended to be connection initiator or only responder. Should be used on WireGuard devices that are used as `servers` for other devices as clients to connect to. Otherwise router will all repeatedly try to connect `endpoint-address` or `current-endpoint-address` causing unnecessary system logs to be written.
	// +kubebuilder:validation:Optional
	IsResponder *bool `json:"isResponder,omitempty" tf:"is_responder,omitempty"`

	// (String) Name of the tunnel.
	// Name of the tunnel.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid persistently. For example, if the interface very rarely sends traffic, but it might at anytime receive traffic from a peer, and it is behind NAT, the interface might benefit from having a persistent keepalive interval of 25 seconds.
	// A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid persistently. For example, if the interface very rarely sends traffic, but it might at anytime receive traffic from a peer, and it is behind NAT, the interface might benefit from having a persistent keepalive interval of 25 seconds.
	// +kubebuilder:validation:Optional
	PersistentKeepalive *string `json:"persistentKeepalive,omitempty" tf:"persistent_keepalive,omitempty"`

	// key cryptography to be mixed into the already existing public-key cryptography, for post-quantum resistance.
	// A **base64** preshared key. Optional, and may be omitted. This option adds an additional layer of symmetric-key cryptography to be mixed into the already existing public-key cryptography, for post-quantum resistance.
	// +kubebuilder:validation:Optional
	PresharedKeySecretRef *v2.LocalSecretKeySelector `json:"presharedKeySecretRef,omitempty" tf:"-"`

	// (String) A base64 private key. If not specified, it will be automatically generated upon interface creation.
	// A base64 private key. If not specified, it will be automatically generated upon interface creation.
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef *v2.LocalSecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`

	// (String) The remote peer's calculated public key.
	// The remote peer's calculated public key.
	// +kubebuilder:validation:Optional
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`
}

// WireguardPeerSpec defines the desired state of WireguardPeer
type WireguardPeerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WireguardPeerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WireguardPeerInitParameters `json:"initProvider,omitempty"`
}

// WireguardPeerStatus defines the observed state of WireguardPeer.
type WireguardPeerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WireguardPeerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WireguardPeer is the Schema for the WireguardPeers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type WireguardPeer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.allowedAddress) || (has(self.initProvider) && has(self.initProvider.allowedAddress))",message="spec.forProvider.allowedAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interface) || (has(self.initProvider) && has(self.initProvider.interface))",message="spec.forProvider.interface is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.publicKey) || (has(self.initProvider) && has(self.initProvider.publicKey))",message="spec.forProvider.publicKey is a required parameter"
	Spec   WireguardPeerSpec   `json:"spec"`
	Status WireguardPeerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WireguardPeerList contains a list of WireguardPeers
type WireguardPeerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WireguardPeer `json:"items"`
}

// Repository type metadata.
var (
	WireguardPeer_Kind             = "WireguardPeer"
	WireguardPeer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WireguardPeer_Kind}.String()
	WireguardPeer_KindAPIVersion   = WireguardPeer_Kind + "." + CRDGroupVersion.String()
	WireguardPeer_GroupVersionKind = CRDGroupVersion.WithKind(WireguardPeer_Kind)
)

func init() {
	SchemeBuilder.Register(&WireguardPeer{}, &WireguardPeerList{})
}
