// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DHCPServerLeaseInitParameters struct {

	// (String) The IP address of the DHCP lease to be created.
	// The IP address of the DHCP lease to be created.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Address list to which address will be added if lease is bound.
	// Address list to which address will be added if lease is bound.
	AddressLists *string `json:"addressLists,omitempty" tf:"address_lists,omitempty"`

	// (Boolean) Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue *bool `json:"allowDualStackQueue,omitempty" tf:"allow_dual_stack_queue,omitempty"`

	// (Boolean) Send all replies as broadcasts.
	// Send all replies as broadcasts.
	AlwaysBroadcast *bool `json:"alwaysBroadcast,omitempty" tf:"always_broadcast,omitempty"`

	// (Boolean) Whether to block access for this DHCP client (true|false).
	// Whether to block access for this DHCP client (true|false).
	BlockAccess *bool `json:"blockAccess,omitempty" tf:"block_access,omitempty"`

	// (String) If specified, must match DHCP 'client identifier' option of the request.
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Add additional DHCP options.
	// Add additional DHCP options.
	DHCPOption *string `json:"dhcpOption,omitempty" tf:"dhcp_option,omitempty"`

	// (String) Add additional set of DHCP options.
	// Add additional set of DHCP options.
	DHCPOptionSet *string `json:"dhcpOptionSet,omitempty" tf:"dhcp_option_set,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// limit parameter set.
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore *string `json:"insertQueueBefore,omitempty" tf:"insert_queue_before,omitempty"`

	// (String) Time that the client may use the address. If set to 0s lease will never expire.
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime *string `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// (String) The MAC addreess of the DHCP lease to be created.
	// The MAC addreess of the DHCP lease to be created.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit *string `json:"rateLimit,omitempty" tf:"rate_limit,omitempty"`

	// (String) Server name which serves this client.
	// Server name which serves this client.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// (Boolean) When this option is set server uses source MAC address instead of received CHADDR to assign address.
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac *bool `json:"useSrcMac,omitempty" tf:"use_src_mac,omitempty"`
}

type DHCPServerLeaseObservation struct {

	// (String) The IP address of the machine currently holding the DHCP lease.
	// The IP address of the machine currently holding the DHCP lease.
	ActiveAddress *string `json:"activeAddress,omitempty" tf:"active_address,omitempty"`

	// id of the client.
	// Actual client-id of the client.
	ActiveClientID *string `json:"activeClientId,omitempty" tf:"active_client_id,omitempty"`

	// (String) The hostname of the machine currently holding the DHCP lease.
	// The hostname of the machine currently holding the DHCP lease.
	ActiveHostname *string `json:"activeHostname,omitempty" tf:"active_hostname,omitempty"`

	// (String) The MAC address of of the machine currently holding the DHCP lease.
	// The MAC address of of the machine currently holding the DHCP lease.
	ActiveMacAddress *string `json:"activeMacAddress,omitempty" tf:"active_mac_address,omitempty"`

	// (String) Actual dhcp server, which serves this client.
	// Actual dhcp server, which serves this client.
	ActiveServer *string `json:"activeServer,omitempty" tf:"active_server,omitempty"`

	// (String) The IP address of the DHCP lease to be created.
	// The IP address of the DHCP lease to be created.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Address list to which address will be added if lease is bound.
	// Address list to which address will be added if lease is bound.
	AddressLists *string `json:"addressLists,omitempty" tf:"address_lists,omitempty"`

	// (String) Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	// Circuit ID of DHCP relay agent. If each character should be valid ASCII text symbol or else this value is displayed as hex dump.
	AgentCircuitID *string `json:"agentCircuitId,omitempty" tf:"agent_circuit_id,omitempty"`

	// (String) Remote ID, set by DHCP relay agent.
	// Remote ID, set by DHCP relay agent.
	AgentRemoteID *string `json:"agentRemoteId,omitempty" tf:"agent_remote_id,omitempty"`

	// (Boolean) Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	AllowDualStackQueue *bool `json:"allowDualStackQueue,omitempty" tf:"allow_dual_stack_queue,omitempty"`

	// (Boolean) Send all replies as broadcasts.
	// Send all replies as broadcasts.
	AlwaysBroadcast *bool `json:"alwaysBroadcast,omitempty" tf:"always_broadcast,omitempty"`

	// (Boolean) Whether to block access for this DHCP client (true|false).
	// Whether to block access for this DHCP client (true|false).
	BlockAccess *bool `json:"blockAccess,omitempty" tf:"block_access,omitempty"`

	// (Boolean) Whether the lease is blocked.
	// Whether the lease is blocked.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// (String) Class ID of the client. This option is available in RouterOS starting from version 7.16.
	// Class ID of the client. This option is available in RouterOS starting from version 7.16.
	ClassID *string `json:"classId,omitempty" tf:"class_id,omitempty"`

	// (String) If specified, must match DHCP 'client identifier' option of the request.
	// If specified, must match DHCP 'client identifier' option of the request.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Add additional DHCP options.
	// Add additional DHCP options.
	DHCPOption *string `json:"dhcpOption,omitempty" tf:"dhcp_option,omitempty"`

	// (String) Add additional set of DHCP options.
	// Add additional set of DHCP options.
	DHCPOptionSet *string `json:"dhcpOptionSet,omitempty" tf:"dhcp_option_set,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Boolean) Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device.
	// Whether the dhcp lease is static or dynamic. Dynamic leases are not guaranteed to continue to be assigned to that specific device.
	Dynamic *bool `json:"dynamic,omitempty" tf:"dynamic,omitempty"`

	// (String) Time until lease expires.
	// Time until lease expires.
	ExpiresAfter *string `json:"expiresAfter,omitempty" tf:"expires_after,omitempty"`

	// (String) The hostname of the device
	// The hostname of the device
	HostName *string `json:"hostName,omitempty" tf:"host_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// limit parameter set.
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	InsertQueueBefore *string `json:"insertQueueBefore,omitempty" tf:"insert_queue_before,omitempty"`

	// (String)
	LastSeen *string `json:"lastSeen,omitempty" tf:"last_seen,omitempty"`

	// (String) Time that the client may use the address. If set to 0s lease will never expire.
	// Time that the client may use the address. If set to 0s lease will never expire.
	LeaseTime *string `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// (String) The MAC addreess of the DHCP lease to be created.
	// The MAC addreess of the DHCP lease to be created.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) Shows if this dynamic lease is authenticated by RADIUS or not.
	// Shows if this dynamic lease is authenticated by RADIUS or not.
	Radius *string `json:"radius,omitempty" tf:"radius,omitempty"`

	// (String) Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	RateLimit *string `json:"rateLimit,omitempty" tf:"rate_limit,omitempty"`

	// (String) Server name which serves this client.
	// Server name which serves this client.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// (String) Source MAC address.
	// Source MAC address.
	SrcMacAddress *string `json:"srcMacAddress,omitempty" tf:"src_mac_address,omitempty"`

	// (String) Lease status.
	// Lease status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Boolean) When this option is set server uses source MAC address instead of received CHADDR to assign address.
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	UseSrcMac *bool `json:"useSrcMac,omitempty" tf:"use_src_mac,omitempty"`
}

type DHCPServerLeaseParameters struct {

	// (String) The IP address of the DHCP lease to be created.
	// The IP address of the DHCP lease to be created.
	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Address list to which address will be added if lease is bound.
	// Address list to which address will be added if lease is bound.
	// +kubebuilder:validation:Optional
	AddressLists *string `json:"addressLists,omitempty" tf:"address_lists,omitempty"`

	// (Boolean) Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	// Creates a single simple queue entry for both IPv4 and IPv6 addresses, uses the MAC address and DUID for identification.
	// +kubebuilder:validation:Optional
	AllowDualStackQueue *bool `json:"allowDualStackQueue,omitempty" tf:"allow_dual_stack_queue,omitempty"`

	// (Boolean) Send all replies as broadcasts.
	// Send all replies as broadcasts.
	// +kubebuilder:validation:Optional
	AlwaysBroadcast *bool `json:"alwaysBroadcast,omitempty" tf:"always_broadcast,omitempty"`

	// (Boolean) Whether to block access for this DHCP client (true|false).
	// Whether to block access for this DHCP client (true|false).
	// +kubebuilder:validation:Optional
	BlockAccess *bool `json:"blockAccess,omitempty" tf:"block_access,omitempty"`

	// (String) If specified, must match DHCP 'client identifier' option of the request.
	// If specified, must match DHCP 'client identifier' option of the request.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Add additional DHCP options.
	// Add additional DHCP options.
	// +kubebuilder:validation:Optional
	DHCPOption *string `json:"dhcpOption,omitempty" tf:"dhcp_option,omitempty"`

	// (String) Add additional set of DHCP options.
	// Add additional set of DHCP options.
	// +kubebuilder:validation:Optional
	DHCPOptionSet *string `json:"dhcpOptionSet,omitempty" tf:"dhcp_option_set,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// limit parameter set.
	// Specify where to place dynamic simple queue entries for static DCHP leases with rate-limit parameter set.
	// +kubebuilder:validation:Optional
	InsertQueueBefore *string `json:"insertQueueBefore,omitempty" tf:"insert_queue_before,omitempty"`

	// (String) Time that the client may use the address. If set to 0s lease will never expire.
	// Time that the client may use the address. If set to 0s lease will never expire.
	// +kubebuilder:validation:Optional
	LeaseTime *string `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// (String) The MAC addreess of the DHCP lease to be created.
	// The MAC addreess of the DHCP lease to be created.
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	// Adds a dynamic simple queue to limit IP's bandwidth to a specified rate. Requires the lease to be static.
	// +kubebuilder:validation:Optional
	RateLimit *string `json:"rateLimit,omitempty" tf:"rate_limit,omitempty"`

	// (String) Server name which serves this client.
	// Server name which serves this client.
	// +kubebuilder:validation:Optional
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// (Boolean) When this option is set server uses source MAC address instead of received CHADDR to assign address.
	// When this option is set server uses source MAC address instead of received CHADDR to assign address.
	// +kubebuilder:validation:Optional
	UseSrcMac *bool `json:"useSrcMac,omitempty" tf:"use_src_mac,omitempty"`
}

// DHCPServerLeaseSpec defines the desired state of DHCPServerLease
type DHCPServerLeaseSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DHCPServerLeaseParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DHCPServerLeaseInitParameters `json:"initProvider,omitempty"`
}

// DHCPServerLeaseStatus defines the observed state of DHCPServerLease.
type DHCPServerLeaseStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DHCPServerLeaseObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DHCPServerLease is the Schema for the DHCPServerLeases API. Creates a DHCP lease on the mikrotik device.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type DHCPServerLease struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.address) || (has(self.initProvider) && has(self.initProvider.address))",message="spec.forProvider.address is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.macAddress) || (has(self.initProvider) && has(self.initProvider.macAddress))",message="spec.forProvider.macAddress is a required parameter"
	Spec   DHCPServerLeaseSpec   `json:"spec"`
	Status DHCPServerLeaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DHCPServerLeaseList contains a list of DHCPServerLeases
type DHCPServerLeaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DHCPServerLease `json:"items"`
}

// Repository type metadata.
var (
	DHCPServerLease_Kind             = "DHCPServerLease"
	DHCPServerLease_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DHCPServerLease_Kind}.String()
	DHCPServerLease_KindAPIVersion   = DHCPServerLease_Kind + "." + CRDGroupVersion.String()
	DHCPServerLease_GroupVersionKind = CRDGroupVersion.WithKind(DHCPServerLease_Kind)
)

func init() {
	SchemeBuilder.Register(&DHCPServerLease{}, &DHCPServerLeaseList{})
}
