// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DHCPServerNetworkInitParameters struct {

	// (String) The network DHCP server(s) will lease addresses from.
	// The network DHCP server(s) will lease addresses from.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Boot filename.
	// Boot filename.
	BootFileName *string `json:"bootFileName,omitempty" tf:"boot_file_name,omitempty"`

	// (List of String) A list of IP addresses for one or more CAPsMAN system managers. DHCP Option 138 (capwap) will be used.
	// A list of IP addresses for one or more CAPsMAN system managers. DHCP Option 138 (capwap) will be used.
	CapsManager []*string `json:"capsManager,omitempty" tf:"caps_manager,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of String) Add additional DHCP options from the option list.
	// Add additional DHCP options from the option list.
	DHCPOption []*string `json:"dhcpOption,omitempty" tf:"dhcp_option,omitempty"`

	// (String) Add an additional set of DHCP options.
	// Add an additional set of DHCP options.
	DHCPOptionSet *string `json:"dhcpOptionSet,omitempty" tf:"dhcp_option_set,omitempty"`

	// server is set.
	// If set, then DHCP Server will not pass dynamic DNS servers configured on the router to the DHCP clients if no DNS Server in DNS-server is set.
	DNSNone *bool `json:"dnsNone,omitempty" tf:"dns_none,omitempty"`

	// (List of String) The DHCP client will use these as the default DNS servers. Two DNS servers can be specified to be used by the DHCP client as primary and secondary DNS servers.
	// The DHCP client will use these as the default DNS servers. Two DNS servers can be specified to be used by the DHCP client as primary and secondary DNS servers.
	DNSServer []*string `json:"dnsServer,omitempty" tf:"dns_server,omitempty"`

	// (String) The DHCP client will use this as the 'DNS domain' setting for the network adapter.
	// The DHCP client will use this as the 'DNS domain' setting for the network adapter.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The default gateway to be used by DHCP Client.
	// The default gateway to be used by DHCP Client.
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// netmask from network address will be used.
	// The actual network mask is to be used by the DHCP client. If set to '0' - netmask from network address will be used.
	Netmask *int64 `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// (String) The IP address of the next server to use in bootstrap.
	// The IP address of the next server to use in bootstrap.
	NextServer *string `json:"nextServer,omitempty" tf:"next_server,omitempty"`

	// (Boolean) If set, then DHCP Server will not pass NTP servers configured on the router to the DHCP clients.
	// If set, then DHCP Server will not pass NTP servers configured on the router to the DHCP clients.
	NtpNone *bool `json:"ntpNone,omitempty" tf:"ntp_none,omitempty"`

	// (List of String) The DHCP client will use these as the default NTP servers. Two NTP servers can be specified to be used by the DHCP client as primary and secondary NTP servers
	// The DHCP client will use these as the default NTP servers. Two NTP servers can be specified to be used by the DHCP client as primary and secondary NTP servers
	NtpServer []*string `json:"ntpServer,omitempty" tf:"ntp_server,omitempty"`

	// (List of String) The Windows DHCP client will use these as the default WINS servers. Two WINS servers can be specified to be used by the DHCP client as primary and secondary WINS servers
	// The Windows DHCP client will use these as the default WINS servers. Two WINS servers can be specified to be used by the DHCP client as primary and secondary WINS servers
	WinsServer []*string `json:"winsServer,omitempty" tf:"wins_server,omitempty"`
}

type DHCPServerNetworkObservation struct {

	// (String) The network DHCP server(s) will lease addresses from.
	// The network DHCP server(s) will lease addresses from.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Boot filename.
	// Boot filename.
	BootFileName *string `json:"bootFileName,omitempty" tf:"boot_file_name,omitempty"`

	// (List of String) A list of IP addresses for one or more CAPsMAN system managers. DHCP Option 138 (capwap) will be used.
	// A list of IP addresses for one or more CAPsMAN system managers. DHCP Option 138 (capwap) will be used.
	CapsManager []*string `json:"capsManager,omitempty" tf:"caps_manager,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of String) Add additional DHCP options from the option list.
	// Add additional DHCP options from the option list.
	DHCPOption []*string `json:"dhcpOption,omitempty" tf:"dhcp_option,omitempty"`

	// (String) Add an additional set of DHCP options.
	// Add an additional set of DHCP options.
	DHCPOptionSet *string `json:"dhcpOptionSet,omitempty" tf:"dhcp_option_set,omitempty"`

	// server is set.
	// If set, then DHCP Server will not pass dynamic DNS servers configured on the router to the DHCP clients if no DNS Server in DNS-server is set.
	DNSNone *bool `json:"dnsNone,omitempty" tf:"dns_none,omitempty"`

	// (List of String) The DHCP client will use these as the default DNS servers. Two DNS servers can be specified to be used by the DHCP client as primary and secondary DNS servers.
	// The DHCP client will use these as the default DNS servers. Two DNS servers can be specified to be used by the DHCP client as primary and secondary DNS servers.
	DNSServer []*string `json:"dnsServer,omitempty" tf:"dns_server,omitempty"`

	// (String) The DHCP client will use this as the 'DNS domain' setting for the network adapter.
	// The DHCP client will use this as the 'DNS domain' setting for the network adapter.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Boolean) Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	Dynamic *bool `json:"dynamic,omitempty" tf:"dynamic,omitempty"`

	// (String) The default gateway to be used by DHCP Client.
	// The default gateway to be used by DHCP Client.
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// netmask from network address will be used.
	// The actual network mask is to be used by the DHCP client. If set to '0' - netmask from network address will be used.
	Netmask *int64 `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// (String) The IP address of the next server to use in bootstrap.
	// The IP address of the next server to use in bootstrap.
	NextServer *string `json:"nextServer,omitempty" tf:"next_server,omitempty"`

	// (Boolean) If set, then DHCP Server will not pass NTP servers configured on the router to the DHCP clients.
	// If set, then DHCP Server will not pass NTP servers configured on the router to the DHCP clients.
	NtpNone *bool `json:"ntpNone,omitempty" tf:"ntp_none,omitempty"`

	// (List of String) The DHCP client will use these as the default NTP servers. Two NTP servers can be specified to be used by the DHCP client as primary and secondary NTP servers
	// The DHCP client will use these as the default NTP servers. Two NTP servers can be specified to be used by the DHCP client as primary and secondary NTP servers
	NtpServer []*string `json:"ntpServer,omitempty" tf:"ntp_server,omitempty"`

	// (List of String) The Windows DHCP client will use these as the default WINS servers. Two WINS servers can be specified to be used by the DHCP client as primary and secondary WINS servers
	// The Windows DHCP client will use these as the default WINS servers. Two WINS servers can be specified to be used by the DHCP client as primary and secondary WINS servers
	WinsServer []*string `json:"winsServer,omitempty" tf:"wins_server,omitempty"`
}

type DHCPServerNetworkParameters struct {

	// (String) The network DHCP server(s) will lease addresses from.
	// The network DHCP server(s) will lease addresses from.
	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Boot filename.
	// Boot filename.
	// +kubebuilder:validation:Optional
	BootFileName *string `json:"bootFileName,omitempty" tf:"boot_file_name,omitempty"`

	// (List of String) A list of IP addresses for one or more CAPsMAN system managers. DHCP Option 138 (capwap) will be used.
	// A list of IP addresses for one or more CAPsMAN system managers. DHCP Option 138 (capwap) will be used.
	// +kubebuilder:validation:Optional
	CapsManager []*string `json:"capsManager,omitempty" tf:"caps_manager,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (List of String) Add additional DHCP options from the option list.
	// Add additional DHCP options from the option list.
	// +kubebuilder:validation:Optional
	DHCPOption []*string `json:"dhcpOption,omitempty" tf:"dhcp_option,omitempty"`

	// (String) Add an additional set of DHCP options.
	// Add an additional set of DHCP options.
	// +kubebuilder:validation:Optional
	DHCPOptionSet *string `json:"dhcpOptionSet,omitempty" tf:"dhcp_option_set,omitempty"`

	// server is set.
	// If set, then DHCP Server will not pass dynamic DNS servers configured on the router to the DHCP clients if no DNS Server in DNS-server is set.
	// +kubebuilder:validation:Optional
	DNSNone *bool `json:"dnsNone,omitempty" tf:"dns_none,omitempty"`

	// (List of String) The DHCP client will use these as the default DNS servers. Two DNS servers can be specified to be used by the DHCP client as primary and secondary DNS servers.
	// The DHCP client will use these as the default DNS servers. Two DNS servers can be specified to be used by the DHCP client as primary and secondary DNS servers.
	// +kubebuilder:validation:Optional
	DNSServer []*string `json:"dnsServer,omitempty" tf:"dns_server,omitempty"`

	// (String) The DHCP client will use this as the 'DNS domain' setting for the network adapter.
	// The DHCP client will use this as the 'DNS domain' setting for the network adapter.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) The default gateway to be used by DHCP Client.
	// The default gateway to be used by DHCP Client.
	// +kubebuilder:validation:Optional
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// netmask from network address will be used.
	// The actual network mask is to be used by the DHCP client. If set to '0' - netmask from network address will be used.
	// +kubebuilder:validation:Optional
	Netmask *int64 `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// (String) The IP address of the next server to use in bootstrap.
	// The IP address of the next server to use in bootstrap.
	// +kubebuilder:validation:Optional
	NextServer *string `json:"nextServer,omitempty" tf:"next_server,omitempty"`

	// (Boolean) If set, then DHCP Server will not pass NTP servers configured on the router to the DHCP clients.
	// If set, then DHCP Server will not pass NTP servers configured on the router to the DHCP clients.
	// +kubebuilder:validation:Optional
	NtpNone *bool `json:"ntpNone,omitempty" tf:"ntp_none,omitempty"`

	// (List of String) The DHCP client will use these as the default NTP servers. Two NTP servers can be specified to be used by the DHCP client as primary and secondary NTP servers
	// The DHCP client will use these as the default NTP servers. Two NTP servers can be specified to be used by the DHCP client as primary and secondary NTP servers
	// +kubebuilder:validation:Optional
	NtpServer []*string `json:"ntpServer,omitempty" tf:"ntp_server,omitempty"`

	// (List of String) The Windows DHCP client will use these as the default WINS servers. Two WINS servers can be specified to be used by the DHCP client as primary and secondary WINS servers
	// The Windows DHCP client will use these as the default WINS servers. Two WINS servers can be specified to be used by the DHCP client as primary and secondary WINS servers
	// +kubebuilder:validation:Optional
	WinsServer []*string `json:"winsServer,omitempty" tf:"wins_server,omitempty"`
}

// DHCPServerNetworkSpec defines the desired state of DHCPServerNetwork
type DHCPServerNetworkSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DHCPServerNetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DHCPServerNetworkInitParameters `json:"initProvider,omitempty"`
}

// DHCPServerNetworkStatus defines the observed state of DHCPServerNetwork.
type DHCPServerNetworkStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DHCPServerNetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DHCPServerNetwork is the Schema for the DHCPServerNetworks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type DHCPServerNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.address) || (has(self.initProvider) && has(self.initProvider.address))",message="spec.forProvider.address is a required parameter"
	Spec   DHCPServerNetworkSpec   `json:"spec"`
	Status DHCPServerNetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DHCPServerNetworkList contains a list of DHCPServerNetworks
type DHCPServerNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DHCPServerNetwork `json:"items"`
}

// Repository type metadata.
var (
	DHCPServerNetwork_Kind             = "DHCPServerNetwork"
	DHCPServerNetwork_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DHCPServerNetwork_Kind}.String()
	DHCPServerNetwork_KindAPIVersion   = DHCPServerNetwork_Kind + "." + CRDGroupVersion.String()
	DHCPServerNetwork_GroupVersionKind = CRDGroupVersion.WithKind(DHCPServerNetwork_Kind)
)

func init() {
	SchemeBuilder.Register(&DHCPServerNetwork{}, &DHCPServerNetworkList{})
}
