// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DHCPRelayInitParameters struct {

	// option contains mac address of an interface, Agent Remote ID Sub-option contains MAC address of the client from which request was received.
	// Adds DHCP relay agent information if enabled according to RFC 3046. Agent Circuit ID Sub-option contains mac address of an interface, Agent Remote ID Sub-option contains MAC address of the client from which request was received.
	AddRelayInfo *bool `json:"addRelayInfo,omitempty" tf:"add_relay_info,omitempty"`

	// (String) List of DHCP servers' IP addresses which should the DHCP requests be forwarded to.
	// List of DHCP servers' IP addresses which should the DHCP requests be forwarded to.
	DHCPServer *string `json:"dhcpServer,omitempty" tf:"dhcp_server,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	DHCPServerVrf *string `json:"dhcpServerVrf,omitempty" tf:"dhcp_server_vrf,omitempty"`

	// threshold, then this packet is ignored.
	// If secs field in DHCP packet is smaller than delay-threshold, then this packet is ignored.
	DelayThreshold *string `json:"delayThreshold,omitempty" tf:"delay_threshold,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Interface name the DHCP relay will be working on.
	// Interface name the DHCP relay will be working on.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// the IP address will be chosen automatically
	// The unique IP address of this DHCP relay needed for DHCP server to distinguish relays. If set to 0.0.0.0 - the IP address will be chosen automatically
	LocalAddress *string `json:"localAddress,omitempty" tf:"local_address,omitempty"`

	// (String) Descriptive name for the relay.
	// Descriptive name for the relay.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// info-remote-id
	// Specified string will be used to construct Option 82 instead of client's MAC address. Option 82 consist of: interface from which packets was received + client mac address or relay-info-remote-id
	RelayInfoRemoteID *string `json:"relayInfoRemoteId,omitempty" tf:"relay_info_remote_id,omitempty"`
}

type DHCPRelayObservation struct {

	// option contains mac address of an interface, Agent Remote ID Sub-option contains MAC address of the client from which request was received.
	// Adds DHCP relay agent information if enabled according to RFC 3046. Agent Circuit ID Sub-option contains mac address of an interface, Agent Remote ID Sub-option contains MAC address of the client from which request was received.
	AddRelayInfo *bool `json:"addRelayInfo,omitempty" tf:"add_relay_info,omitempty"`

	// (String) List of DHCP servers' IP addresses which should the DHCP requests be forwarded to.
	// List of DHCP servers' IP addresses which should the DHCP requests be forwarded to.
	DHCPServer *string `json:"dhcpServer,omitempty" tf:"dhcp_server,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	DHCPServerVrf *string `json:"dhcpServerVrf,omitempty" tf:"dhcp_server_vrf,omitempty"`

	// threshold, then this packet is ignored.
	// If secs field in DHCP packet is smaller than delay-threshold, then this packet is ignored.
	DelayThreshold *string `json:"delayThreshold,omitempty" tf:"delay_threshold,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Interface name the DHCP relay will be working on.
	// Interface name the DHCP relay will be working on.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (Boolean)
	Invalid *bool `json:"invalid,omitempty" tf:"invalid,omitempty"`

	// the IP address will be chosen automatically
	// The unique IP address of this DHCP relay needed for DHCP server to distinguish relays. If set to 0.0.0.0 - the IP address will be chosen automatically
	LocalAddress *string `json:"localAddress,omitempty" tf:"local_address,omitempty"`

	// (String) Descriptive name for the relay.
	// Descriptive name for the relay.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// info-remote-id
	// Specified string will be used to construct Option 82 instead of client's MAC address. Option 82 consist of: interface from which packets was received + client mac address or relay-info-remote-id
	RelayInfoRemoteID *string `json:"relayInfoRemoteId,omitempty" tf:"relay_info_remote_id,omitempty"`
}

type DHCPRelayParameters struct {

	// option contains mac address of an interface, Agent Remote ID Sub-option contains MAC address of the client from which request was received.
	// Adds DHCP relay agent information if enabled according to RFC 3046. Agent Circuit ID Sub-option contains mac address of an interface, Agent Remote ID Sub-option contains MAC address of the client from which request was received.
	// +kubebuilder:validation:Optional
	AddRelayInfo *bool `json:"addRelayInfo,omitempty" tf:"add_relay_info,omitempty"`

	// (String) List of DHCP servers' IP addresses which should the DHCP requests be forwarded to.
	// List of DHCP servers' IP addresses which should the DHCP requests be forwarded to.
	// +kubebuilder:validation:Optional
	DHCPServer *string `json:"dhcpServer,omitempty" tf:"dhcp_server,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	// +kubebuilder:validation:Optional
	DHCPServerVrf *string `json:"dhcpServerVrf,omitempty" tf:"dhcp_server_vrf,omitempty"`

	// threshold, then this packet is ignored.
	// If secs field in DHCP packet is smaller than delay-threshold, then this packet is ignored.
	// +kubebuilder:validation:Optional
	DelayThreshold *string `json:"delayThreshold,omitempty" tf:"delay_threshold,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Interface name the DHCP relay will be working on.
	// Interface name the DHCP relay will be working on.
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// the IP address will be chosen automatically
	// The unique IP address of this DHCP relay needed for DHCP server to distinguish relays. If set to 0.0.0.0 - the IP address will be chosen automatically
	// +kubebuilder:validation:Optional
	LocalAddress *string `json:"localAddress,omitempty" tf:"local_address,omitempty"`

	// (String) Descriptive name for the relay.
	// Descriptive name for the relay.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// info-remote-id
	// Specified string will be used to construct Option 82 instead of client's MAC address. Option 82 consist of: interface from which packets was received + client mac address or relay-info-remote-id
	// +kubebuilder:validation:Optional
	RelayInfoRemoteID *string `json:"relayInfoRemoteId,omitempty" tf:"relay_info_remote_id,omitempty"`
}

// DHCPRelaySpec defines the desired state of DHCPRelay
type DHCPRelaySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DHCPRelayParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DHCPRelayInitParameters `json:"initProvider,omitempty"`
}

// DHCPRelayStatus defines the observed state of DHCPRelay.
type DHCPRelayStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DHCPRelayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DHCPRelay is the Schema for the DHCPRelays API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type DHCPRelay struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dhcpServer) || (has(self.initProvider) && has(self.initProvider.dhcpServer))",message="spec.forProvider.dhcpServer is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interface) || (has(self.initProvider) && has(self.initProvider.interface))",message="spec.forProvider.interface is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DHCPRelaySpec   `json:"spec"`
	Status DHCPRelayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DHCPRelayList contains a list of DHCPRelays
type DHCPRelayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DHCPRelay `json:"items"`
}

// Repository type metadata.
var (
	DHCPRelay_Kind             = "DHCPRelay"
	DHCPRelay_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DHCPRelay_Kind}.String()
	DHCPRelay_KindAPIVersion   = DHCPRelay_Kind + "." + CRDGroupVersion.String()
	DHCPRelay_GroupVersionKind = CRDGroupVersion.WithKind(DHCPRelay_Kind)
)

func init() {
	SchemeBuilder.Register(&DHCPRelay{}, &DHCPRelayList{})
}
