// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type HotspotInitParameters struct {

	// (String) Address space used to change HotSpot client any IP address to a valid address. Useful for providing public network access to mobile clients that are not willing to change their networking settings.
	// Address space used to change HotSpot client any IP address to a valid address. Useful for providing public network access to mobile clients that are not willing to change their networking settings.
	AddressPool *string `json:"addressPool,omitempty" tf:"address_pool,omitempty"`

	// address.
	// Number of IP addresses allowed to be bind with the MAC address, when multiple HotSpot clients connected with one MAC-address.
	AddressesPerMac *string `json:"addressesPerMac,omitempty" tf:"addresses_per_mac,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Period of inactivity for unauthorized clients. When there is no traffic from this client (literally client computer should be switched off), once the timeout is reached, a user is dropped from the HotSpot host list, its used address becomes available.
	// Period of inactivity for unauthorized clients. When there is no traffic from this client (literally client computer should be switched off), once the timeout is reached, a user is dropped from the HotSpot host list, its used address becomes available.
	IdleTimeout *string `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// (String) Interface to run HotSpot on.
	// Interface to run HotSpot on.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// timeout, that is applied to the user. Value shows how long the host can stay out of reach to be removed from the HotSpot.
	// The exact value of the keepalive-timeout, that is applied to the user. Value shows how long the host can stay out of reach to be removed from the HotSpot.
	KeepaliveTimeout *string `json:"keepaliveTimeout,omitempty" tf:"keepalive_timeout,omitempty"`

	// (String) Period of time after which if a host hasn't been authorized itself with a system the host entry gets deleted from host table. Loop repeats until the host logs in the system. Enable if there are situations where a host cannot log in after being too long in the host table unauthorized.
	// Period of time after which if a host hasn't been authorized itself with a system the host entry gets deleted from host table. Loop repeats until the host logs in the system. Enable if there are situations where a host cannot log in after being too long in the host table unauthorized.
	LoginTimeout *string `json:"loginTimeout,omitempty" tf:"login_timeout,omitempty"`

	// (String) HotSpot server's name or identifier.
	// HotSpot server's name or identifier.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) HotSpot server default HotSpot profile, which is located in `/ip/hotspot/profile`.
	// HotSpot server default HotSpot profile, which is located in `/ip/hotspot/profile`.
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`
}

type HotspotObservation struct {

	// (String) Address space used to change HotSpot client any IP address to a valid address. Useful for providing public network access to mobile clients that are not willing to change their networking settings.
	// Address space used to change HotSpot client any IP address to a valid address. Useful for providing public network access to mobile clients that are not willing to change their networking settings.
	AddressPool *string `json:"addressPool,omitempty" tf:"address_pool,omitempty"`

	// address.
	// Number of IP addresses allowed to be bind with the MAC address, when multiple HotSpot clients connected with one MAC-address.
	AddressesPerMac *string `json:"addressesPerMac,omitempty" tf:"addresses_per_mac,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Period of inactivity for unauthorized clients. When there is no traffic from this client (literally client computer should be switched off), once the timeout is reached, a user is dropped from the HotSpot host list, its used address becomes available.
	// Period of inactivity for unauthorized clients. When there is no traffic from this client (literally client computer should be switched off), once the timeout is reached, a user is dropped from the HotSpot host list, its used address becomes available.
	IdleTimeout *string `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// (String) Interface to run HotSpot on.
	// Interface to run HotSpot on.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (Boolean)
	Invalid *bool `json:"invalid,omitempty" tf:"invalid,omitempty"`

	// timeout, that is applied to the user. Value shows how long the host can stay out of reach to be removed from the HotSpot.
	// The exact value of the keepalive-timeout, that is applied to the user. Value shows how long the host can stay out of reach to be removed from the HotSpot.
	KeepaliveTimeout *string `json:"keepaliveTimeout,omitempty" tf:"keepalive_timeout,omitempty"`

	// (String) Period of time after which if a host hasn't been authorized itself with a system the host entry gets deleted from host table. Loop repeats until the host logs in the system. Enable if there are situations where a host cannot log in after being too long in the host table unauthorized.
	// Period of time after which if a host hasn't been authorized itself with a system the host entry gets deleted from host table. Loop repeats until the host logs in the system. Enable if there are situations where a host cannot log in after being too long in the host table unauthorized.
	LoginTimeout *string `json:"loginTimeout,omitempty" tf:"login_timeout,omitempty"`

	// (String) HotSpot server's name or identifier.
	// HotSpot server's name or identifier.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) HotSpot server default HotSpot profile, which is located in `/ip/hotspot/profile`.
	// HotSpot server default HotSpot profile, which is located in `/ip/hotspot/profile`.
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`
}

type HotspotParameters struct {

	// (String) Address space used to change HotSpot client any IP address to a valid address. Useful for providing public network access to mobile clients that are not willing to change their networking settings.
	// Address space used to change HotSpot client any IP address to a valid address. Useful for providing public network access to mobile clients that are not willing to change their networking settings.
	// +kubebuilder:validation:Optional
	AddressPool *string `json:"addressPool,omitempty" tf:"address_pool,omitempty"`

	// address.
	// Number of IP addresses allowed to be bind with the MAC address, when multiple HotSpot clients connected with one MAC-address.
	// +kubebuilder:validation:Optional
	AddressesPerMac *string `json:"addressesPerMac,omitempty" tf:"addresses_per_mac,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Period of inactivity for unauthorized clients. When there is no traffic from this client (literally client computer should be switched off), once the timeout is reached, a user is dropped from the HotSpot host list, its used address becomes available.
	// Period of inactivity for unauthorized clients. When there is no traffic from this client (literally client computer should be switched off), once the timeout is reached, a user is dropped from the HotSpot host list, its used address becomes available.
	// +kubebuilder:validation:Optional
	IdleTimeout *string `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// (String) Interface to run HotSpot on.
	// Interface to run HotSpot on.
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// timeout, that is applied to the user. Value shows how long the host can stay out of reach to be removed from the HotSpot.
	// The exact value of the keepalive-timeout, that is applied to the user. Value shows how long the host can stay out of reach to be removed from the HotSpot.
	// +kubebuilder:validation:Optional
	KeepaliveTimeout *string `json:"keepaliveTimeout,omitempty" tf:"keepalive_timeout,omitempty"`

	// (String) Period of time after which if a host hasn't been authorized itself with a system the host entry gets deleted from host table. Loop repeats until the host logs in the system. Enable if there are situations where a host cannot log in after being too long in the host table unauthorized.
	// Period of time after which if a host hasn't been authorized itself with a system the host entry gets deleted from host table. Loop repeats until the host logs in the system. Enable if there are situations where a host cannot log in after being too long in the host table unauthorized.
	// +kubebuilder:validation:Optional
	LoginTimeout *string `json:"loginTimeout,omitempty" tf:"login_timeout,omitempty"`

	// (String) HotSpot server's name or identifier.
	// HotSpot server's name or identifier.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) HotSpot server default HotSpot profile, which is located in `/ip/hotspot/profile`.
	// HotSpot server default HotSpot profile, which is located in `/ip/hotspot/profile`.
	// +kubebuilder:validation:Optional
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`
}

// HotspotSpec defines the desired state of Hotspot
type HotspotSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   HotspotParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HotspotInitParameters `json:"initProvider,omitempty"`
}

// HotspotStatus defines the observed state of Hotspot.
type HotspotStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               HotspotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Hotspot is the Schema for the Hotspots API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type Hotspot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interface) || (has(self.initProvider) && has(self.initProvider.interface))",message="spec.forProvider.interface is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   HotspotSpec   `json:"spec"`
	Status HotspotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HotspotList contains a list of Hotspots
type HotspotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Hotspot `json:"items"`
}

// Repository type metadata.
var (
	Hotspot_Kind             = "Hotspot"
	Hotspot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Hotspot_Kind}.String()
	Hotspot_KindAPIVersion   = Hotspot_Kind + "." + CRDGroupVersion.String()
	Hotspot_GroupVersionKind = CRDGroupVersion.WithKind(Hotspot_Kind)
)

func init() {
	SchemeBuilder.Register(&Hotspot{}, &HotspotList{})
}
