// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IpsecKeyInitParameters struct {

	// (Number) Size of this key.
	// Size of this key.
	KeySize *int64 `json:"keySize,omitempty" tf:"key_size,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IpsecKeyObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Size of this key.
	// Size of this key.
	KeySize *int64 `json:"keySize,omitempty" tf:"key_size,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IpsecKeyParameters struct {

	// (Number) Size of this key.
	// Size of this key.
	// +kubebuilder:validation:Optional
	KeySize *int64 `json:"keySize,omitempty" tf:"key_size,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// IpsecKeySpec defines the desired state of IpsecKey
type IpsecKeySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   IpsecKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IpsecKeyInitParameters `json:"initProvider,omitempty"`
}

// IpsecKeyStatus defines the observed state of IpsecKey.
type IpsecKeyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IpsecKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IpsecKey is the Schema for the IpsecKeys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type IpsecKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keySize) || (has(self.initProvider) && has(self.initProvider.keySize))",message="spec.forProvider.keySize is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   IpsecKeySpec   `json:"spec"`
	Status IpsecKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IpsecKeyList contains a list of IpsecKeys
type IpsecKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IpsecKey `json:"items"`
}

// Repository type metadata.
var (
	IpsecKey_Kind             = "IpsecKey"
	IpsecKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IpsecKey_Kind}.String()
	IpsecKey_KindAPIVersion   = IpsecKey_Kind + "." + CRDGroupVersion.String()
	IpsecKey_GroupVersionKind = CRDGroupVersion.WithKind(IpsecKey_Kind)
)

func init() {
	SchemeBuilder.Register(&IpsecKey{}, &IpsecKeyList{})
}
