// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SMBInitParameters struct {

	// (String) Set comment for the server.
	// Set comment for the server.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Name of Windows Workgroup.
	// Name of Windows Workgroup.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// disabled SMB share is configured under '/ip smb share'.
	// The default value is 'auto'. This means that the SMB server will automatically be enabled when the first non-disabled SMB share is configured under '/ip smb share'.
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of String) List of interfaces on which SMB service will be running.
	// List of interfaces on which SMB service will be running.
	// +listType=set
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`
}

type SMBObservation struct {

	// (String) Set comment for the server.
	// Set comment for the server.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Name of Windows Workgroup.
	// Name of Windows Workgroup.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// disabled SMB share is configured under '/ip smb share'.
	// The default value is 'auto'. This means that the SMB server will automatically be enabled when the first non-disabled SMB share is configured under '/ip smb share'.
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) List of interfaces on which SMB service will be running.
	// List of interfaces on which SMB service will be running.
	// +listType=set
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type SMBParameters struct {

	// (String) Set comment for the server.
	// Set comment for the server.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Name of Windows Workgroup.
	// Name of Windows Workgroup.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// disabled SMB share is configured under '/ip smb share'.
	// The default value is 'auto'. This means that the SMB server will automatically be enabled when the first non-disabled SMB share is configured under '/ip smb share'.
	// +kubebuilder:validation:Optional
	Enabled *string `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of String) List of interfaces on which SMB service will be running.
	// List of interfaces on which SMB service will be running.
	// +kubebuilder:validation:Optional
	// +listType=set
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`
}

// SMBSpec defines the desired state of SMB
type SMBSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SMBParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SMBInitParameters `json:"initProvider,omitempty"`
}

// SMBStatus defines the observed state of SMB.
type SMBStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SMBObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SMB is the Schema for the SMBs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type SMB struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SMBSpec   `json:"spec"`
	Status            SMBStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SMBList contains a list of SMBs
type SMBList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SMB `json:"items"`
}

// Repository type metadata.
var (
	SMB_Kind             = "SMB"
	SMB_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SMB_Kind}.String()
	SMB_KindAPIVersion   = SMB_Kind + "." + CRDGroupVersion.String()
	SMB_GroupVersionKind = CRDGroupVersion.WithKind(SMB_Kind)
)

func init() {
	SchemeBuilder.Register(&SMB{}, &SMBList{})
}
