// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TftpInitParameters struct {

	// (Boolean) Allow connection.
	// Allow connection.
	Allow *bool `json:"allow,omitempty" tf:"allow,omitempty"`

	// (Boolean) If `true`, overwriting the file is allowed.
	// If `true`, overwriting the file is allowed.
	AllowOverwrite *bool `json:"allowOverwrite,omitempty" tf:"allow_overwrite,omitempty"`

	// (Boolean) If set, server will allow sequence number to roll over when maximum value is reached. This is used to enable large downloads using TFTP server.
	// If set, server will allow sequence number to roll over when maximum value is reached. This is used to enable large downloads using TFTP server.
	AllowRollover *bool `json:"allowRollover,omitempty" tf:"allow_rollover,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Set of String) Range of IP addresses accepted as clients. If empty `0.0.0.0/0` will be used.
	// Range of IP addresses accepted as clients. If empty `0.0.0.0/0` will be used.
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// (Boolean) Sets if file can be written to. If set to `false` write attempts will fail with an error.
	// Sets if file can be written to. If set to `false` write attempts will fail with an error.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (String) TFTP Windowsize option value.
	// TFTP Windowsize option value.
	ReadingWindowSize *string `json:"readingWindowSize,omitempty" tf:"reading_window_size,omitempty"`

	// filename` and `real-filename` values are set and valid, the requested filename will be replaced with matched file. This field has to be set. If multiple regex are specified in `req-filename`, with this field you can set which ones should match, so this rule is validated. `real-filename` format for using multiple regex is `filename\0\5\6`.
	// If `req-filename` and `real-filename` values are set and valid, the requested filename will be replaced with matched file. This field has to be set. If multiple regex are specified in `req-filename`, with this field you can set which ones should match, so this rule is validated. `real-filename` format for using multiple regex is `filename\0\5\6`.
	RealFilename *string `json:"realFilename,omitempty" tf:"real_filename,omitempty"`

	// (String) Requested filename as regular expression (regex) if field is left empty it defaults to `.*`.
	// Requested filename as regular expression (regex) if field is left empty it defaults to `.*`.
	ReqFilename *string `json:"reqFilename,omitempty" tf:"req_filename,omitempty"`
}

type TftpObservation struct {

	// (Boolean) Allow connection.
	// Allow connection.
	Allow *bool `json:"allow,omitempty" tf:"allow,omitempty"`

	// (Boolean) If `true`, overwriting the file is allowed.
	// If `true`, overwriting the file is allowed.
	AllowOverwrite *bool `json:"allowOverwrite,omitempty" tf:"allow_overwrite,omitempty"`

	// (Boolean) If set, server will allow sequence number to roll over when maximum value is reached. This is used to enable large downloads using TFTP server.
	// If set, server will allow sequence number to roll over when maximum value is reached. This is used to enable large downloads using TFTP server.
	AllowRollover *bool `json:"allowRollover,omitempty" tf:"allow_rollover,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) Range of IP addresses accepted as clients. If empty `0.0.0.0/0` will be used.
	// Range of IP addresses accepted as clients. If empty `0.0.0.0/0` will be used.
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// (Boolean) Sets if file can be written to. If set to `false` write attempts will fail with an error.
	// Sets if file can be written to. If set to `false` write attempts will fail with an error.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (String) TFTP Windowsize option value.
	// TFTP Windowsize option value.
	ReadingWindowSize *string `json:"readingWindowSize,omitempty" tf:"reading_window_size,omitempty"`

	// filename` and `real-filename` values are set and valid, the requested filename will be replaced with matched file. This field has to be set. If multiple regex are specified in `req-filename`, with this field you can set which ones should match, so this rule is validated. `real-filename` format for using multiple regex is `filename\0\5\6`.
	// If `req-filename` and `real-filename` values are set and valid, the requested filename will be replaced with matched file. This field has to be set. If multiple regex are specified in `req-filename`, with this field you can set which ones should match, so this rule is validated. `real-filename` format for using multiple regex is `filename\0\5\6`.
	RealFilename *string `json:"realFilename,omitempty" tf:"real_filename,omitempty"`

	// (String) Requested filename as regular expression (regex) if field is left empty it defaults to `.*`.
	// Requested filename as regular expression (regex) if field is left empty it defaults to `.*`.
	ReqFilename *string `json:"reqFilename,omitempty" tf:"req_filename,omitempty"`
}

type TftpParameters struct {

	// (Boolean) Allow connection.
	// Allow connection.
	// +kubebuilder:validation:Optional
	Allow *bool `json:"allow,omitempty" tf:"allow,omitempty"`

	// (Boolean) If `true`, overwriting the file is allowed.
	// If `true`, overwriting the file is allowed.
	// +kubebuilder:validation:Optional
	AllowOverwrite *bool `json:"allowOverwrite,omitempty" tf:"allow_overwrite,omitempty"`

	// (Boolean) If set, server will allow sequence number to roll over when maximum value is reached. This is used to enable large downloads using TFTP server.
	// If set, server will allow sequence number to roll over when maximum value is reached. This is used to enable large downloads using TFTP server.
	// +kubebuilder:validation:Optional
	AllowRollover *bool `json:"allowRollover,omitempty" tf:"allow_rollover,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Set of String) Range of IP addresses accepted as clients. If empty `0.0.0.0/0` will be used.
	// Range of IP addresses accepted as clients. If empty `0.0.0.0/0` will be used.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// (Boolean) Sets if file can be written to. If set to `false` write attempts will fail with an error.
	// Sets if file can be written to. If set to `false` write attempts will fail with an error.
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (String) TFTP Windowsize option value.
	// TFTP Windowsize option value.
	// +kubebuilder:validation:Optional
	ReadingWindowSize *string `json:"readingWindowSize,omitempty" tf:"reading_window_size,omitempty"`

	// filename` and `real-filename` values are set and valid, the requested filename will be replaced with matched file. This field has to be set. If multiple regex are specified in `req-filename`, with this field you can set which ones should match, so this rule is validated. `real-filename` format for using multiple regex is `filename\0\5\6`.
	// If `req-filename` and `real-filename` values are set and valid, the requested filename will be replaced with matched file. This field has to be set. If multiple regex are specified in `req-filename`, with this field you can set which ones should match, so this rule is validated. `real-filename` format for using multiple regex is `filename\0\5\6`.
	// +kubebuilder:validation:Optional
	RealFilename *string `json:"realFilename,omitempty" tf:"real_filename,omitempty"`

	// (String) Requested filename as regular expression (regex) if field is left empty it defaults to `.*`.
	// Requested filename as regular expression (regex) if field is left empty it defaults to `.*`.
	// +kubebuilder:validation:Optional
	ReqFilename *string `json:"reqFilename,omitempty" tf:"req_filename,omitempty"`
}

// TftpSpec defines the desired state of Tftp
type TftpSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TftpParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TftpInitParameters `json:"initProvider,omitempty"`
}

// TftpStatus defines the observed state of Tftp.
type TftpStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TftpObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Tftp is the Schema for the Tftps API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type Tftp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TftpSpec   `json:"spec"`
	Status            TftpStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TftpList contains a list of Tftps
type TftpList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Tftp `json:"items"`
}

// Repository type metadata.
var (
	Tftp_Kind             = "Tftp"
	Tftp_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Tftp_Kind}.String()
	Tftp_KindAPIVersion   = Tftp_Kind + "." + CRDGroupVersion.String()
	Tftp_GroupVersionKind = CRDGroupVersion.WithKind(Tftp_Kind)
)

func init() {
	SchemeBuilder.Register(&Tftp{}, &TftpList{})
}
