// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BGPEvpnInitParameters struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// -export))
	// A group of parameters associated with the route export.
	Export []ExportInitParameters `json:"export,omitempty" tf:"export,omitempty"`

	// -import))
	// A group of parameters associated with the route import.
	Import []ImportInitParameters `json:"import,omitempty" tf:"import,omitempty"`

	// (String) BGP instance this EVPN is assigned to.
	// BGP instance this EVPN is assigned to.
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Name of the entry.
	// Name of the entry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies the value that gets attached to route so that receiving routers can distinguish advertisements that may otherwise look the same. Used to distinguish between tenants using overlapping IP ranges. Also can be used to simplify convergence and redundancy within Virtual Network. RDs form MLAG pairs should be unique, too.
	// Specifies the value that gets attached to route so that receiving routers can distinguish advertisements that may otherwise look the same. Used to distinguish between tenants using overlapping IP ranges. Also can be used to simplify convergence and redundancy within Virtual Network. RDs form MLAG pairs should be unique, too.
	Rd *string `json:"rd,omitempty" tf:"rd,omitempty"`

	// (Number) Range of Virtual Network Identifiers.
	// Range of Virtual Network Identifiers.
	Vni *int64 `json:"vni,omitempty" tf:"vni,omitempty"`

	// (String) VRF name.
	// VRF name.
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type BGPEvpnObservation struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// -export))
	// A group of parameters associated with the route export.
	Export []ExportObservation `json:"export,omitempty" tf:"export,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// -import))
	// A group of parameters associated with the route import.
	Import []ImportObservation `json:"import,omitempty" tf:"import,omitempty"`

	// (String) BGP instance this EVPN is assigned to.
	// BGP instance this EVPN is assigned to.
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Name of the entry.
	// Name of the entry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies the value that gets attached to route so that receiving routers can distinguish advertisements that may otherwise look the same. Used to distinguish between tenants using overlapping IP ranges. Also can be used to simplify convergence and redundancy within Virtual Network. RDs form MLAG pairs should be unique, too.
	// Specifies the value that gets attached to route so that receiving routers can distinguish advertisements that may otherwise look the same. Used to distinguish between tenants using overlapping IP ranges. Also can be used to simplify convergence and redundancy within Virtual Network. RDs form MLAG pairs should be unique, too.
	Rd *string `json:"rd,omitempty" tf:"rd,omitempty"`

	// (Number) Range of Virtual Network Identifiers.
	// Range of Virtual Network Identifiers.
	Vni *int64 `json:"vni,omitempty" tf:"vni,omitempty"`

	// (String) VRF name.
	// VRF name.
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type BGPEvpnParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// -export))
	// A group of parameters associated with the route export.
	// +kubebuilder:validation:Optional
	Export []ExportParameters `json:"export,omitempty" tf:"export,omitempty"`

	// -import))
	// A group of parameters associated with the route import.
	// +kubebuilder:validation:Optional
	Import []ImportParameters `json:"import,omitempty" tf:"import,omitempty"`

	// (String) BGP instance this EVPN is assigned to.
	// BGP instance this EVPN is assigned to.
	// +kubebuilder:validation:Optional
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Name of the entry.
	// Name of the entry.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies the value that gets attached to route so that receiving routers can distinguish advertisements that may otherwise look the same. Used to distinguish between tenants using overlapping IP ranges. Also can be used to simplify convergence and redundancy within Virtual Network. RDs form MLAG pairs should be unique, too.
	// Specifies the value that gets attached to route so that receiving routers can distinguish advertisements that may otherwise look the same. Used to distinguish between tenants using overlapping IP ranges. Also can be used to simplify convergence and redundancy within Virtual Network. RDs form MLAG pairs should be unique, too.
	// +kubebuilder:validation:Optional
	Rd *string `json:"rd,omitempty" tf:"rd,omitempty"`

	// (Number) Range of Virtual Network Identifiers.
	// Range of Virtual Network Identifiers.
	// +kubebuilder:validation:Optional
	Vni *int64 `json:"vni,omitempty" tf:"vni,omitempty"`

	// (String) VRF name.
	// VRF name.
	// +kubebuilder:validation:Optional
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type ExportInitParameters struct {

	// (Set of String) List of route targets that will be used to import EVPN routes.
	// List of route targets that will be added to EVPN routes when exporting.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type ExportObservation struct {

	// (Set of String) List of route targets that will be used to import EVPN routes.
	// List of route targets that will be added to EVPN routes when exporting.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type ExportParameters struct {

	// (Set of String) List of route targets that will be used to import EVPN routes.
	// List of route targets that will be added to EVPN routes when exporting.
	// +kubebuilder:validation:Optional
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type ImportInitParameters struct {

	// (Set of String) List of route targets that will be used to import EVPN routes.
	// List of route targets that will be used to import EVPN routes.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type ImportObservation struct {

	// (Set of String) List of route targets that will be used to import EVPN routes.
	// List of route targets that will be used to import EVPN routes.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type ImportParameters struct {

	// (Set of String) List of route targets that will be used to import EVPN routes.
	// List of route targets that will be used to import EVPN routes.
	// +kubebuilder:validation:Optional
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

// BGPEvpnSpec defines the desired state of BGPEvpn
type BGPEvpnSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   BGPEvpnParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BGPEvpnInitParameters `json:"initProvider,omitempty"`
}

// BGPEvpnStatus defines the observed state of BGPEvpn.
type BGPEvpnStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BGPEvpnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BGPEvpn is the Schema for the BGPEvpns API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type BGPEvpn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instance) || (has(self.initProvider) && has(self.initProvider.instance))",message="spec.forProvider.instance is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   BGPEvpnSpec   `json:"spec"`
	Status BGPEvpnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BGPEvpnList contains a list of BGPEvpns
type BGPEvpnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BGPEvpn `json:"items"`
}

// Repository type metadata.
var (
	BGPEvpn_Kind             = "BGPEvpn"
	BGPEvpn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BGPEvpn_Kind}.String()
	BGPEvpn_KindAPIVersion   = BGPEvpn_Kind + "." + CRDGroupVersion.String()
	BGPEvpn_GroupVersionKind = CRDGroupVersion.WithKind(BGPEvpn_Kind)
)

func init() {
	SchemeBuilder.Register(&BGPEvpn{}, &BGPEvpnList{})
}
