// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CapsmanInitParameters struct {

	// (String) Device CA certificate.
	// Device CA certificate.
	CACertificate *string `json:"caCertificate,omitempty" tf:"ca_certificate,omitempty"`

	// (String) Device certificate.
	// Device certificate.
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (Boolean) Disable or enable CAPsMAN functionality.
	// Disable or enable CAPsMAN functionality.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) List of interfaces on which CAPsMAN will listen for CAP connections.
	// List of interfaces on which CAPsMAN will listen for CAP connections.
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// in RouterOS packages, note that in this case only CAPs with the same architecture as CAPsMAN will be upgraded.
	// Folder location for the RouterOS packages. For example, use '/upgrade' to specify the upgrade folder from the files section. If empty string is set, CAPsMAN can use built-in RouterOS packages, note that in this case only CAPs with the same architecture as CAPsMAN will be upgraded.
	PackagePath *string `json:"packagePath,omitempty" tf:"package_path,omitempty"`

	// (Boolean) Require all connecting CAPs to have a valid certificate.
	// Require all connecting CAPs to have a valid certificate.
	RequirePeerCertificate *bool `json:"requirePeerCertificate,omitempty" tf:"require_peer_certificate,omitempty"`

	// (String) Upgrade policy options.
	// Upgrade policy options.
	UpgradePolicy *string `json:"upgradePolicy,omitempty" tf:"upgrade_policy,omitempty"`
}

type CapsmanObservation struct {

	// (String) Device CA certificate.
	// Device CA certificate.
	CACertificate *string `json:"caCertificate,omitempty" tf:"ca_certificate,omitempty"`

	// (String) Device certificate.
	// Device certificate.
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (Boolean) Disable or enable CAPsMAN functionality.
	// Disable or enable CAPsMAN functionality.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Generated CA certificate.
	// Generated CA certificate.
	GeneratedCACertificate *string `json:"generatedCaCertificate,omitempty" tf:"generated_ca_certificate,omitempty"`

	// (String) Generated CAPsMAN certificate.
	// Generated CAPsMAN certificate.
	GeneratedCertificate *string `json:"generatedCertificate,omitempty" tf:"generated_certificate,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) List of interfaces on which CAPsMAN will listen for CAP connections.
	// List of interfaces on which CAPsMAN will listen for CAP connections.
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// in RouterOS packages, note that in this case only CAPs with the same architecture as CAPsMAN will be upgraded.
	// Folder location for the RouterOS packages. For example, use '/upgrade' to specify the upgrade folder from the files section. If empty string is set, CAPsMAN can use built-in RouterOS packages, note that in this case only CAPs with the same architecture as CAPsMAN will be upgraded.
	PackagePath *string `json:"packagePath,omitempty" tf:"package_path,omitempty"`

	// (Boolean) Require all connecting CAPs to have a valid certificate.
	// Require all connecting CAPs to have a valid certificate.
	RequirePeerCertificate *bool `json:"requirePeerCertificate,omitempty" tf:"require_peer_certificate,omitempty"`

	// (String) Upgrade policy options.
	// Upgrade policy options.
	UpgradePolicy *string `json:"upgradePolicy,omitempty" tf:"upgrade_policy,omitempty"`
}

type CapsmanParameters struct {

	// (String) Device CA certificate.
	// Device CA certificate.
	// +kubebuilder:validation:Optional
	CACertificate *string `json:"caCertificate,omitempty" tf:"ca_certificate,omitempty"`

	// (String) Device certificate.
	// Device certificate.
	// +kubebuilder:validation:Optional
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (Boolean) Disable or enable CAPsMAN functionality.
	// Disable or enable CAPsMAN functionality.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) List of interfaces on which CAPsMAN will listen for CAP connections.
	// List of interfaces on which CAPsMAN will listen for CAP connections.
	// +kubebuilder:validation:Optional
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// in RouterOS packages, note that in this case only CAPs with the same architecture as CAPsMAN will be upgraded.
	// Folder location for the RouterOS packages. For example, use '/upgrade' to specify the upgrade folder from the files section. If empty string is set, CAPsMAN can use built-in RouterOS packages, note that in this case only CAPs with the same architecture as CAPsMAN will be upgraded.
	// +kubebuilder:validation:Optional
	PackagePath *string `json:"packagePath,omitempty" tf:"package_path,omitempty"`

	// (Boolean) Require all connecting CAPs to have a valid certificate.
	// Require all connecting CAPs to have a valid certificate.
	// +kubebuilder:validation:Optional
	RequirePeerCertificate *bool `json:"requirePeerCertificate,omitempty" tf:"require_peer_certificate,omitempty"`

	// (String) Upgrade policy options.
	// Upgrade policy options.
	// +kubebuilder:validation:Optional
	UpgradePolicy *string `json:"upgradePolicy,omitempty" tf:"upgrade_policy,omitempty"`
}

// CapsmanSpec defines the desired state of Capsman
type CapsmanSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CapsmanParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CapsmanInitParameters `json:"initProvider,omitempty"`
}

// CapsmanStatus defines the observed state of Capsman.
type CapsmanStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CapsmanObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Capsman is the Schema for the Capsmans API. *<span style="color:red">This resource requires a minimum version of RouterOS 7.13.</span>*
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type Capsman struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CapsmanSpec   `json:"spec"`
	Status            CapsmanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CapsmanList contains a list of Capsmans
type CapsmanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Capsman `json:"items"`
}

// Repository type metadata.
var (
	Capsman_Kind             = "Capsman"
	Capsman_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Capsman_Kind}.String()
	Capsman_KindAPIVersion   = Capsman_Kind + "." + CRDGroupVersion.String()
	Capsman_GroupVersionKind = CRDGroupVersion.WithKind(Capsman_Kind)
)

func init() {
	SchemeBuilder.Register(&Capsman{}, &CapsmanList{})
}
