apiVersion: v1
kind: Secret
metadata:
  name: routeros-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  username: admin
  password: replace-me
---
apiVersion: routeros.m.sindrip.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  endpoint: https://192.0.2.1
  credentials:
    secretRef:
      name: routeros-credentials
  tls:
    insecureSkipVerify: true
  requestTimeout: 30s
