// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type QueueTypeInitParameters struct {

	// (Number) Maximum number of bytes that the BFIFO queue can hold. Applies if `kind` is `bfifo`.
	// Maximum number of bytes that the BFIFO queue can hold. Applies if `kind` is `bfifo`.
	BfifoLimit *int64 `json:"bfifoLimit,omitempty" tf:"bfifo_limit,omitempty"`

	// (String)
	CakeAckFilter *string `json:"cakeAckFilter,omitempty" tf:"cake_ack_filter,omitempty"`

	// (String) Compensates for ATM cell framing, which is normally found on ADSL links.
	// Compensates for ATM cell framing, which is normally found on ADSL links.
	CakeAtm *string `json:"cakeAtm,omitempty" tf:"cake_atm,omitempty"`

	// (Boolean) Automatic capacity estimation based on traffic arriving at this qdisc. This is most likely to be useful with cellular links, which tend to change quality randomly.  The Bandwidth Limit parameter can be used in conjunction to specify an initial estimate. The shaper will periodically be set to a bandwidth slightly below the estimated rate.  This estimator cannot estimate the bandwidth of links downstream of itself.
	// Automatic capacity estimation based on traffic arriving at this qdisc. This is most likely to be useful with cellular links, which tend to change quality randomly.  The Bandwidth Limit parameter can be used in conjunction to specify an initial estimate. The shaper will periodically be set to a bandwidth slightly below the estimated rate.  This estimator cannot estimate the bandwidth of links downstream of itself.
	CakeAutorateIngress *bool `json:"cakeAutorateIngress,omitempty" tf:"cake_autorate_ingress,omitempty"`

	// (Number) Sets the shaper bandwidth.
	// Sets the shaper bandwidth.
	CakeBandwidth *int64 `json:"cakeBandwidth,omitempty" tf:"cake_bandwidth,omitempty"`

	// (String) CAKE can divide traffic into `tins` based on the Diffserv field:
	// CAKE can divide traffic into `tins` based on the Diffserv field:
	// * `diffserv4` Provides a general-purpose Diffserv implementation with four tins: Bulk (CS1), 6.25% threshold, generally low priority. Best Effort (general), 100% threshold. Video (AF4x, AF3x, CS3, AF2x, CS2, TOS4, TOS1), 50% threshold. Voice (CS7, CS6, EF, VA, CS5, CS4), 25% threshold.
	// * `diffserv3` (default) Provides a simple, general-purpose Diffserv implementation with three tins: Bulk (CS1), 6.25% threshold, generally low priority. Best Effort (general), 100% threshold. Voice (CS7, CS6, EF, VA, TOS4), 25% threshold, reduced Codel interval.
	CakeDiffserv *string `json:"cakeDiffserv,omitempty" tf:"cake_diffserv,omitempty"`

	// Disables flow isolation; all traffic passes through a single queue for each tin.
	//
	// * `flowblind` - Disables flow isolation; all traffic passes through a single queue for each tin.
	// * `srchost` - Flows are defined only by source address.
	// * `dsthost` Flows are defined only by destination address.
	// * `hosts` - Flows are defined by source-destination host pairs. This is host isolation, rather than flow isolation.
	// * `flows` - Flows are defined by the entire 5-tuple of source address, a destination address, transport protocol, source port, and destination port. This is the type of flow isolation performed by SFQ and fq_codel.
	// * `dual-srchost` Flows are defined by the 5-tuple, and fairness is applied first over source addresses, then over individual flows. Good for use on egress traffic from a LAN to the internet, where it'll prevent any LAN host from monopolizing the uplink, regardless of the number of flows they use.
	// * `dual-dsthost` Flows are defined by the 5-tuple, and fairness is applied first over destination addresses, then over individual flows. Good for use on ingress traffic to a LAN from the internet, where it'll prevent any LAN host from monopolizing the downlink, regardless of the number of flows they use.
	// * `triple-isolate` - Flows are defined by the 5-tuple, and fairness is applied over source *and* destination addresses intelligently (ie. not merely by host-pairs), and also over individual flows.
	// * `nat` Instructs Cake to perform a NAT lookup before applying flow- isolation rules, to determine the true addresses and port numbers of the packet, to improve fairness between hosts `inside` the NAT. This has no practical effect in `flowblind` or `flows` modes, or if NAT is performed on a different host.
	// * `nonat` (default) The cake will not perform a NAT lookup. Flow isolation will be performed using the addresses and port numbers directly visible to the interface Cake is attached to.
	CakeFlowmode *string `json:"cakeFlowmode,omitempty" tf:"cake_flowmode,omitempty"`

	// (Number) Limit the memory consumed by Cake to LIMIT bytes. By default, the limit is calculated based on the bandwidth and RTT settings.
	// Limit the memory consumed by Cake to LIMIT bytes. By default, the limit is calculated based on the bandwidth and RTT settings.
	CakeMemlimit *int64 `json:"cakeMemlimit,omitempty" tf:"cake_memlimit,omitempty"`

	// (Number) Rounds each packet (including overhead) up to a minimum length BYTES.
	// Rounds each packet (including overhead) up to a minimum length BYTES.
	CakeMpu *int64 `json:"cakeMpu,omitempty" tf:"cake_mpu,omitempty"`

	// isolation rule.
	// Instructs Cake to perform a NAT lookup before applying a flow-isolation rule.
	CakeNAT *bool `json:"cakeNat,omitempty" tf:"cake_nat,omitempty"`

	// (Number) Adds BYTES to the size of each packet. BYTES may be negative.
	// Adds BYTES to the size of each packet. BYTES may be negative.
	CakeOverhead *int64 `json:"cakeOverhead,omitempty" tf:"cake_overhead,omitempty"`

	// (String)
	CakeOverheadScheme *string `json:"cakeOverheadScheme,omitempty" tf:"cake_overhead_scheme,omitempty"`

	// (String) Manually specify an RTT. Default 100ms is suitable for most Internet traffic.
	// Manually specify an RTT. Default 100ms is suitable for most Internet traffic.
	CakeRtt *string `json:"cakeRtt,omitempty" tf:"cake_rtt,omitempty"`

	// For extremely high-performance 10GigE+ networks only. Equivalent to `RTT 100us`.
	//
	// * `datacentre` - For extremely high-performance 10GigE+ networks only. Equivalent to `RTT 100us`.
	// * `lan` - For pure Ethernet (not Wi-Fi) networks, at home or in the office. Don't use this when shaping for an Internet access link. Equivalent to `RTT 1ms`.
	// * `metro` - For traffic mostly within a single city. Equivalent to `RTT 10ms`. regional For traffic mostly within a European-sized country. Equivalent to `RTT 30ms`.
	// * `internet` (default) This is suitable for most Internet traffic. Equivalent to `RTT 100ms`.
	// * `oceanic` - For Internet traffic with generally above-average latency, such as that suffered by Australasian residents. Equivalent to `RTT 300ms`.
	// * `satellite` - For traffic via geostationary satellites. Equivalent to `RTT 1000ms`.
	// * `interplanetary` - So named because Jupiter is about 1 light-hour from Earth. Use this to (almost) completely disable AQM actions. Equivalent to `RTT 3600s`.
	CakeRttScheme *string `json:"cakeRttScheme,omitempty" tf:"cake_rtt_scheme,omitempty"`

	// (Boolean) Apply the wash option to clear all extra DiffServ (but not ECN bits), after priority queuing has taken place.
	// Apply the wash option to clear all extra DiffServ (but not ECN bits), after priority queuing has taken place.
	CakeWash *bool `json:"cakeWash,omitempty" tf:"cake_wash,omitempty"`

	// (Number) Marks packets above a configured threshold with ECN.
	// Marks packets above a configured threshold with ECN.
	CodelCeThreshold *int64 `json:"codelCeThreshold,omitempty" tf:"codel_ce_threshold,omitempty"`

	// (Boolean) An option is used to mark packets instead of dropping them.
	// An option is used to mark packets instead of dropping them.
	CodelEcn *bool `json:"codelEcn,omitempty" tf:"codel_ecn,omitempty"`

	// case RTT through the bottleneck giving endpoints sufficient time to react.
	// Interval should be set on the order of the worst-case RTT through the bottleneck giving endpoints sufficient time to react.
	CodelInterval *string `json:"codelInterval,omitempty" tf:"codel_interval,omitempty"`

	// (Number) Queue limit, when the limit is reached, incoming packets are dropped.
	// Queue limit, when the limit is reached, incoming packets are dropped.
	CodelLimit *int64 `json:"codelLimit,omitempty" tf:"codel_limit,omitempty"`

	// (String) Represents an acceptable minimum persistent queue delay.
	// Represents an acceptable minimum persistent queue delay.
	CodelTarget *string `json:"codelTarget,omitempty" tf:"codel_target,omitempty"`

	// (Number) Marks packets above a configured threshold with ECN.
	// Marks packets above a configured threshold with ECN.
	FqCodelCeThreshold *int64 `json:"fqCodelCeThreshold,omitempty" tf:"fq_codel_ce_threshold,omitempty"`

	// (Boolean) An option is used to mark packets instead of dropping them.
	// An option is used to mark packets instead of dropping them.
	FqCodelEcn *bool `json:"fqCodelEcn,omitempty" tf:"fq_codel_ecn,omitempty"`

	// (Number) A number of flows into which the incoming packets are classified.
	// A number of flows into which the incoming packets are classified.
	FqCodelFlows *int64 `json:"fqCodelFlows,omitempty" tf:"fq_codel_flows,omitempty"`

	// case RTT through the bottleneck giving endpoints sufficient time to react.
	// Interval should be set on the order of the worst-case RTT through the bottleneck giving endpoints sufficient time to react.
	FqCodelInterval *string `json:"fqCodelInterval,omitempty" tf:"fq_codel_interval,omitempty"`

	// (Number) Queue limit, when the limit is reached, incoming packets are dropped.
	// Queue limit, when the limit is reached, incoming packets are dropped.
	FqCodelLimit *int64 `json:"fqCodelLimit,omitempty" tf:"fq_codel_limit,omitempty"`

	// CoDel instance. Will be enforced from the fq-codel-limit parameter.
	// A total number of bytes that can be queued in this FQ-CoDel instance. Will be enforced from the fq-codel-limit parameter.
	FqCodelMemlimit *int64 `json:"fqCodelMemlimit,omitempty" tf:"fq_codel_memlimit,omitempty"`

	// (Number) A number of bytes used as 'deficit' in the fair queuing algorithm. Default (1514 bytes) corresponds to the Ethernet MTU plus the hardware header length of 14 bytes.
	// A number of bytes used as 'deficit' in the fair queuing algorithm. Default (1514 bytes) corresponds to the Ethernet MTU plus the hardware header length of 14 bytes.
	FqCodelQuantum *int64 `json:"fqCodelQuantum,omitempty" tf:"fq_codel_quantum,omitempty"`

	// (String) Represents an acceptable minimum persistent queue delay.
	// Represents an acceptable minimum persistent queue delay.
	FqCodelTarget *string `json:"fqCodelTarget,omitempty" tf:"fq_codel_target,omitempty"`

	// (String) Queue kind.
	// Queue kind.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// queue PFIFO limit.
	// Multi-queue PFIFO limit.
	MqPfifoLimit *int64 `json:"mqPfifoLimit,omitempty" tf:"mq_pfifo_limit,omitempty"`

	// (String) Type name.
	// Type name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Maximal upload/download data rate which can be reached while the burst for substream is allowed.
	// Maximal upload/download data rate which can be reached while the burst for substream is allowed.
	PcqBurstRate *int64 `json:"pcqBurstRate,omitempty" tf:"pcq_burst_rate,omitempty"`

	// (Number) This is value of burst on/off switch.
	// This is value of burst on/off switch.
	PcqBurstThreshold *int64 `json:"pcqBurstThreshold,omitempty" tf:"pcq_burst_threshold,omitempty"`

	// (String) Period of time, in seconds, over which the average data rate is calculated. (This is NOT the time of actual burst).
	// Period of time, in seconds, over which the average data rate is calculated. (This is NOT the time of actual burst).
	PcqBurstTime *string `json:"pcqBurstTime,omitempty" tf:"pcq_burst_time,omitempty"`

	// stream identifiers.
	// Selection of sub-stream identifiers.
	// +listType=set
	PcqClassifier []*string `json:"pcqClassifier,omitempty" tf:"pcq_classifier,omitempty"`

	// address sub-stream identifier.
	// Size of IPV6 network that will be used as dst-address sub-stream identifier.
	PcqDstAddress6Mask *int64 `json:"pcqDstAddress6Mask,omitempty" tf:"pcq_dst_address6_mask,omitempty"`

	// address sub-stream identifier.
	// Size of IPv4 network that will be used as dst-address sub-stream identifier.
	PcqDstAddressMask *int64 `json:"pcqDstAddressMask,omitempty" tf:"pcq_dst_address_mask,omitempty"`

	// stream (in kilobytes).
	// Queue size of a single sub-stream (in kilobytes).
	PcqLimit *int64 `json:"pcqLimit,omitempty" tf:"pcq_limit,omitempty"`

	// steam.
	// Maximal available data rate of each sub-steam.
	PcqRate *int64 `json:"pcqRate,omitempty" tf:"pcq_rate,omitempty"`

	// address sub-stream identifier.
	// Size of IPV6 network that will be used as src-address sub-stream identifier.
	PcqSrcAddress6Mask *int64 `json:"pcqSrcAddress6Mask,omitempty" tf:"pcq_src_address6_mask,omitempty"`

	// address sub-stream identifier.
	// Size of IPv4 network that will be used as src-address sub-stream identifier.
	PcqSrcAddressMask *int64 `json:"pcqSrcAddressMask,omitempty" tf:"pcq_src_address_mask,omitempty"`

	// streams per PCQ instance. Note that each queue tree entry has its own PCQ instance.
	// Max amount of bytes queued (in kilobytes) for all sub-streams per PCQ instance. Note that each queue tree entry has its own PCQ instance.
	PcqTotalLimit *int64 `json:"pcqTotalLimit,omitempty" tf:"pcq_total_limit,omitempty"`

	// (Number) Maximum number of packets that the PFIFO queue can hold. Applies if `kind` is `pfifo`.
	// Maximum number of packets that the PFIFO queue can hold. Applies if `kind` is `pfifo`.
	PfifoLimit *int64 `json:"pfifoLimit,omitempty" tf:"pfifo_limit,omitempty"`

	// (Number) Used by RED for average queue size calculations (for packet to byte translation).
	// Used by RED for average queue size calculations (for packet to byte translation).
	RedAvgPacket *int64 `json:"redAvgPacket,omitempty" tf:"red_avg_packet,omitempty"`

	// (Number) Number of packets allowed for bursts of packets when there are no packets in the queue.
	// Number of packets allowed for bursts of packets when there are no packets in the queue.
	RedBurst *int64 `json:"redBurst,omitempty" tf:"red_burst,omitempty"`

	// (Number) RED queue limit in packets.
	// RED queue limit in packets.
	RedLimit *int64 `json:"redLimit,omitempty" tf:"red_limit,omitempty"`

	// (Number) The average queue size at which packet marking probability is the highest.
	// The average queue size at which packet marking probability is the highest.
	RedMaxThreshold *int64 `json:"redMaxThreshold,omitempty" tf:"red_max_threshold,omitempty"`

	// (Number) Average queue size in bytes.
	// Average queue size in bytes.
	RedMinThreshold *int64 `json:"redMinThreshold,omitempty" tf:"red_min_threshold,omitempty"`

	// robin round.
	// Amount of data in bytes that can be sent in one round-robin round.
	SfqAllot *int64 `json:"sfqAllot,omitempty" tf:"sfq_allot,omitempty"`

	// (Number) How often hash function must be refreshed.
	// How often hash function must be refreshed.
	SfqPerturb *int64 `json:"sfqPerturb,omitempty" tf:"sfq_perturb,omitempty"`
}

type QueueTypeObservation struct {

	// (Number) Maximum number of bytes that the BFIFO queue can hold. Applies if `kind` is `bfifo`.
	// Maximum number of bytes that the BFIFO queue can hold. Applies if `kind` is `bfifo`.
	BfifoLimit *int64 `json:"bfifoLimit,omitempty" tf:"bfifo_limit,omitempty"`

	// (String)
	CakeAckFilter *string `json:"cakeAckFilter,omitempty" tf:"cake_ack_filter,omitempty"`

	// (String) Compensates for ATM cell framing, which is normally found on ADSL links.
	// Compensates for ATM cell framing, which is normally found on ADSL links.
	CakeAtm *string `json:"cakeAtm,omitempty" tf:"cake_atm,omitempty"`

	// (Boolean) Automatic capacity estimation based on traffic arriving at this qdisc. This is most likely to be useful with cellular links, which tend to change quality randomly.  The Bandwidth Limit parameter can be used in conjunction to specify an initial estimate. The shaper will periodically be set to a bandwidth slightly below the estimated rate.  This estimator cannot estimate the bandwidth of links downstream of itself.
	// Automatic capacity estimation based on traffic arriving at this qdisc. This is most likely to be useful with cellular links, which tend to change quality randomly.  The Bandwidth Limit parameter can be used in conjunction to specify an initial estimate. The shaper will periodically be set to a bandwidth slightly below the estimated rate.  This estimator cannot estimate the bandwidth of links downstream of itself.
	CakeAutorateIngress *bool `json:"cakeAutorateIngress,omitempty" tf:"cake_autorate_ingress,omitempty"`

	// (Number) Sets the shaper bandwidth.
	// Sets the shaper bandwidth.
	CakeBandwidth *int64 `json:"cakeBandwidth,omitempty" tf:"cake_bandwidth,omitempty"`

	// (String) CAKE can divide traffic into `tins` based on the Diffserv field:
	// CAKE can divide traffic into `tins` based on the Diffserv field:
	// * `diffserv4` Provides a general-purpose Diffserv implementation with four tins: Bulk (CS1), 6.25% threshold, generally low priority. Best Effort (general), 100% threshold. Video (AF4x, AF3x, CS3, AF2x, CS2, TOS4, TOS1), 50% threshold. Voice (CS7, CS6, EF, VA, CS5, CS4), 25% threshold.
	// * `diffserv3` (default) Provides a simple, general-purpose Diffserv implementation with three tins: Bulk (CS1), 6.25% threshold, generally low priority. Best Effort (general), 100% threshold. Voice (CS7, CS6, EF, VA, TOS4), 25% threshold, reduced Codel interval.
	CakeDiffserv *string `json:"cakeDiffserv,omitempty" tf:"cake_diffserv,omitempty"`

	// Disables flow isolation; all traffic passes through a single queue for each tin.
	//
	// * `flowblind` - Disables flow isolation; all traffic passes through a single queue for each tin.
	// * `srchost` - Flows are defined only by source address.
	// * `dsthost` Flows are defined only by destination address.
	// * `hosts` - Flows are defined by source-destination host pairs. This is host isolation, rather than flow isolation.
	// * `flows` - Flows are defined by the entire 5-tuple of source address, a destination address, transport protocol, source port, and destination port. This is the type of flow isolation performed by SFQ and fq_codel.
	// * `dual-srchost` Flows are defined by the 5-tuple, and fairness is applied first over source addresses, then over individual flows. Good for use on egress traffic from a LAN to the internet, where it'll prevent any LAN host from monopolizing the uplink, regardless of the number of flows they use.
	// * `dual-dsthost` Flows are defined by the 5-tuple, and fairness is applied first over destination addresses, then over individual flows. Good for use on ingress traffic to a LAN from the internet, where it'll prevent any LAN host from monopolizing the downlink, regardless of the number of flows they use.
	// * `triple-isolate` - Flows are defined by the 5-tuple, and fairness is applied over source *and* destination addresses intelligently (ie. not merely by host-pairs), and also over individual flows.
	// * `nat` Instructs Cake to perform a NAT lookup before applying flow- isolation rules, to determine the true addresses and port numbers of the packet, to improve fairness between hosts `inside` the NAT. This has no practical effect in `flowblind` or `flows` modes, or if NAT is performed on a different host.
	// * `nonat` (default) The cake will not perform a NAT lookup. Flow isolation will be performed using the addresses and port numbers directly visible to the interface Cake is attached to.
	CakeFlowmode *string `json:"cakeFlowmode,omitempty" tf:"cake_flowmode,omitempty"`

	// (Number) Limit the memory consumed by Cake to LIMIT bytes. By default, the limit is calculated based on the bandwidth and RTT settings.
	// Limit the memory consumed by Cake to LIMIT bytes. By default, the limit is calculated based on the bandwidth and RTT settings.
	CakeMemlimit *int64 `json:"cakeMemlimit,omitempty" tf:"cake_memlimit,omitempty"`

	// (Number) Rounds each packet (including overhead) up to a minimum length BYTES.
	// Rounds each packet (including overhead) up to a minimum length BYTES.
	CakeMpu *int64 `json:"cakeMpu,omitempty" tf:"cake_mpu,omitempty"`

	// isolation rule.
	// Instructs Cake to perform a NAT lookup before applying a flow-isolation rule.
	CakeNAT *bool `json:"cakeNat,omitempty" tf:"cake_nat,omitempty"`

	// (Number) Adds BYTES to the size of each packet. BYTES may be negative.
	// Adds BYTES to the size of each packet. BYTES may be negative.
	CakeOverhead *int64 `json:"cakeOverhead,omitempty" tf:"cake_overhead,omitempty"`

	// (String)
	CakeOverheadScheme *string `json:"cakeOverheadScheme,omitempty" tf:"cake_overhead_scheme,omitempty"`

	// (String) Manually specify an RTT. Default 100ms is suitable for most Internet traffic.
	// Manually specify an RTT. Default 100ms is suitable for most Internet traffic.
	CakeRtt *string `json:"cakeRtt,omitempty" tf:"cake_rtt,omitempty"`

	// For extremely high-performance 10GigE+ networks only. Equivalent to `RTT 100us`.
	//
	// * `datacentre` - For extremely high-performance 10GigE+ networks only. Equivalent to `RTT 100us`.
	// * `lan` - For pure Ethernet (not Wi-Fi) networks, at home or in the office. Don't use this when shaping for an Internet access link. Equivalent to `RTT 1ms`.
	// * `metro` - For traffic mostly within a single city. Equivalent to `RTT 10ms`. regional For traffic mostly within a European-sized country. Equivalent to `RTT 30ms`.
	// * `internet` (default) This is suitable for most Internet traffic. Equivalent to `RTT 100ms`.
	// * `oceanic` - For Internet traffic with generally above-average latency, such as that suffered by Australasian residents. Equivalent to `RTT 300ms`.
	// * `satellite` - For traffic via geostationary satellites. Equivalent to `RTT 1000ms`.
	// * `interplanetary` - So named because Jupiter is about 1 light-hour from Earth. Use this to (almost) completely disable AQM actions. Equivalent to `RTT 3600s`.
	CakeRttScheme *string `json:"cakeRttScheme,omitempty" tf:"cake_rtt_scheme,omitempty"`

	// (Boolean) Apply the wash option to clear all extra DiffServ (but not ECN bits), after priority queuing has taken place.
	// Apply the wash option to clear all extra DiffServ (but not ECN bits), after priority queuing has taken place.
	CakeWash *bool `json:"cakeWash,omitempty" tf:"cake_wash,omitempty"`

	// (Number) Marks packets above a configured threshold with ECN.
	// Marks packets above a configured threshold with ECN.
	CodelCeThreshold *int64 `json:"codelCeThreshold,omitempty" tf:"codel_ce_threshold,omitempty"`

	// (Boolean) An option is used to mark packets instead of dropping them.
	// An option is used to mark packets instead of dropping them.
	CodelEcn *bool `json:"codelEcn,omitempty" tf:"codel_ecn,omitempty"`

	// case RTT through the bottleneck giving endpoints sufficient time to react.
	// Interval should be set on the order of the worst-case RTT through the bottleneck giving endpoints sufficient time to react.
	CodelInterval *string `json:"codelInterval,omitempty" tf:"codel_interval,omitempty"`

	// (Number) Queue limit, when the limit is reached, incoming packets are dropped.
	// Queue limit, when the limit is reached, incoming packets are dropped.
	CodelLimit *int64 `json:"codelLimit,omitempty" tf:"codel_limit,omitempty"`

	// (String) Represents an acceptable minimum persistent queue delay.
	// Represents an acceptable minimum persistent queue delay.
	CodelTarget *string `json:"codelTarget,omitempty" tf:"codel_target,omitempty"`

	// (Boolean) It's the default item.
	// It's the default item.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (Number) Marks packets above a configured threshold with ECN.
	// Marks packets above a configured threshold with ECN.
	FqCodelCeThreshold *int64 `json:"fqCodelCeThreshold,omitempty" tf:"fq_codel_ce_threshold,omitempty"`

	// (Boolean) An option is used to mark packets instead of dropping them.
	// An option is used to mark packets instead of dropping them.
	FqCodelEcn *bool `json:"fqCodelEcn,omitempty" tf:"fq_codel_ecn,omitempty"`

	// (Number) A number of flows into which the incoming packets are classified.
	// A number of flows into which the incoming packets are classified.
	FqCodelFlows *int64 `json:"fqCodelFlows,omitempty" tf:"fq_codel_flows,omitempty"`

	// case RTT through the bottleneck giving endpoints sufficient time to react.
	// Interval should be set on the order of the worst-case RTT through the bottleneck giving endpoints sufficient time to react.
	FqCodelInterval *string `json:"fqCodelInterval,omitempty" tf:"fq_codel_interval,omitempty"`

	// (Number) Queue limit, when the limit is reached, incoming packets are dropped.
	// Queue limit, when the limit is reached, incoming packets are dropped.
	FqCodelLimit *int64 `json:"fqCodelLimit,omitempty" tf:"fq_codel_limit,omitempty"`

	// CoDel instance. Will be enforced from the fq-codel-limit parameter.
	// A total number of bytes that can be queued in this FQ-CoDel instance. Will be enforced from the fq-codel-limit parameter.
	FqCodelMemlimit *int64 `json:"fqCodelMemlimit,omitempty" tf:"fq_codel_memlimit,omitempty"`

	// (Number) A number of bytes used as 'deficit' in the fair queuing algorithm. Default (1514 bytes) corresponds to the Ethernet MTU plus the hardware header length of 14 bytes.
	// A number of bytes used as 'deficit' in the fair queuing algorithm. Default (1514 bytes) corresponds to the Ethernet MTU plus the hardware header length of 14 bytes.
	FqCodelQuantum *int64 `json:"fqCodelQuantum,omitempty" tf:"fq_codel_quantum,omitempty"`

	// (String) Represents an acceptable minimum persistent queue delay.
	// Represents an acceptable minimum persistent queue delay.
	FqCodelTarget *string `json:"fqCodelTarget,omitempty" tf:"fq_codel_target,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Queue kind.
	// Queue kind.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// queue PFIFO limit.
	// Multi-queue PFIFO limit.
	MqPfifoLimit *int64 `json:"mqPfifoLimit,omitempty" tf:"mq_pfifo_limit,omitempty"`

	// (String) Type name.
	// Type name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Maximal upload/download data rate which can be reached while the burst for substream is allowed.
	// Maximal upload/download data rate which can be reached while the burst for substream is allowed.
	PcqBurstRate *int64 `json:"pcqBurstRate,omitempty" tf:"pcq_burst_rate,omitempty"`

	// (Number) This is value of burst on/off switch.
	// This is value of burst on/off switch.
	PcqBurstThreshold *int64 `json:"pcqBurstThreshold,omitempty" tf:"pcq_burst_threshold,omitempty"`

	// (String) Period of time, in seconds, over which the average data rate is calculated. (This is NOT the time of actual burst).
	// Period of time, in seconds, over which the average data rate is calculated. (This is NOT the time of actual burst).
	PcqBurstTime *string `json:"pcqBurstTime,omitempty" tf:"pcq_burst_time,omitempty"`

	// stream identifiers.
	// Selection of sub-stream identifiers.
	// +listType=set
	PcqClassifier []*string `json:"pcqClassifier,omitempty" tf:"pcq_classifier,omitempty"`

	// address sub-stream identifier.
	// Size of IPV6 network that will be used as dst-address sub-stream identifier.
	PcqDstAddress6Mask *int64 `json:"pcqDstAddress6Mask,omitempty" tf:"pcq_dst_address6_mask,omitempty"`

	// address sub-stream identifier.
	// Size of IPv4 network that will be used as dst-address sub-stream identifier.
	PcqDstAddressMask *int64 `json:"pcqDstAddressMask,omitempty" tf:"pcq_dst_address_mask,omitempty"`

	// stream (in kilobytes).
	// Queue size of a single sub-stream (in kilobytes).
	PcqLimit *int64 `json:"pcqLimit,omitempty" tf:"pcq_limit,omitempty"`

	// steam.
	// Maximal available data rate of each sub-steam.
	PcqRate *int64 `json:"pcqRate,omitempty" tf:"pcq_rate,omitempty"`

	// address sub-stream identifier.
	// Size of IPV6 network that will be used as src-address sub-stream identifier.
	PcqSrcAddress6Mask *int64 `json:"pcqSrcAddress6Mask,omitempty" tf:"pcq_src_address6_mask,omitempty"`

	// address sub-stream identifier.
	// Size of IPv4 network that will be used as src-address sub-stream identifier.
	PcqSrcAddressMask *int64 `json:"pcqSrcAddressMask,omitempty" tf:"pcq_src_address_mask,omitempty"`

	// streams per PCQ instance. Note that each queue tree entry has its own PCQ instance.
	// Max amount of bytes queued (in kilobytes) for all sub-streams per PCQ instance. Note that each queue tree entry has its own PCQ instance.
	PcqTotalLimit *int64 `json:"pcqTotalLimit,omitempty" tf:"pcq_total_limit,omitempty"`

	// (Number) Maximum number of packets that the PFIFO queue can hold. Applies if `kind` is `pfifo`.
	// Maximum number of packets that the PFIFO queue can hold. Applies if `kind` is `pfifo`.
	PfifoLimit *int64 `json:"pfifoLimit,omitempty" tf:"pfifo_limit,omitempty"`

	// (Number) Used by RED for average queue size calculations (for packet to byte translation).
	// Used by RED for average queue size calculations (for packet to byte translation).
	RedAvgPacket *int64 `json:"redAvgPacket,omitempty" tf:"red_avg_packet,omitempty"`

	// (Number) Number of packets allowed for bursts of packets when there are no packets in the queue.
	// Number of packets allowed for bursts of packets when there are no packets in the queue.
	RedBurst *int64 `json:"redBurst,omitempty" tf:"red_burst,omitempty"`

	// (Number) RED queue limit in packets.
	// RED queue limit in packets.
	RedLimit *int64 `json:"redLimit,omitempty" tf:"red_limit,omitempty"`

	// (Number) The average queue size at which packet marking probability is the highest.
	// The average queue size at which packet marking probability is the highest.
	RedMaxThreshold *int64 `json:"redMaxThreshold,omitempty" tf:"red_max_threshold,omitempty"`

	// (Number) Average queue size in bytes.
	// Average queue size in bytes.
	RedMinThreshold *int64 `json:"redMinThreshold,omitempty" tf:"red_min_threshold,omitempty"`

	// robin round.
	// Amount of data in bytes that can be sent in one round-robin round.
	SfqAllot *int64 `json:"sfqAllot,omitempty" tf:"sfq_allot,omitempty"`

	// (Number) How often hash function must be refreshed.
	// How often hash function must be refreshed.
	SfqPerturb *int64 `json:"sfqPerturb,omitempty" tf:"sfq_perturb,omitempty"`
}

type QueueTypeParameters struct {

	// (Number) Maximum number of bytes that the BFIFO queue can hold. Applies if `kind` is `bfifo`.
	// Maximum number of bytes that the BFIFO queue can hold. Applies if `kind` is `bfifo`.
	// +kubebuilder:validation:Optional
	BfifoLimit *int64 `json:"bfifoLimit,omitempty" tf:"bfifo_limit,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	CakeAckFilter *string `json:"cakeAckFilter,omitempty" tf:"cake_ack_filter,omitempty"`

	// (String) Compensates for ATM cell framing, which is normally found on ADSL links.
	// Compensates for ATM cell framing, which is normally found on ADSL links.
	// +kubebuilder:validation:Optional
	CakeAtm *string `json:"cakeAtm,omitempty" tf:"cake_atm,omitempty"`

	// (Boolean) Automatic capacity estimation based on traffic arriving at this qdisc. This is most likely to be useful with cellular links, which tend to change quality randomly.  The Bandwidth Limit parameter can be used in conjunction to specify an initial estimate. The shaper will periodically be set to a bandwidth slightly below the estimated rate.  This estimator cannot estimate the bandwidth of links downstream of itself.
	// Automatic capacity estimation based on traffic arriving at this qdisc. This is most likely to be useful with cellular links, which tend to change quality randomly.  The Bandwidth Limit parameter can be used in conjunction to specify an initial estimate. The shaper will periodically be set to a bandwidth slightly below the estimated rate.  This estimator cannot estimate the bandwidth of links downstream of itself.
	// +kubebuilder:validation:Optional
	CakeAutorateIngress *bool `json:"cakeAutorateIngress,omitempty" tf:"cake_autorate_ingress,omitempty"`

	// (Number) Sets the shaper bandwidth.
	// Sets the shaper bandwidth.
	// +kubebuilder:validation:Optional
	CakeBandwidth *int64 `json:"cakeBandwidth,omitempty" tf:"cake_bandwidth,omitempty"`

	// (String) CAKE can divide traffic into `tins` based on the Diffserv field:
	// CAKE can divide traffic into `tins` based on the Diffserv field:
	// * `diffserv4` Provides a general-purpose Diffserv implementation with four tins: Bulk (CS1), 6.25% threshold, generally low priority. Best Effort (general), 100% threshold. Video (AF4x, AF3x, CS3, AF2x, CS2, TOS4, TOS1), 50% threshold. Voice (CS7, CS6, EF, VA, CS5, CS4), 25% threshold.
	// * `diffserv3` (default) Provides a simple, general-purpose Diffserv implementation with three tins: Bulk (CS1), 6.25% threshold, generally low priority. Best Effort (general), 100% threshold. Voice (CS7, CS6, EF, VA, TOS4), 25% threshold, reduced Codel interval.
	// +kubebuilder:validation:Optional
	CakeDiffserv *string `json:"cakeDiffserv,omitempty" tf:"cake_diffserv,omitempty"`

	// Disables flow isolation; all traffic passes through a single queue for each tin.
	//
	// * `flowblind` - Disables flow isolation; all traffic passes through a single queue for each tin.
	// * `srchost` - Flows are defined only by source address.
	// * `dsthost` Flows are defined only by destination address.
	// * `hosts` - Flows are defined by source-destination host pairs. This is host isolation, rather than flow isolation.
	// * `flows` - Flows are defined by the entire 5-tuple of source address, a destination address, transport protocol, source port, and destination port. This is the type of flow isolation performed by SFQ and fq_codel.
	// * `dual-srchost` Flows are defined by the 5-tuple, and fairness is applied first over source addresses, then over individual flows. Good for use on egress traffic from a LAN to the internet, where it'll prevent any LAN host from monopolizing the uplink, regardless of the number of flows they use.
	// * `dual-dsthost` Flows are defined by the 5-tuple, and fairness is applied first over destination addresses, then over individual flows. Good for use on ingress traffic to a LAN from the internet, where it'll prevent any LAN host from monopolizing the downlink, regardless of the number of flows they use.
	// * `triple-isolate` - Flows are defined by the 5-tuple, and fairness is applied over source *and* destination addresses intelligently (ie. not merely by host-pairs), and also over individual flows.
	// * `nat` Instructs Cake to perform a NAT lookup before applying flow- isolation rules, to determine the true addresses and port numbers of the packet, to improve fairness between hosts `inside` the NAT. This has no practical effect in `flowblind` or `flows` modes, or if NAT is performed on a different host.
	// * `nonat` (default) The cake will not perform a NAT lookup. Flow isolation will be performed using the addresses and port numbers directly visible to the interface Cake is attached to.
	// +kubebuilder:validation:Optional
	CakeFlowmode *string `json:"cakeFlowmode,omitempty" tf:"cake_flowmode,omitempty"`

	// (Number) Limit the memory consumed by Cake to LIMIT bytes. By default, the limit is calculated based on the bandwidth and RTT settings.
	// Limit the memory consumed by Cake to LIMIT bytes. By default, the limit is calculated based on the bandwidth and RTT settings.
	// +kubebuilder:validation:Optional
	CakeMemlimit *int64 `json:"cakeMemlimit,omitempty" tf:"cake_memlimit,omitempty"`

	// (Number) Rounds each packet (including overhead) up to a minimum length BYTES.
	// Rounds each packet (including overhead) up to a minimum length BYTES.
	// +kubebuilder:validation:Optional
	CakeMpu *int64 `json:"cakeMpu,omitempty" tf:"cake_mpu,omitempty"`

	// isolation rule.
	// Instructs Cake to perform a NAT lookup before applying a flow-isolation rule.
	// +kubebuilder:validation:Optional
	CakeNAT *bool `json:"cakeNat,omitempty" tf:"cake_nat,omitempty"`

	// (Number) Adds BYTES to the size of each packet. BYTES may be negative.
	// Adds BYTES to the size of each packet. BYTES may be negative.
	// +kubebuilder:validation:Optional
	CakeOverhead *int64 `json:"cakeOverhead,omitempty" tf:"cake_overhead,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	CakeOverheadScheme *string `json:"cakeOverheadScheme,omitempty" tf:"cake_overhead_scheme,omitempty"`

	// (String) Manually specify an RTT. Default 100ms is suitable for most Internet traffic.
	// Manually specify an RTT. Default 100ms is suitable for most Internet traffic.
	// +kubebuilder:validation:Optional
	CakeRtt *string `json:"cakeRtt,omitempty" tf:"cake_rtt,omitempty"`

	// For extremely high-performance 10GigE+ networks only. Equivalent to `RTT 100us`.
	//
	// * `datacentre` - For extremely high-performance 10GigE+ networks only. Equivalent to `RTT 100us`.
	// * `lan` - For pure Ethernet (not Wi-Fi) networks, at home or in the office. Don't use this when shaping for an Internet access link. Equivalent to `RTT 1ms`.
	// * `metro` - For traffic mostly within a single city. Equivalent to `RTT 10ms`. regional For traffic mostly within a European-sized country. Equivalent to `RTT 30ms`.
	// * `internet` (default) This is suitable for most Internet traffic. Equivalent to `RTT 100ms`.
	// * `oceanic` - For Internet traffic with generally above-average latency, such as that suffered by Australasian residents. Equivalent to `RTT 300ms`.
	// * `satellite` - For traffic via geostationary satellites. Equivalent to `RTT 1000ms`.
	// * `interplanetary` - So named because Jupiter is about 1 light-hour from Earth. Use this to (almost) completely disable AQM actions. Equivalent to `RTT 3600s`.
	// +kubebuilder:validation:Optional
	CakeRttScheme *string `json:"cakeRttScheme,omitempty" tf:"cake_rtt_scheme,omitempty"`

	// (Boolean) Apply the wash option to clear all extra DiffServ (but not ECN bits), after priority queuing has taken place.
	// Apply the wash option to clear all extra DiffServ (but not ECN bits), after priority queuing has taken place.
	// +kubebuilder:validation:Optional
	CakeWash *bool `json:"cakeWash,omitempty" tf:"cake_wash,omitempty"`

	// (Number) Marks packets above a configured threshold with ECN.
	// Marks packets above a configured threshold with ECN.
	// +kubebuilder:validation:Optional
	CodelCeThreshold *int64 `json:"codelCeThreshold,omitempty" tf:"codel_ce_threshold,omitempty"`

	// (Boolean) An option is used to mark packets instead of dropping them.
	// An option is used to mark packets instead of dropping them.
	// +kubebuilder:validation:Optional
	CodelEcn *bool `json:"codelEcn,omitempty" tf:"codel_ecn,omitempty"`

	// case RTT through the bottleneck giving endpoints sufficient time to react.
	// Interval should be set on the order of the worst-case RTT through the bottleneck giving endpoints sufficient time to react.
	// +kubebuilder:validation:Optional
	CodelInterval *string `json:"codelInterval,omitempty" tf:"codel_interval,omitempty"`

	// (Number) Queue limit, when the limit is reached, incoming packets are dropped.
	// Queue limit, when the limit is reached, incoming packets are dropped.
	// +kubebuilder:validation:Optional
	CodelLimit *int64 `json:"codelLimit,omitempty" tf:"codel_limit,omitempty"`

	// (String) Represents an acceptable minimum persistent queue delay.
	// Represents an acceptable minimum persistent queue delay.
	// +kubebuilder:validation:Optional
	CodelTarget *string `json:"codelTarget,omitempty" tf:"codel_target,omitempty"`

	// (Number) Marks packets above a configured threshold with ECN.
	// Marks packets above a configured threshold with ECN.
	// +kubebuilder:validation:Optional
	FqCodelCeThreshold *int64 `json:"fqCodelCeThreshold,omitempty" tf:"fq_codel_ce_threshold,omitempty"`

	// (Boolean) An option is used to mark packets instead of dropping them.
	// An option is used to mark packets instead of dropping them.
	// +kubebuilder:validation:Optional
	FqCodelEcn *bool `json:"fqCodelEcn,omitempty" tf:"fq_codel_ecn,omitempty"`

	// (Number) A number of flows into which the incoming packets are classified.
	// A number of flows into which the incoming packets are classified.
	// +kubebuilder:validation:Optional
	FqCodelFlows *int64 `json:"fqCodelFlows,omitempty" tf:"fq_codel_flows,omitempty"`

	// case RTT through the bottleneck giving endpoints sufficient time to react.
	// Interval should be set on the order of the worst-case RTT through the bottleneck giving endpoints sufficient time to react.
	// +kubebuilder:validation:Optional
	FqCodelInterval *string `json:"fqCodelInterval,omitempty" tf:"fq_codel_interval,omitempty"`

	// (Number) Queue limit, when the limit is reached, incoming packets are dropped.
	// Queue limit, when the limit is reached, incoming packets are dropped.
	// +kubebuilder:validation:Optional
	FqCodelLimit *int64 `json:"fqCodelLimit,omitempty" tf:"fq_codel_limit,omitempty"`

	// CoDel instance. Will be enforced from the fq-codel-limit parameter.
	// A total number of bytes that can be queued in this FQ-CoDel instance. Will be enforced from the fq-codel-limit parameter.
	// +kubebuilder:validation:Optional
	FqCodelMemlimit *int64 `json:"fqCodelMemlimit,omitempty" tf:"fq_codel_memlimit,omitempty"`

	// (Number) A number of bytes used as 'deficit' in the fair queuing algorithm. Default (1514 bytes) corresponds to the Ethernet MTU plus the hardware header length of 14 bytes.
	// A number of bytes used as 'deficit' in the fair queuing algorithm. Default (1514 bytes) corresponds to the Ethernet MTU plus the hardware header length of 14 bytes.
	// +kubebuilder:validation:Optional
	FqCodelQuantum *int64 `json:"fqCodelQuantum,omitempty" tf:"fq_codel_quantum,omitempty"`

	// (String) Represents an acceptable minimum persistent queue delay.
	// Represents an acceptable minimum persistent queue delay.
	// +kubebuilder:validation:Optional
	FqCodelTarget *string `json:"fqCodelTarget,omitempty" tf:"fq_codel_target,omitempty"`

	// (String) Queue kind.
	// Queue kind.
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// queue PFIFO limit.
	// Multi-queue PFIFO limit.
	// +kubebuilder:validation:Optional
	MqPfifoLimit *int64 `json:"mqPfifoLimit,omitempty" tf:"mq_pfifo_limit,omitempty"`

	// (String) Type name.
	// Type name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Maximal upload/download data rate which can be reached while the burst for substream is allowed.
	// Maximal upload/download data rate which can be reached while the burst for substream is allowed.
	// +kubebuilder:validation:Optional
	PcqBurstRate *int64 `json:"pcqBurstRate,omitempty" tf:"pcq_burst_rate,omitempty"`

	// (Number) This is value of burst on/off switch.
	// This is value of burst on/off switch.
	// +kubebuilder:validation:Optional
	PcqBurstThreshold *int64 `json:"pcqBurstThreshold,omitempty" tf:"pcq_burst_threshold,omitempty"`

	// (String) Period of time, in seconds, over which the average data rate is calculated. (This is NOT the time of actual burst).
	// Period of time, in seconds, over which the average data rate is calculated. (This is NOT the time of actual burst).
	// +kubebuilder:validation:Optional
	PcqBurstTime *string `json:"pcqBurstTime,omitempty" tf:"pcq_burst_time,omitempty"`

	// stream identifiers.
	// Selection of sub-stream identifiers.
	// +kubebuilder:validation:Optional
	// +listType=set
	PcqClassifier []*string `json:"pcqClassifier,omitempty" tf:"pcq_classifier,omitempty"`

	// address sub-stream identifier.
	// Size of IPV6 network that will be used as dst-address sub-stream identifier.
	// +kubebuilder:validation:Optional
	PcqDstAddress6Mask *int64 `json:"pcqDstAddress6Mask,omitempty" tf:"pcq_dst_address6_mask,omitempty"`

	// address sub-stream identifier.
	// Size of IPv4 network that will be used as dst-address sub-stream identifier.
	// +kubebuilder:validation:Optional
	PcqDstAddressMask *int64 `json:"pcqDstAddressMask,omitempty" tf:"pcq_dst_address_mask,omitempty"`

	// stream (in kilobytes).
	// Queue size of a single sub-stream (in kilobytes).
	// +kubebuilder:validation:Optional
	PcqLimit *int64 `json:"pcqLimit,omitempty" tf:"pcq_limit,omitempty"`

	// steam.
	// Maximal available data rate of each sub-steam.
	// +kubebuilder:validation:Optional
	PcqRate *int64 `json:"pcqRate,omitempty" tf:"pcq_rate,omitempty"`

	// address sub-stream identifier.
	// Size of IPV6 network that will be used as src-address sub-stream identifier.
	// +kubebuilder:validation:Optional
	PcqSrcAddress6Mask *int64 `json:"pcqSrcAddress6Mask,omitempty" tf:"pcq_src_address6_mask,omitempty"`

	// address sub-stream identifier.
	// Size of IPv4 network that will be used as src-address sub-stream identifier.
	// +kubebuilder:validation:Optional
	PcqSrcAddressMask *int64 `json:"pcqSrcAddressMask,omitempty" tf:"pcq_src_address_mask,omitempty"`

	// streams per PCQ instance. Note that each queue tree entry has its own PCQ instance.
	// Max amount of bytes queued (in kilobytes) for all sub-streams per PCQ instance. Note that each queue tree entry has its own PCQ instance.
	// +kubebuilder:validation:Optional
	PcqTotalLimit *int64 `json:"pcqTotalLimit,omitempty" tf:"pcq_total_limit,omitempty"`

	// (Number) Maximum number of packets that the PFIFO queue can hold. Applies if `kind` is `pfifo`.
	// Maximum number of packets that the PFIFO queue can hold. Applies if `kind` is `pfifo`.
	// +kubebuilder:validation:Optional
	PfifoLimit *int64 `json:"pfifoLimit,omitempty" tf:"pfifo_limit,omitempty"`

	// (Number) Used by RED for average queue size calculations (for packet to byte translation).
	// Used by RED for average queue size calculations (for packet to byte translation).
	// +kubebuilder:validation:Optional
	RedAvgPacket *int64 `json:"redAvgPacket,omitempty" tf:"red_avg_packet,omitempty"`

	// (Number) Number of packets allowed for bursts of packets when there are no packets in the queue.
	// Number of packets allowed for bursts of packets when there are no packets in the queue.
	// +kubebuilder:validation:Optional
	RedBurst *int64 `json:"redBurst,omitempty" tf:"red_burst,omitempty"`

	// (Number) RED queue limit in packets.
	// RED queue limit in packets.
	// +kubebuilder:validation:Optional
	RedLimit *int64 `json:"redLimit,omitempty" tf:"red_limit,omitempty"`

	// (Number) The average queue size at which packet marking probability is the highest.
	// The average queue size at which packet marking probability is the highest.
	// +kubebuilder:validation:Optional
	RedMaxThreshold *int64 `json:"redMaxThreshold,omitempty" tf:"red_max_threshold,omitempty"`

	// (Number) Average queue size in bytes.
	// Average queue size in bytes.
	// +kubebuilder:validation:Optional
	RedMinThreshold *int64 `json:"redMinThreshold,omitempty" tf:"red_min_threshold,omitempty"`

	// robin round.
	// Amount of data in bytes that can be sent in one round-robin round.
	// +kubebuilder:validation:Optional
	SfqAllot *int64 `json:"sfqAllot,omitempty" tf:"sfq_allot,omitempty"`

	// (Number) How often hash function must be refreshed.
	// How often hash function must be refreshed.
	// +kubebuilder:validation:Optional
	SfqPerturb *int64 `json:"sfqPerturb,omitempty" tf:"sfq_perturb,omitempty"`
}

// QueueTypeSpec defines the desired state of QueueType
type QueueTypeSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   QueueTypeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider QueueTypeInitParameters `json:"initProvider,omitempty"`
}

// QueueTypeStatus defines the observed state of QueueType.
type QueueTypeStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               QueueTypeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// QueueType is the Schema for the QueueTypes API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type QueueType struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.kind) || (has(self.initProvider) && has(self.initProvider.kind))",message="spec.forProvider.kind is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   QueueTypeSpec   `json:"spec"`
	Status QueueTypeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// QueueTypeList contains a list of QueueTypes
type QueueTypeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []QueueType `json:"items"`
}

// Repository type metadata.
var (
	QueueType_Kind             = "QueueType"
	QueueType_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: QueueType_Kind}.String()
	QueueType_KindAPIVersion   = QueueType_Kind + "." + CRDGroupVersion.String()
	QueueType_GroupVersionKind = CRDGroupVersion.WithKind(QueueType_Kind)
)

func init() {
	SchemeBuilder.Register(&QueueType{}, &QueueTypeList{})
}
