// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CertificateInitParameters struct {

	// (String) Common Name (e.g. server FQDN or YOUR name).
	// Common Name (e.g. server FQDN or YOUR name).
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String)
	CopyFrom *string `json:"copyFrom,omitempty" tf:"copy_from,omitempty"`

	// (String) Country Name (2 letter code).
	// Country Name (2 letter code).
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// (Number) Certificate lifetime.
	// Certificate lifetime.
	DaysValid *int64 `json:"daysValid,omitempty" tf:"days_valid,omitempty"`

	// -import))
	Import []ImportInitParameters `json:"import,omitempty" tf:"import,omitempty"`

	// (String)
	KeySize *string `json:"keySize,omitempty" tf:"key_size,omitempty"`

	// (Set of String) Detailed key usage descriptions can be found in RFC 5280.
	// Detailed key usage descriptions can be found in RFC 5280.
	// +listType=set
	KeyUsage []*string `json:"keyUsage,omitempty" tf:"key_usage,omitempty"`

	// (String) Locality Name (eg, city).
	// Locality Name (eg, city).
	Locality *string `json:"locality,omitempty" tf:"locality,omitempty"`

	// (String) Name of the certificate. Name can be edited.
	// Name of the certificate. Name can be edited.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Organizational Unit Name (eg, section)
	// Organizational Unit Name (eg, section)
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// -sign))
	Sign []SignInitParameters `json:"sign,omitempty" tf:"sign,omitempty"`

	// -sign_via_scep))
	SignViaScep []SignViaScepInitParameters `json:"signViaScep,omitempty" tf:"sign_via_scep,omitempty"`

	// (String) State or Province Name (full name).
	// State or Province Name (full name).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) SANs (subject alternative names).
	// SANs (subject alternative names).
	SubjectAltName *string `json:"subjectAltName,omitempty" tf:"subject_alt_name,omitempty"`

	// (Boolean) If set to yes certificate is included 'in trusted certificate chain'.
	// If set to yes certificate is included 'in trusted certificate chain'.
	Trusted *bool `json:"trusted,omitempty" tf:"trusted,omitempty"`

	// (String) Organizational Unit Name (eg, section).
	// Organizational Unit Name (eg, section).
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`
}

type CertificateObservation struct {

	// (String) Authority Key Identifier.
	// Authority Key Identifier.
	Akid *string `json:"akid,omitempty" tf:"akid,omitempty"`

	// (String)
	Authority *string `json:"authority,omitempty" tf:"authority,omitempty"`

	// (String) Which CA to use if signing issued certificates.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) CRL host if issuing CA certificate.
	CACrlHost *string `json:"caCrlHost,omitempty" tf:"ca_crl_host,omitempty"`

	// (String)
	CAFingerprint *string `json:"caFingerprint,omitempty" tf:"ca_fingerprint,omitempty"`

	// (String) Common Name (e.g. server FQDN or YOUR name).
	// Common Name (e.g. server FQDN or YOUR name).
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String)
	CopyFrom *string `json:"copyFrom,omitempty" tf:"copy_from,omitempty"`

	// (String) Country Name (2 letter code).
	// Country Name (2 letter code).
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// (String)
	Crl *string `json:"crl,omitempty" tf:"crl,omitempty"`

	// (Number) Certificate lifetime.
	// Certificate lifetime.
	DaysValid *int64 `json:"daysValid,omitempty" tf:"days_valid,omitempty"`

	// (Boolean)
	DigestAlgorithm *bool `json:"digestAlgorithm,omitempty" tf:"digest_algorithm,omitempty"`

	// (Boolean)
	Dsa *bool `json:"dsa,omitempty" tf:"dsa,omitempty"`

	// (Boolean) Set to true if certificate is expired.
	// Set to true if certificate is expired.
	Expired *bool `json:"expired,omitempty" tf:"expired,omitempty"`

	// (String)
	ExpiresAfter *string `json:"expiresAfter,omitempty" tf:"expires_after,omitempty"`

	// (String)
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// -import))
	Import []ImportObservation `json:"import,omitempty" tf:"import,omitempty"`

	// (String) The date after which certificate wil be invalid.
	// The date after which certificate wil be invalid.
	InvalidAfter *string `json:"invalidAfter,omitempty" tf:"invalid_after,omitempty"`

	// (String) The date before which certificate is invalid.
	// The date before which certificate is invalid.
	InvalidBefore *string `json:"invalidBefore,omitempty" tf:"invalid_before,omitempty"`

	// (String)
	Issued *string `json:"issued,omitempty" tf:"issued,omitempty"`

	// (String)
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// (String)
	KeySize *string `json:"keySize,omitempty" tf:"key_size,omitempty"`

	// (String)
	KeyType *string `json:"keyType,omitempty" tf:"key_type,omitempty"`

	// (Set of String) Detailed key usage descriptions can be found in RFC 5280.
	// Detailed key usage descriptions can be found in RFC 5280.
	// +listType=set
	KeyUsage []*string `json:"keyUsage,omitempty" tf:"key_usage,omitempty"`

	// (String) Locality Name (eg, city).
	// Locality Name (eg, city).
	Locality *string `json:"locality,omitempty" tf:"locality,omitempty"`

	// (String) Name of the certificate. Name can be edited.
	// Name of the certificate. Name can be edited.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Organizational Unit Name (eg, section)
	// Organizational Unit Name (eg, section)
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Boolean)
	PrivateKey *bool `json:"privateKey,omitempty" tf:"private_key,omitempty"`

	// (String)
	ReqFingerprint *string `json:"reqFingerprint,omitempty" tf:"req_fingerprint,omitempty"`

	// (String)
	Revoked *string `json:"revoked,omitempty" tf:"revoked,omitempty"`

	// (String) HTTP URL to the SCEP server.
	ScepURL *string `json:"scepUrl,omitempty" tf:"scep_url,omitempty"`

	// (String)
	SerialNumber *string `json:"serialNumber,omitempty" tf:"serial_number,omitempty"`

	// -sign))
	Sign []SignObservation `json:"sign,omitempty" tf:"sign,omitempty"`

	// -sign_via_scep))
	SignViaScep []SignViaScepObservation `json:"signViaScep,omitempty" tf:"sign_via_scep,omitempty"`

	// (String) Subject Key Identifier.
	// Subject Key Identifier.
	Skid *string `json:"skid,omitempty" tf:"skid,omitempty"`

	// (String)
	SmartCardKey *string `json:"smartCardKey,omitempty" tf:"smart_card_key,omitempty"`

	// (String) State or Province Name (full name).
	// State or Province Name (full name).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Shows current status of scep client.
	// Shows current status of scep client.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) SANs (subject alternative names).
	// SANs (subject alternative names).
	SubjectAltName *string `json:"subjectAltName,omitempty" tf:"subject_alt_name,omitempty"`

	// (Boolean) If set to yes certificate is included 'in trusted certificate chain'.
	// If set to yes certificate is included 'in trusted certificate chain'.
	Trusted *bool `json:"trusted,omitempty" tf:"trusted,omitempty"`

	// (String) Organizational Unit Name (eg, section).
	// Organizational Unit Name (eg, section).
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`
}

type CertificateParameters struct {

	// (String) Common Name (e.g. server FQDN or YOUR name).
	// Common Name (e.g. server FQDN or YOUR name).
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	CopyFrom *string `json:"copyFrom,omitempty" tf:"copy_from,omitempty"`

	// (String) Country Name (2 letter code).
	// Country Name (2 letter code).
	// +kubebuilder:validation:Optional
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// (Number) Certificate lifetime.
	// Certificate lifetime.
	// +kubebuilder:validation:Optional
	DaysValid *int64 `json:"daysValid,omitempty" tf:"days_valid,omitempty"`

	// -import))
	// +kubebuilder:validation:Optional
	Import []ImportParameters `json:"import,omitempty" tf:"import,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	KeySize *string `json:"keySize,omitempty" tf:"key_size,omitempty"`

	// (Set of String) Detailed key usage descriptions can be found in RFC 5280.
	// Detailed key usage descriptions can be found in RFC 5280.
	// +kubebuilder:validation:Optional
	// +listType=set
	KeyUsage []*string `json:"keyUsage,omitempty" tf:"key_usage,omitempty"`

	// (String) Locality Name (eg, city).
	// Locality Name (eg, city).
	// +kubebuilder:validation:Optional
	Locality *string `json:"locality,omitempty" tf:"locality,omitempty"`

	// (String) Name of the certificate. Name can be edited.
	// Name of the certificate. Name can be edited.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Organizational Unit Name (eg, section)
	// Organizational Unit Name (eg, section)
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// -sign))
	// +kubebuilder:validation:Optional
	Sign []SignParameters `json:"sign,omitempty" tf:"sign,omitempty"`

	// -sign_via_scep))
	// +kubebuilder:validation:Optional
	SignViaScep []SignViaScepParameters `json:"signViaScep,omitempty" tf:"sign_via_scep,omitempty"`

	// (String) State or Province Name (full name).
	// State or Province Name (full name).
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) SANs (subject alternative names).
	// SANs (subject alternative names).
	// +kubebuilder:validation:Optional
	SubjectAltName *string `json:"subjectAltName,omitempty" tf:"subject_alt_name,omitempty"`

	// (Boolean) If set to yes certificate is included 'in trusted certificate chain'.
	// If set to yes certificate is included 'in trusted certificate chain'.
	// +kubebuilder:validation:Optional
	Trusted *bool `json:"trusted,omitempty" tf:"trusted,omitempty"`

	// (String) Organizational Unit Name (eg, section).
	// Organizational Unit Name (eg, section).
	// +kubebuilder:validation:Optional
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`
}

type ImportInitParameters struct {

	// (String) Certificate in PEM format.
	// Certificate in PEM format.
	CertFileContent *string `json:"certFileContent,omitempty" tf:"cert_file_content,omitempty"`

	// (String) Certificate file name that will be imported.
	// Certificate file name that will be imported.
	CertFileName *string `json:"certFileName,omitempty" tf:"cert_file_name,omitempty"`

	// (String) Key in PEM format.
	// Key in PEM format.
	KeyFileContent *string `json:"keyFileContent,omitempty" tf:"key_file_content,omitempty"`

	// (String) Key file name that will be imported.
	// Key file name that will be imported.
	KeyFileName *string `json:"keyFileName,omitempty" tf:"key_file_name,omitempty"`

	// (String, Sensitive) File passphrase if there is such.
	// File passphrase if there is such.
	PassphraseSecretRef *v2.SecretKeySelector `json:"passphraseSecretRef,omitempty" tf:"-"`
}

type ImportObservation struct {

	// (String) Certificate in PEM format.
	// Certificate in PEM format.
	CertFileContent *string `json:"certFileContent,omitempty" tf:"cert_file_content,omitempty"`

	// (String) Certificate file name that will be imported.
	// Certificate file name that will be imported.
	CertFileName *string `json:"certFileName,omitempty" tf:"cert_file_name,omitempty"`

	// (String) Key in PEM format.
	// Key in PEM format.
	KeyFileContent *string `json:"keyFileContent,omitempty" tf:"key_file_content,omitempty"`

	// (String) Key file name that will be imported.
	// Key file name that will be imported.
	KeyFileName *string `json:"keyFileName,omitempty" tf:"key_file_name,omitempty"`
}

type ImportParameters struct {

	// (String) Certificate in PEM format.
	// Certificate in PEM format.
	// +kubebuilder:validation:Optional
	CertFileContent *string `json:"certFileContent,omitempty" tf:"cert_file_content,omitempty"`

	// (String) Certificate file name that will be imported.
	// Certificate file name that will be imported.
	// +kubebuilder:validation:Optional
	CertFileName *string `json:"certFileName,omitempty" tf:"cert_file_name,omitempty"`

	// (String) Key in PEM format.
	// Key in PEM format.
	// +kubebuilder:validation:Optional
	KeyFileContent *string `json:"keyFileContent,omitempty" tf:"key_file_content,omitempty"`

	// (String) Key file name that will be imported.
	// Key file name that will be imported.
	// +kubebuilder:validation:Optional
	KeyFileName *string `json:"keyFileName,omitempty" tf:"key_file_name,omitempty"`

	// (String, Sensitive) File passphrase if there is such.
	// File passphrase if there is such.
	// +kubebuilder:validation:Optional
	PassphraseSecretRef *v2.SecretKeySelector `json:"passphraseSecretRef,omitempty" tf:"-"`
}

type SignInitParameters struct {

	// (String) Which CA to use if signing issued certificates.
	// Which CA to use if signing issued certificates.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) CRL host if issuing CA certificate.
	// CRL host if issuing CA certificate.
	CACrlHost *string `json:"caCrlHost,omitempty" tf:"ca_crl_host,omitempty"`
}

type SignObservation struct {

	// (String) Which CA to use if signing issued certificates.
	// Which CA to use if signing issued certificates.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) CRL host if issuing CA certificate.
	// CRL host if issuing CA certificate.
	CACrlHost *string `json:"caCrlHost,omitempty" tf:"ca_crl_host,omitempty"`
}

type SignParameters struct {

	// (String) Which CA to use if signing issued certificates.
	// Which CA to use if signing issued certificates.
	// +kubebuilder:validation:Optional
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) CRL host if issuing CA certificate.
	// CRL host if issuing CA certificate.
	// +kubebuilder:validation:Optional
	CACrlHost *string `json:"caCrlHost,omitempty" tf:"ca_crl_host,omitempty"`
}

type SignViaScepInitParameters struct {

	// (String) SCEP CA identity.
	// SCEP CA identity.
	CAIdentity *string `json:"caIdentity,omitempty" tf:"ca_identity,omitempty"`

	// (String, Sensitive) A challenge password.
	// A challenge password.
	ChallengePasswordSecretRef *v2.SecretKeySelector `json:"challengePasswordSecretRef,omitempty" tf:"-"`

	// (Boolean) Whether to store a private key on smart card if hardware supports it.
	// Whether to store a private key on smart card if hardware supports it.
	OnSmartCard *bool `json:"onSmartCard,omitempty" tf:"on_smart_card,omitempty"`

	// (Boolean) Check certificate expiration and refresh it if expired.
	// Check certificate expiration and refresh it if expired.
	Refresh *bool `json:"refresh,omitempty" tf:"refresh,omitempty"`

	// (String) HTTP URL to the SCEP server.
	// HTTP URL to the SCEP server.
	ScepURL *string `json:"scepUrl,omitempty" tf:"scep_url,omitempty"`
}

type SignViaScepObservation struct {

	// (String) SCEP CA identity.
	// SCEP CA identity.
	CAIdentity *string `json:"caIdentity,omitempty" tf:"ca_identity,omitempty"`

	// (Boolean) Whether to store a private key on smart card if hardware supports it.
	// Whether to store a private key on smart card if hardware supports it.
	OnSmartCard *bool `json:"onSmartCard,omitempty" tf:"on_smart_card,omitempty"`

	// (Boolean) Check certificate expiration and refresh it if expired.
	// Check certificate expiration and refresh it if expired.
	Refresh *bool `json:"refresh,omitempty" tf:"refresh,omitempty"`

	// (String) HTTP URL to the SCEP server.
	// HTTP URL to the SCEP server.
	ScepURL *string `json:"scepUrl,omitempty" tf:"scep_url,omitempty"`
}

type SignViaScepParameters struct {

	// (String) SCEP CA identity.
	// SCEP CA identity.
	// +kubebuilder:validation:Optional
	CAIdentity *string `json:"caIdentity,omitempty" tf:"ca_identity,omitempty"`

	// (String, Sensitive) A challenge password.
	// A challenge password.
	// +kubebuilder:validation:Optional
	ChallengePasswordSecretRef *v2.SecretKeySelector `json:"challengePasswordSecretRef,omitempty" tf:"-"`

	// (Boolean) Whether to store a private key on smart card if hardware supports it.
	// Whether to store a private key on smart card if hardware supports it.
	// +kubebuilder:validation:Optional
	OnSmartCard *bool `json:"onSmartCard,omitempty" tf:"on_smart_card,omitempty"`

	// (Boolean) Check certificate expiration and refresh it if expired.
	// Check certificate expiration and refresh it if expired.
	// +kubebuilder:validation:Optional
	Refresh *bool `json:"refresh,omitempty" tf:"refresh,omitempty"`

	// (String) HTTP URL to the SCEP server.
	// HTTP URL to the SCEP server.
	// +kubebuilder:validation:Optional
	ScepURL *string `json:"scepUrl" tf:"scep_url,omitempty"`
}

// CertificateSpec defines the desired state of Certificate
type CertificateSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CertificateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CertificateInitParameters `json:"initProvider,omitempty"`
}

// CertificateStatus defines the observed state of Certificate.
type CertificateStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CertificateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Certificate is the Schema for the Certificates API. Certificate resource management consists of two independent processes: * key creation and certificate signing request (`key` + `csr`) * certificate signing by the issuer (`crt`) For a complete certificate creation cycle, both of the above steps must be performed. In this case the `sign {}` block must be specified in the configuration. If you need to import the current state of the certificate resource, then do not specify the `sign{}` block. Importing an external certificate is also done without specifying the `sign{}` block, because the certificate should have already been signed by the issuer at this step.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type Certificate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.commonName) || (has(self.initProvider) && has(self.initProvider.commonName))",message="spec.forProvider.commonName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   CertificateSpec   `json:"spec"`
	Status CertificateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CertificateList contains a list of Certificates
type CertificateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Certificate `json:"items"`
}

// Repository type metadata.
var (
	Certificate_Kind             = "Certificate"
	Certificate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Certificate_Kind}.String()
	Certificate_KindAPIVersion   = Certificate_Kind + "." + CRDGroupVersion.String()
	Certificate_GroupVersionKind = CRDGroupVersion.WithKind(Certificate_Kind)
)

func init() {
	SchemeBuilder.Register(&Certificate{}, &CertificateList{})
}
