// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type LedInitParameters struct {

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) An option to set the interface to which the LED is connected.
	// An option to set the interface to which the LED is connected.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (List of String) An option to set the LED name.
	// An option to set the LED name.
	Leds []*string `json:"leds,omitempty" tf:"leds,omitempty"`

	// (Number) An option to set the signal strength threshold for the modem LED.
	// An option to set the signal strength threshold for the modem LED.
	ModemSignalTreshold *int64 `json:"modemSignalTreshold,omitempty" tf:"modem_signal_treshold,omitempty"`

	// (String) An option to set the LED type.
	// An option to set the LED type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LedObservation struct {

	// (Boolean) It's the default item.
	// It's the default item.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) An option to set the interface to which the LED is connected.
	// An option to set the interface to which the LED is connected.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (List of String) An option to set the LED name.
	// An option to set the LED name.
	Leds []*string `json:"leds,omitempty" tf:"leds,omitempty"`

	// (Number) An option to set the signal strength threshold for the modem LED.
	// An option to set the signal strength threshold for the modem LED.
	ModemSignalTreshold *int64 `json:"modemSignalTreshold,omitempty" tf:"modem_signal_treshold,omitempty"`

	// (String) An option to set the LED type.
	// An option to set the LED type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LedParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) An option to set the interface to which the LED is connected.
	// An option to set the interface to which the LED is connected.
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (List of String) An option to set the LED name.
	// An option to set the LED name.
	// +kubebuilder:validation:Optional
	Leds []*string `json:"leds,omitempty" tf:"leds,omitempty"`

	// (Number) An option to set the signal strength threshold for the modem LED.
	// An option to set the signal strength threshold for the modem LED.
	// +kubebuilder:validation:Optional
	ModemSignalTreshold *int64 `json:"modemSignalTreshold,omitempty" tf:"modem_signal_treshold,omitempty"`

	// (String) An option to set the LED type.
	// An option to set the LED type.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// LedSpec defines the desired state of Led
type LedSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   LedParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LedInitParameters `json:"initProvider,omitempty"`
}

// LedStatus defines the observed state of Led.
type LedStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               LedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Led is the Schema for the Leds API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type Led struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LedSpec   `json:"spec"`
	Status            LedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LedList contains a list of Leds
type LedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Led `json:"items"`
}

// Repository type metadata.
var (
	Led_Kind             = "Led"
	Led_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Led_Kind}.String()
	Led_KindAPIVersion   = Led_Kind + "." + CRDGroupVersion.String()
	Led_GroupVersionKind = CRDGroupVersion.WithKind(Led_Kind)
)

func init() {
	SchemeBuilder.Register(&Led{}, &LedList{})
}
