// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NtpServerInitParameters struct {

	// an integer identifying the cryptographic key used to generate the message-authentication code.
	// NTP symmetric key, used for authentication between the NTP client and server. Key Identifier (Key ID) - an integer identifying the cryptographic key used to generate the message-authentication code.
	AuthKey *string `json:"authKey,omitempty" tf:"auth_key,omitempty"`

	// addresses field.
	// Enable certain NTP server mode, for this mode to work you have to set up broadcast-addresses field.
	Broadcast *bool `json:"broadcast,omitempty" tf:"broadcast,omitempty"`

	// (String) Set broadcast address to use for NTP server broadcast mode.
	// Set broadcast address to use for NTP server broadcast mode.
	BroadcastAddresses *string `json:"broadcastAddresses,omitempty" tf:"broadcast_addresses,omitempty"`

	// (Boolean) Enable NTP server.
	// Enable NTP server.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Manually set stratum if ```use_local_clock = true```.
	// Manually set stratum if ```use_local_clock = true```.
	LocalClockStratum *int64 `json:"localClockStratum,omitempty" tf:"local_clock_stratum,omitempty"`

	// (Boolean) Enable certain NTP server mode.
	// Enable certain NTP server mode.
	Manycast *bool `json:"manycast,omitempty" tf:"manycast,omitempty"`

	// (Boolean) Enable certain NTP server mode.
	// Enable certain NTP server mode.
	Multicast *bool `json:"multicast,omitempty" tf:"multicast,omitempty"`

	// (Boolean) The server will supply its local system time as valid if others are not available.
	// The server will supply its local system time as valid if others are not available.
	UseLocalClock *bool `json:"useLocalClock,omitempty" tf:"use_local_clock,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type NtpServerObservation struct {

	// an integer identifying the cryptographic key used to generate the message-authentication code.
	// NTP symmetric key, used for authentication between the NTP client and server. Key Identifier (Key ID) - an integer identifying the cryptographic key used to generate the message-authentication code.
	AuthKey *string `json:"authKey,omitempty" tf:"auth_key,omitempty"`

	// addresses field.
	// Enable certain NTP server mode, for this mode to work you have to set up broadcast-addresses field.
	Broadcast *bool `json:"broadcast,omitempty" tf:"broadcast,omitempty"`

	// (String) Set broadcast address to use for NTP server broadcast mode.
	// Set broadcast address to use for NTP server broadcast mode.
	BroadcastAddresses *string `json:"broadcastAddresses,omitempty" tf:"broadcast_addresses,omitempty"`

	// (Boolean) Enable NTP server.
	// Enable NTP server.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Manually set stratum if ```use_local_clock = true```.
	// Manually set stratum if ```use_local_clock = true```.
	LocalClockStratum *int64 `json:"localClockStratum,omitempty" tf:"local_clock_stratum,omitempty"`

	// (Boolean) Enable certain NTP server mode.
	// Enable certain NTP server mode.
	Manycast *bool `json:"manycast,omitempty" tf:"manycast,omitempty"`

	// (Boolean) Enable certain NTP server mode.
	// Enable certain NTP server mode.
	Multicast *bool `json:"multicast,omitempty" tf:"multicast,omitempty"`

	// (Boolean) The server will supply its local system time as valid if others are not available.
	// The server will supply its local system time as valid if others are not available.
	UseLocalClock *bool `json:"useLocalClock,omitempty" tf:"use_local_clock,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type NtpServerParameters struct {

	// an integer identifying the cryptographic key used to generate the message-authentication code.
	// NTP symmetric key, used for authentication between the NTP client and server. Key Identifier (Key ID) - an integer identifying the cryptographic key used to generate the message-authentication code.
	// +kubebuilder:validation:Optional
	AuthKey *string `json:"authKey,omitempty" tf:"auth_key,omitempty"`

	// addresses field.
	// Enable certain NTP server mode, for this mode to work you have to set up broadcast-addresses field.
	// +kubebuilder:validation:Optional
	Broadcast *bool `json:"broadcast,omitempty" tf:"broadcast,omitempty"`

	// (String) Set broadcast address to use for NTP server broadcast mode.
	// Set broadcast address to use for NTP server broadcast mode.
	// +kubebuilder:validation:Optional
	BroadcastAddresses *string `json:"broadcastAddresses,omitempty" tf:"broadcast_addresses,omitempty"`

	// (Boolean) Enable NTP server.
	// Enable NTP server.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Manually set stratum if ```use_local_clock = true```.
	// Manually set stratum if ```use_local_clock = true```.
	// +kubebuilder:validation:Optional
	LocalClockStratum *int64 `json:"localClockStratum,omitempty" tf:"local_clock_stratum,omitempty"`

	// (Boolean) Enable certain NTP server mode.
	// Enable certain NTP server mode.
	// +kubebuilder:validation:Optional
	Manycast *bool `json:"manycast,omitempty" tf:"manycast,omitempty"`

	// (Boolean) Enable certain NTP server mode.
	// Enable certain NTP server mode.
	// +kubebuilder:validation:Optional
	Multicast *bool `json:"multicast,omitempty" tf:"multicast,omitempty"`

	// (Boolean) The server will supply its local system time as valid if others are not available.
	// The server will supply its local system time as valid if others are not available.
	// +kubebuilder:validation:Optional
	UseLocalClock *bool `json:"useLocalClock,omitempty" tf:"use_local_clock,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	// +kubebuilder:validation:Optional
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

// NtpServerSpec defines the desired state of NtpServer
type NtpServerSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   NtpServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NtpServerInitParameters `json:"initProvider,omitempty"`
}

// NtpServerStatus defines the observed state of NtpServer.
type NtpServerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NtpServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NtpServer is the Schema for the NtpServers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type NtpServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NtpServerSpec   `json:"spec"`
	Status            NtpServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NtpServerList contains a list of NtpServers
type NtpServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NtpServer `json:"items"`
}

// Repository type metadata.
var (
	NtpServer_Kind             = "NtpServer"
	NtpServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NtpServer_Kind}.String()
	NtpServer_KindAPIVersion   = NtpServer_Kind + "." + CRDGroupVersion.String()
	NtpServer_GroupVersionKind = CRDGroupVersion.WithKind(NtpServer_Kind)
)

func init() {
	SchemeBuilder.Register(&NtpServer{}, &NtpServerList{})
}
