// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ZerotierInitParameters struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// bit unique instance address.
	// The 40-bit unique instance address.
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// (Set of String) The interfaces to discover ZeroTier peers by ARP and IP type connections.
	// The interfaces to discover ZeroTier peers by ARP and IP type connections.
	// +listType=set
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// (String) Name of the ZeroTier instance.
	// Name of the ZeroTier instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The port number the instance listens to.
	// The port number the instance listens to.
	Port *int64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Number) The route distance for routes obtained from the planet/moon server.
	// The route distance for routes obtained from the planet/moon server.
	RouteDistance *int64 `json:"routeDistance,omitempty" tf:"route_distance,omitempty"`
}

type ZerotierObservation struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// bit unique instance address.
	// The 40-bit unique instance address.
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// (String) The public identity of the ZeroTier instance.
	// The public identity of the ZeroTier instance.
	IdentityPublic *string `json:"identityPublic,omitempty" tf:"identity_public,omitempty"`

	// (Set of String) The interfaces to discover ZeroTier peers by ARP and IP type connections.
	// The interfaces to discover ZeroTier peers by ARP and IP type connections.
	// +listType=set
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// (String) Name of the ZeroTier instance.
	// Name of the ZeroTier instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) A flag whether the ZeroTier instance is currently online.
	// A flag whether the ZeroTier instance is currently online.
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Number) The port number the instance listens to.
	// The port number the instance listens to.
	Port *int64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Number) The route distance for routes obtained from the planet/moon server.
	// The route distance for routes obtained from the planet/moon server.
	RouteDistance *int64 `json:"routeDistance,omitempty" tf:"route_distance,omitempty"`

	// (String) The state of the ZeroTier instance.
	// The state of the ZeroTier instance.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type ZerotierParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// bit unique instance address.
	// The 40-bit unique instance address.
	// +kubebuilder:validation:Optional
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// (Set of String) The interfaces to discover ZeroTier peers by ARP and IP type connections.
	// The interfaces to discover ZeroTier peers by ARP and IP type connections.
	// +kubebuilder:validation:Optional
	// +listType=set
	Interfaces []*string `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// (String) Name of the ZeroTier instance.
	// Name of the ZeroTier instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The port number the instance listens to.
	// The port number the instance listens to.
	// +kubebuilder:validation:Optional
	Port *int64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Number) The route distance for routes obtained from the planet/moon server.
	// The route distance for routes obtained from the planet/moon server.
	// +kubebuilder:validation:Optional
	RouteDistance *int64 `json:"routeDistance,omitempty" tf:"route_distance,omitempty"`
}

// ZerotierSpec defines the desired state of Zerotier
type ZerotierSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ZerotierParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZerotierInitParameters `json:"initProvider,omitempty"`
}

// ZerotierStatus defines the observed state of Zerotier.
type ZerotierStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ZerotierObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Zerotier is the Schema for the Zerotiers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type Zerotier struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZerotierSpec   `json:"spec"`
	Status ZerotierStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZerotierList contains a list of Zerotiers
type ZerotierList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Zerotier `json:"items"`
}

// Repository type metadata.
var (
	Zerotier_Kind             = "Zerotier"
	Zerotier_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Zerotier_Kind}.String()
	Zerotier_KindAPIVersion   = Zerotier_Kind + "." + CRDGroupVersion.String()
	Zerotier_GroupVersionKind = CRDGroupVersion.WithKind(Zerotier_Kind)
)

func init() {
	SchemeBuilder.Register(&Zerotier{}, &ZerotierList{})
}
