// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IdentityInitParameters struct {

	// Device name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IdentityObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Device name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type IdentityParameters struct {

	// Device name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// IdentitySpec defines the desired state of Identity
type IdentitySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IdentityParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentityInitParameters `json:"initProvider,omitempty"`
}

// IdentityStatus defines the observed state of Identity.
type IdentityStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IdentityObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Identity is the Schema for the Identitys API. #### This is an alias for backwards compatibility between plugin versions. Please see documentation for [routeros_system_identity](system_identity.md)
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type Identity struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   IdentitySpec   `json:"spec"`
	Status IdentityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentityList contains a list of Identitys
type IdentityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Identity `json:"items"`
}

// Repository type metadata.
var (
	Identity_Kind             = "Identity"
	Identity_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Identity_Kind}.String()
	Identity_KindAPIVersion   = Identity_Kind + "." + CRDGroupVersion.String()
	Identity_GroupVersionKind = CRDGroupVersion.WithKind(Identity_Kind)
)

func init() {
	SchemeBuilder.Register(&Identity{}, &IdentityList{})
}
