// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CAPsMANInterfaceInitParameters struct {

	// timeout in IP/Settings, default is 30s. Can use postfix `ms`, `s`, `m`, `h`, `d` for milliseconds, seconds, minutes, hours or days. If no postfix is set then seconds (s) is used.
	// ARP timeout is time how long ARP record is kept in ARP table after no packets are received from IP. Value auto equals to the value of arp-timeout in IP/Settings, default is 30s. Can use postfix `ms`, `s`, `m`, `h`, `d` for milliseconds, seconds, minutes, hours or days. If no postfix is set then seconds (s) is used.
	ArpTimeout *string `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// (Map of String) Channel inline settings.
	// Channel inline settings.
	// +mapType=granular
	Channel map[string]*string `json:"channel,omitempty" tf:"channel,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Map of String) Configuration inline settings.
	// Configuration inline settings.
	// +mapType=granular
	Configuration map[string]*string `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (Map of String) Datapath inline settings.
	// Datapath inline settings.
	// +mapType=granular
	Datapath map[string]*string `json:"datapath,omitempty" tf:"datapath,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) MAC address (BSSID) to use for the interface.
	// MAC address (BSSID) to use for the interface.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The corresponding master interface of the virtual one.
	// The corresponding master interface of the virtual one.
	MasterInterface *string `json:"masterInterface,omitempty" tf:"master_interface,omitempty"`

	// (String) Name of the interface.
	// Name of the interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The MAC address of the associated radio.
	// The MAC address of the associated radio.
	RadioMac *string `json:"radioMac,omitempty" tf:"radio_mac,omitempty"`

	// (String) Name of the associated radio.
	// Name of the associated radio.
	RadioName *string `json:"radioName,omitempty" tf:"radio_name,omitempty"`

	// (Map of String) Rates inline settings.
	// Rates inline settings.
	// +mapType=granular
	Rates map[string]*string `json:"rates,omitempty" tf:"rates,omitempty"`

	// (Map of String) Security inline settings.
	// Security inline settings.
	// +mapType=granular
	Security map[string]*string `json:"security,omitempty" tf:"security,omitempty"`
}

type CAPsMANInterfaceObservation struct {

	// timeout in IP/Settings, default is 30s. Can use postfix `ms`, `s`, `m`, `h`, `d` for milliseconds, seconds, minutes, hours or days. If no postfix is set then seconds (s) is used.
	// ARP timeout is time how long ARP record is kept in ARP table after no packets are received from IP. Value auto equals to the value of arp-timeout in IP/Settings, default is 30s. Can use postfix `ms`, `s`, `m`, `h`, `d` for milliseconds, seconds, minutes, hours or days. If no postfix is set then seconds (s) is used.
	ArpTimeout *string `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// (Boolean) A flag whether the interface is currently available for the CAPsMAN.
	// A flag whether the interface is currently available for the CAPsMAN.
	Bound *bool `json:"bound,omitempty" tf:"bound,omitempty"`

	// (Map of String) Channel inline settings.
	// Channel inline settings.
	// +mapType=granular
	Channel map[string]*string `json:"channel,omitempty" tf:"channel,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Map of String) Configuration inline settings.
	// Configuration inline settings.
	// +mapType=granular
	Configuration map[string]*string `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (Map of String) Datapath inline settings.
	// Datapath inline settings.
	// +mapType=granular
	Datapath map[string]*string `json:"datapath,omitempty" tf:"datapath,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) A flag whether the interface is currently inactive.
	// A flag whether the interface is currently inactive.
	Inactive *bool `json:"inactive,omitempty" tf:"inactive,omitempty"`

	// (Number) Layer2 Maximum transmission unit. [See](https://wiki.mikrotik.com/wiki/Maximum_Transmission_Unit_on_RouterBoards).
	// Layer2 Maximum transmission unit. [See](https://wiki.mikrotik.com/wiki/Maximum_Transmission_Unit_on_RouterBoards).
	L2Mtu *int64 `json:"l2mtu,omitempty" tf:"l2mtu,omitempty"`

	// (String) MAC address (BSSID) to use for the interface.
	// MAC address (BSSID) to use for the interface.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (Boolean) A flag whether the interface is not a virtual one.
	// A flag whether the interface is not a virtual one.
	Master *bool `json:"master,omitempty" tf:"master,omitempty"`

	// (String) The corresponding master interface of the virtual one.
	// The corresponding master interface of the virtual one.
	MasterInterface *string `json:"masterInterface,omitempty" tf:"master_interface,omitempty"`

	// (String) Name of the interface.
	// Name of the interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The MAC address of the associated radio.
	// The MAC address of the associated radio.
	RadioMac *string `json:"radioMac,omitempty" tf:"radio_mac,omitempty"`

	// (String) Name of the associated radio.
	// Name of the associated radio.
	RadioName *string `json:"radioName,omitempty" tf:"radio_name,omitempty"`

	// (Map of String) Rates inline settings.
	// Rates inline settings.
	// +mapType=granular
	Rates map[string]*string `json:"rates,omitempty" tf:"rates,omitempty"`

	// (Boolean) A flag whether the interface has established a link to another device.
	// A flag whether the interface has established a link to another device.
	Running *bool `json:"running,omitempty" tf:"running,omitempty"`

	// (Map of String) Security inline settings.
	// Security inline settings.
	// +mapType=granular
	Security map[string]*string `json:"security,omitempty" tf:"security,omitempty"`
}

type CAPsMANInterfaceParameters struct {

	// timeout in IP/Settings, default is 30s. Can use postfix `ms`, `s`, `m`, `h`, `d` for milliseconds, seconds, minutes, hours or days. If no postfix is set then seconds (s) is used.
	// ARP timeout is time how long ARP record is kept in ARP table after no packets are received from IP. Value auto equals to the value of arp-timeout in IP/Settings, default is 30s. Can use postfix `ms`, `s`, `m`, `h`, `d` for milliseconds, seconds, minutes, hours or days. If no postfix is set then seconds (s) is used.
	// +kubebuilder:validation:Optional
	ArpTimeout *string `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// (Map of String) Channel inline settings.
	// Channel inline settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Channel map[string]*string `json:"channel,omitempty" tf:"channel,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Map of String) Configuration inline settings.
	// Configuration inline settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Configuration map[string]*string `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (Map of String) Datapath inline settings.
	// Datapath inline settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Datapath map[string]*string `json:"datapath,omitempty" tf:"datapath,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) MAC address (BSSID) to use for the interface.
	// MAC address (BSSID) to use for the interface.
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The corresponding master interface of the virtual one.
	// The corresponding master interface of the virtual one.
	// +kubebuilder:validation:Optional
	MasterInterface *string `json:"masterInterface,omitempty" tf:"master_interface,omitempty"`

	// (String) Name of the interface.
	// Name of the interface.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The MAC address of the associated radio.
	// The MAC address of the associated radio.
	// +kubebuilder:validation:Optional
	RadioMac *string `json:"radioMac,omitempty" tf:"radio_mac,omitempty"`

	// (String) Name of the associated radio.
	// Name of the associated radio.
	// +kubebuilder:validation:Optional
	RadioName *string `json:"radioName,omitempty" tf:"radio_name,omitempty"`

	// (Map of String) Rates inline settings.
	// Rates inline settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Rates map[string]*string `json:"rates,omitempty" tf:"rates,omitempty"`

	// (Map of String) Security inline settings.
	// Security inline settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Security map[string]*string `json:"security,omitempty" tf:"security,omitempty"`
}

// CAPsMANInterfaceSpec defines the desired state of CAPsMANInterface
type CAPsMANInterfaceSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CAPsMANInterfaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CAPsMANInterfaceInitParameters `json:"initProvider,omitempty"`
}

// CAPsMANInterfaceStatus defines the observed state of CAPsMANInterface.
type CAPsMANInterfaceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CAPsMANInterfaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CAPsMANInterface is the Schema for the CAPsMANInterfaces API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type CAPsMANInterface struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   CAPsMANInterfaceSpec   `json:"spec"`
	Status CAPsMANInterfaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CAPsMANInterfaceList contains a list of CAPsMANInterfaces
type CAPsMANInterfaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CAPsMANInterface `json:"items"`
}

// Repository type metadata.
var (
	CAPsMANInterface_Kind             = "CAPsMANInterface"
	CAPsMANInterface_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CAPsMANInterface_Kind}.String()
	CAPsMANInterface_KindAPIVersion   = CAPsMANInterface_Kind + "." + CRDGroupVersion.String()
	CAPsMANInterface_GroupVersionKind = CRDGroupVersion.WithKind(CAPsMANInterface_Kind)
)

func init() {
	SchemeBuilder.Register(&CAPsMANInterface{}, &CAPsMANInterfaceList{})
}
