// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DHCPServerOptionInitParameters struct {

	// (Number) The number of the DHCP option
	// The number of the DHCP option RouterOS accepts a DHCP option code 1..254, or "vendor-specific"; 0 is out of range.
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// side even if the DHCP-client does not request such parameter.
	// Force the DHCP option from the server-side even if the DHCP-client does not request such parameter.
	Force *bool `json:"force,omitempty" tf:"force,omitempty"`

	// (String) The name of the DHCP option
	// The name of the DHCP option
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The value with formatting using Mikrotik settings https://wiki.mikrotik.com/wiki/Manual:IP/DHCP_Server#DHCP_Options
	// The value with formatting using Mikrotik settings https://wiki.mikrotik.com/wiki/Manual:IP/DHCP_Server#DHCP_Options
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DHCPServerOptionObservation struct {

	// (Number) The number of the DHCP option
	// The number of the DHCP option RouterOS accepts a DHCP option code 1..254, or "vendor-specific"; 0 is out of range.
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// side even if the DHCP-client does not request such parameter.
	// Force the DHCP option from the server-side even if the DHCP-client does not request such parameter.
	Force *bool `json:"force,omitempty" tf:"force,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the DHCP option
	// The name of the DHCP option
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The computed value of the option as an hex value
	// The computed value of the option as an hex value
	RawValue *string `json:"rawValue,omitempty" tf:"raw_value,omitempty"`

	// (String) The value with formatting using Mikrotik settings https://wiki.mikrotik.com/wiki/Manual:IP/DHCP_Server#DHCP_Options
	// The value with formatting using Mikrotik settings https://wiki.mikrotik.com/wiki/Manual:IP/DHCP_Server#DHCP_Options
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DHCPServerOptionParameters struct {

	// (Number) The number of the DHCP option
	// The number of the DHCP option RouterOS accepts a DHCP option code 1..254, or "vendor-specific"; 0 is out of range.
	// +kubebuilder:validation:Optional
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// side even if the DHCP-client does not request such parameter.
	// Force the DHCP option from the server-side even if the DHCP-client does not request such parameter.
	// +kubebuilder:validation:Optional
	Force *bool `json:"force,omitempty" tf:"force,omitempty"`

	// (String) The name of the DHCP option
	// The name of the DHCP option
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The value with formatting using Mikrotik settings https://wiki.mikrotik.com/wiki/Manual:IP/DHCP_Server#DHCP_Options
	// The value with formatting using Mikrotik settings https://wiki.mikrotik.com/wiki/Manual:IP/DHCP_Server#DHCP_Options
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// DHCPServerOptionSpec defines the desired state of DHCPServerOption
type DHCPServerOptionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DHCPServerOptionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DHCPServerOptionInitParameters `json:"initProvider,omitempty"`
}

// DHCPServerOptionStatus defines the observed state of DHCPServerOption.
type DHCPServerOptionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DHCPServerOptionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DHCPServerOption is the Schema for the DHCPServerOptions API. Creates a DHCP lease on the mikrotik device.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type DHCPServerOption struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.code) || (has(self.initProvider) && has(self.initProvider.code))",message="spec.forProvider.code is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   DHCPServerOptionSpec   `json:"spec"`
	Status DHCPServerOptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DHCPServerOptionList contains a list of DHCPServerOptions
type DHCPServerOptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DHCPServerOption `json:"items"`
}

// Repository type metadata.
var (
	DHCPServerOption_Kind             = "DHCPServerOption"
	DHCPServerOption_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DHCPServerOption_Kind}.String()
	DHCPServerOption_KindAPIVersion   = DHCPServerOption_Kind + "." + CRDGroupVersion.String()
	DHCPServerOption_GroupVersionKind = CRDGroupVersion.WithKind(DHCPServerOption_Kind)
)

func init() {
	SchemeBuilder.Register(&DHCPServerOption{}, &DHCPServerOptionList{})
}
