// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NATPmpInterfacesInitParameters struct {

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Allow specifying what public IP to use if the external interface has more than one IP available.
	// Allow specifying what public IP to use if the external interface has more than one IP available.
	ForcedIP *string `json:"forcedIp,omitempty" tf:"forced_ip,omitempty"`

	// (String) Interface name on which PMP will be running on
	// Interface name on which PMP will be running on
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// PMP interface type:
	// NAT-PMP interface type:
	// * external - the interface a global IP address is assigned to
	// * internal - router's local interface the clients are connected to
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NATPmpInterfacesObservation struct {

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Boolean) Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	// Configuration item created by software, not by management interface. It is not exported, and cannot be directly modified.
	Dynamic *bool `json:"dynamic,omitempty" tf:"dynamic,omitempty"`

	// (String) Allow specifying what public IP to use if the external interface has more than one IP available.
	// Allow specifying what public IP to use if the external interface has more than one IP available.
	ForcedIP *string `json:"forcedIp,omitempty" tf:"forced_ip,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Interface name on which PMP will be running on
	// Interface name on which PMP will be running on
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// PMP interface type:
	// NAT-PMP interface type:
	// * external - the interface a global IP address is assigned to
	// * internal - router's local interface the clients are connected to
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NATPmpInterfacesParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) Allow specifying what public IP to use if the external interface has more than one IP available.
	// Allow specifying what public IP to use if the external interface has more than one IP available.
	// +kubebuilder:validation:Optional
	ForcedIP *string `json:"forcedIp,omitempty" tf:"forced_ip,omitempty"`

	// (String) Interface name on which PMP will be running on
	// Interface name on which PMP will be running on
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// PMP interface type:
	// NAT-PMP interface type:
	// * external - the interface a global IP address is assigned to
	// * internal - router's local interface the clients are connected to
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// NATPmpInterfacesSpec defines the desired state of NATPmpInterfaces
type NATPmpInterfacesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NATPmpInterfacesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NATPmpInterfacesInitParameters `json:"initProvider,omitempty"`
}

// NATPmpInterfacesStatus defines the observed state of NATPmpInterfaces.
type NATPmpInterfacesStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NATPmpInterfacesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NATPmpInterfaces is the Schema for the NATPmpInterfacess API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type NATPmpInterfaces struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interface) || (has(self.initProvider) && has(self.initProvider.interface))",message="spec.forProvider.interface is a required parameter"
	Spec   NATPmpInterfacesSpec   `json:"spec"`
	Status NATPmpInterfacesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NATPmpInterfacesList contains a list of NATPmpInterfacess
type NATPmpInterfacesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NATPmpInterfaces `json:"items"`
}

// Repository type metadata.
var (
	NATPmpInterfaces_Kind             = "NATPmpInterfaces"
	NATPmpInterfaces_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NATPmpInterfaces_Kind}.String()
	NATPmpInterfaces_KindAPIVersion   = NATPmpInterfaces_Kind + "." + CRDGroupVersion.String()
	NATPmpInterfaces_GroupVersionKind = CRDGroupVersion.WithKind(NATPmpInterfaces_Kind)
)

func init() {
	SchemeBuilder.Register(&NATPmpInterfaces{}, &NATPmpInterfacesList{})
}
