// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type UpnpInitParameters struct {

	// (Boolean) Whether or not should the users be allowed to disable the router's external interface. This functionality (for users to be able to turn the router's external interface off without any authentication procedure) is required by the standard, but as it is sometimes not expected or unwanted in UPnP deployments which the standard was not designed for (it was designed mostly for home users to establish their own local networks), you can disable this behavior
	// Whether or not should the users be allowed to disable the router's external interface. This functionality (for users to be able to turn the router's external interface off without any authentication procedure) is required by the standard, but as it is sometimes not expected or unwanted in UPnP deployments which the standard was not designed for (it was designed mostly for home users to establish their own local networks), you can disable this behavior
	AllowDisableExternalInterface *bool `json:"allowDisableExternalInterface,omitempty" tf:"allow_disable_external_interface,omitempty"`

	// (Boolean) Enable UPnP service.
	// Enable UPnP service.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Enable a workaround for some broken implementations, which are handling the absence of UPnP rules incorrectly (for example, popping up error messages). This option will instruct the server to install a dummy (meaningless) UPnP rule that can be observed by the clients, which refuse to work correctly otherwise
	// Enable a workaround for some broken implementations, which are handling the absence of UPnP rules incorrectly (for example, popping up error messages). This option will instruct the server to install a dummy (meaningless) UPnP rule that can be observed by the clients, which refuse to work correctly otherwise
	ShowDummyRule *bool `json:"showDummyRule,omitempty" tf:"show_dummy_rule,omitempty"`
}

type UpnpObservation struct {

	// (Boolean) Whether or not should the users be allowed to disable the router's external interface. This functionality (for users to be able to turn the router's external interface off without any authentication procedure) is required by the standard, but as it is sometimes not expected or unwanted in UPnP deployments which the standard was not designed for (it was designed mostly for home users to establish their own local networks), you can disable this behavior
	// Whether or not should the users be allowed to disable the router's external interface. This functionality (for users to be able to turn the router's external interface off without any authentication procedure) is required by the standard, but as it is sometimes not expected or unwanted in UPnP deployments which the standard was not designed for (it was designed mostly for home users to establish their own local networks), you can disable this behavior
	AllowDisableExternalInterface *bool `json:"allowDisableExternalInterface,omitempty" tf:"allow_disable_external_interface,omitempty"`

	// (Boolean) Enable UPnP service.
	// Enable UPnP service.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Enable a workaround for some broken implementations, which are handling the absence of UPnP rules incorrectly (for example, popping up error messages). This option will instruct the server to install a dummy (meaningless) UPnP rule that can be observed by the clients, which refuse to work correctly otherwise
	// Enable a workaround for some broken implementations, which are handling the absence of UPnP rules incorrectly (for example, popping up error messages). This option will instruct the server to install a dummy (meaningless) UPnP rule that can be observed by the clients, which refuse to work correctly otherwise
	ShowDummyRule *bool `json:"showDummyRule,omitempty" tf:"show_dummy_rule,omitempty"`
}

type UpnpParameters struct {

	// (Boolean) Whether or not should the users be allowed to disable the router's external interface. This functionality (for users to be able to turn the router's external interface off without any authentication procedure) is required by the standard, but as it is sometimes not expected or unwanted in UPnP deployments which the standard was not designed for (it was designed mostly for home users to establish their own local networks), you can disable this behavior
	// Whether or not should the users be allowed to disable the router's external interface. This functionality (for users to be able to turn the router's external interface off without any authentication procedure) is required by the standard, but as it is sometimes not expected or unwanted in UPnP deployments which the standard was not designed for (it was designed mostly for home users to establish their own local networks), you can disable this behavior
	// +kubebuilder:validation:Optional
	AllowDisableExternalInterface *bool `json:"allowDisableExternalInterface,omitempty" tf:"allow_disable_external_interface,omitempty"`

	// (Boolean) Enable UPnP service.
	// Enable UPnP service.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Enable a workaround for some broken implementations, which are handling the absence of UPnP rules incorrectly (for example, popping up error messages). This option will instruct the server to install a dummy (meaningless) UPnP rule that can be observed by the clients, which refuse to work correctly otherwise
	// Enable a workaround for some broken implementations, which are handling the absence of UPnP rules incorrectly (for example, popping up error messages). This option will instruct the server to install a dummy (meaningless) UPnP rule that can be observed by the clients, which refuse to work correctly otherwise
	// +kubebuilder:validation:Optional
	ShowDummyRule *bool `json:"showDummyRule,omitempty" tf:"show_dummy_rule,omitempty"`
}

// UpnpSpec defines the desired state of Upnp
type UpnpSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UpnpParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UpnpInitParameters `json:"initProvider,omitempty"`
}

// UpnpStatus defines the observed state of Upnp.
type UpnpStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UpnpObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Upnp is the Schema for the Upnps API. *<span style="color:red">If you do not disable the `allow-disable-external-interface`, any user from the local network will be able (without any authentication procedures) to disable the router's external interface.</span>*
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type Upnp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UpnpSpec   `json:"spec"`
	Status            UpnpStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UpnpList contains a list of Upnps
type UpnpList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Upnp `json:"items"`
}

// Repository type metadata.
var (
	Upnp_Kind             = "Upnp"
	Upnp_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Upnp_Kind}.String()
	Upnp_KindAPIVersion   = Upnp_Kind + "." + CRDGroupVersion.String()
	Upnp_GroupVersionKind = CRDGroupVersion.WithKind(Upnp_Kind)
)

func init() {
	SchemeBuilder.Register(&Upnp{}, &UpnpList{})
}
