// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BGPVPNExportInitParameters struct {

	// (String) The name of the routing filter chain that is used to filter prefixes during import.
	// The name of the routing filter chain that is used to filter prefixes before exporting.
	FilterChain *string `json:"filterChain,omitempty" tf:"filter_chain,omitempty"`

	// (String) The name of the select filter chain that is used to select prefixes to be exported exporting.
	// The name of the select filter chain that is used to select prefixes to be exported exporting.
	FilterSelect *string `json:"filterSelect,omitempty" tf:"filter_select,omitempty"`

	// (String) Enable redistribution of specified route types from VRF to VPNv4.
	// Enable redistribution of specified route types from VRF to VPNv4.
	Redistribute *string `json:"redistribute,omitempty" tf:"redistribute,omitempty"`

	// (Set of String) List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// List of route targets added when exporting VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type BGPVPNExportObservation struct {

	// (String) The name of the routing filter chain that is used to filter prefixes during import.
	// The name of the routing filter chain that is used to filter prefixes before exporting.
	FilterChain *string `json:"filterChain,omitempty" tf:"filter_chain,omitempty"`

	// (String) The name of the select filter chain that is used to select prefixes to be exported exporting.
	// The name of the select filter chain that is used to select prefixes to be exported exporting.
	FilterSelect *string `json:"filterSelect,omitempty" tf:"filter_select,omitempty"`

	// (String) Enable redistribution of specified route types from VRF to VPNv4.
	// Enable redistribution of specified route types from VRF to VPNv4.
	Redistribute *string `json:"redistribute,omitempty" tf:"redistribute,omitempty"`

	// (Set of String) List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// List of route targets added when exporting VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type BGPVPNExportParameters struct {

	// (String) The name of the routing filter chain that is used to filter prefixes during import.
	// The name of the routing filter chain that is used to filter prefixes before exporting.
	// +kubebuilder:validation:Optional
	FilterChain *string `json:"filterChain,omitempty" tf:"filter_chain,omitempty"`

	// (String) The name of the select filter chain that is used to select prefixes to be exported exporting.
	// The name of the select filter chain that is used to select prefixes to be exported exporting.
	// +kubebuilder:validation:Optional
	FilterSelect *string `json:"filterSelect,omitempty" tf:"filter_select,omitempty"`

	// (String) Enable redistribution of specified route types from VRF to VPNv4.
	// Enable redistribution of specified route types from VRF to VPNv4.
	// +kubebuilder:validation:Optional
	Redistribute *string `json:"redistribute,omitempty" tf:"redistribute,omitempty"`

	// (Set of String) List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// List of route targets added when exporting VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// +kubebuilder:validation:Optional
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`
}

type BGPVPNImportInitParameters struct {

	// (String) The name of the routing filter chain that is used to filter prefixes during import.
	// The name of the routing filter chain that is used to filter prefixes during import.
	FilterChain *string `json:"filterChain,omitempty" tf:"filter_chain,omitempty"`

	// (Set of String) List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`

	// (String) The router ID of the BGP instance that will be used for the BGP best path selection algorithm.
	// The router ID of the BGP instance that will be used for the BGP best path selection algorithm.
	RouterID *string `json:"routerId,omitempty" tf:"router_id,omitempty"`
}

type BGPVPNImportObservation struct {

	// (String) The name of the routing filter chain that is used to filter prefixes during import.
	// The name of the routing filter chain that is used to filter prefixes during import.
	FilterChain *string `json:"filterChain,omitempty" tf:"filter_chain,omitempty"`

	// (Set of String) List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`

	// (String) The router ID of the BGP instance that will be used for the BGP best path selection algorithm.
	// The router ID of the BGP instance that will be used for the BGP best path selection algorithm.
	RouterID *string `json:"routerId,omitempty" tf:"router_id,omitempty"`
}

type BGPVPNImportParameters struct {

	// (String) The name of the routing filter chain that is used to filter prefixes during import.
	// The name of the routing filter chain that is used to filter prefixes during import.
	// +kubebuilder:validation:Optional
	FilterChain *string `json:"filterChain,omitempty" tf:"filter_chain,omitempty"`

	// (Set of String) List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// List of route targets that will be used to import VPNv4 routes. The accepted RT format is similar to the one for Route Distinguishers.
	// +kubebuilder:validation:Optional
	// +listType=set
	RouteTargets []*string `json:"routeTargets,omitempty" tf:"route_targets,omitempty"`

	// (String) The router ID of the BGP instance that will be used for the BGP best path selection algorithm.
	// The router ID of the BGP instance that will be used for the BGP best path selection algorithm.
	// +kubebuilder:validation:Optional
	RouterID *string `json:"routerId,omitempty" tf:"router_id,omitempty"`
}

type BGPVPNInitParameters struct {

	// Comment on the item. The provider uses it as the resource identity: required at create and enforced unique within the menu.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// -export))
	// A group of parameters associated with the route export.
	Export []BGPVPNExportInitParameters `json:"export,omitempty" tf:"export,omitempty"`

	// -import))
	// A group of parameters associated with the route import.
	Import []BGPVPNImportInitParameters `json:"import,omitempty" tf:"import,omitempty"`

	// (String) Name of the instance this VPN is assigned to.
	// Name of the instance this VPN is assigned to.
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Label allocationpolicy.
	// Label allocationpolicy.
	LabelAllocationPolicy *string `json:"labelAllocationPolicy,omitempty" tf:"label_allocation_policy,omitempty"`

	// (String) VPN instance name.
	// VPN instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Helps to distinguish between overlapping routes from multiple VRFs. Should be unique per VRF. Accepts 3 types of formats.
	// Helps to distinguish between overlapping routes from multiple VRFs. Should be unique per VRF. Accepts 3 types of formats.
	RouteDistinguisher *string `json:"routeDistinguisher,omitempty" tf:"route_distinguisher,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type BGPVPNObservation struct {

	// Comment on the item. The provider uses it as the resource identity: required at create and enforced unique within the menu.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// -export))
	// A group of parameters associated with the route export.
	Export []BGPVPNExportObservation `json:"export,omitempty" tf:"export,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// -import))
	// A group of parameters associated with the route import.
	Import []BGPVPNImportObservation `json:"import,omitempty" tf:"import,omitempty"`

	// (Boolean)
	Inactive *bool `json:"inactive,omitempty" tf:"inactive,omitempty"`

	// (String) Name of the instance this VPN is assigned to.
	// Name of the instance this VPN is assigned to.
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Label allocationpolicy.
	// Label allocationpolicy.
	LabelAllocationPolicy *string `json:"labelAllocationPolicy,omitempty" tf:"label_allocation_policy,omitempty"`

	// (String) VPN instance name.
	// VPN instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Helps to distinguish between overlapping routes from multiple VRFs. Should be unique per VRF. Accepts 3 types of formats.
	// Helps to distinguish between overlapping routes from multiple VRFs. Should be unique per VRF. Accepts 3 types of formats.
	RouteDistinguisher *string `json:"routeDistinguisher,omitempty" tf:"route_distinguisher,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type BGPVPNParameters struct {

	// Comment on the item. The provider uses it as the resource identity: required at create and enforced unique within the menu.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// -export))
	// A group of parameters associated with the route export.
	// +kubebuilder:validation:Optional
	Export []BGPVPNExportParameters `json:"export,omitempty" tf:"export,omitempty"`

	// -import))
	// A group of parameters associated with the route import.
	// +kubebuilder:validation:Optional
	Import []BGPVPNImportParameters `json:"import,omitempty" tf:"import,omitempty"`

	// (String) Name of the instance this VPN is assigned to.
	// Name of the instance this VPN is assigned to.
	// +kubebuilder:validation:Optional
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Label allocationpolicy.
	// Label allocationpolicy.
	// +kubebuilder:validation:Optional
	LabelAllocationPolicy *string `json:"labelAllocationPolicy,omitempty" tf:"label_allocation_policy,omitempty"`

	// (String) VPN instance name.
	// VPN instance name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Helps to distinguish between overlapping routes from multiple VRFs. Should be unique per VRF. Accepts 3 types of formats.
	// Helps to distinguish between overlapping routes from multiple VRFs. Should be unique per VRF. Accepts 3 types of formats.
	// +kubebuilder:validation:Optional
	RouteDistinguisher *string `json:"routeDistinguisher,omitempty" tf:"route_distinguisher,omitempty"`

	// (String) The VRF table this resource operates on.
	// The VRF table this resource operates on.
	// +kubebuilder:validation:Optional
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

// BGPVPNSpec defines the desired state of BGPVPN
type BGPVPNSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BGPVPNParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BGPVPNInitParameters `json:"initProvider,omitempty"`
}

// BGPVPNStatus defines the observed state of BGPVPN.
type BGPVPNStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BGPVPNObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BGPVPN is the Schema for the BGPVPNs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type BGPVPN struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routeDistinguisher) || (has(self.initProvider) && has(self.initProvider.routeDistinguisher))",message="spec.forProvider.routeDistinguisher is a required parameter"
	Spec   BGPVPNSpec   `json:"spec"`
	Status BGPVPNStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BGPVPNList contains a list of BGPVPNs
type BGPVPNList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BGPVPN `json:"items"`
}

// Repository type metadata.
var (
	BGPVPN_Kind             = "BGPVPN"
	BGPVPN_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BGPVPN_Kind}.String()
	BGPVPN_KindAPIVersion   = BGPVPN_Kind + "." + CRDGroupVersion.String()
	BGPVPN_GroupVersionKind = CRDGroupVersion.WithKind(BGPVPN_Kind)
)

func init() {
	SchemeBuilder.Register(&BGPVPN{}, &BGPVPNList{})
}
