// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MacServerInitParameters struct {

	// (String) List of interfaces for MAC Telnet access.
	// List of interfaces for MAC Telnet access.
	AllowedInterfaceList *string `json:"allowedInterfaceList,omitempty" tf:"allowed_interface_list,omitempty"`
}

type MacServerObservation struct {

	// (String) List of interfaces for MAC Telnet access.
	// List of interfaces for MAC Telnet access.
	AllowedInterfaceList *string `json:"allowedInterfaceList,omitempty" tf:"allowed_interface_list,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type MacServerParameters struct {

	// (String) List of interfaces for MAC Telnet access.
	// List of interfaces for MAC Telnet access.
	// +kubebuilder:validation:Optional
	AllowedInterfaceList *string `json:"allowedInterfaceList,omitempty" tf:"allowed_interface_list,omitempty"`
}

// MacServerSpec defines the desired state of MacServer
type MacServerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MacServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MacServerInitParameters `json:"initProvider,omitempty"`
}

// MacServerStatus defines the observed state of MacServer.
type MacServerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MacServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MacServer is the Schema for the MacServers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,routeros}
type MacServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.allowedInterfaceList) || (has(self.initProvider) && has(self.initProvider.allowedInterfaceList))",message="spec.forProvider.allowedInterfaceList is a required parameter"
	Spec   MacServerSpec   `json:"spec"`
	Status MacServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MacServerList contains a list of MacServers
type MacServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MacServer `json:"items"`
}

// Repository type metadata.
var (
	MacServer_Kind             = "MacServer"
	MacServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MacServer_Kind}.String()
	MacServer_KindAPIVersion   = MacServer_Kind + "." + CRDGroupVersion.String()
	MacServer_GroupVersionKind = CRDGroupVersion.WithKind(MacServer_Kind)
)

func init() {
	SchemeBuilder.Register(&MacServer{}, &MacServerList{})
}
