// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClientOptionInitParameters struct {

	// client option code.
	// The dhcp-client option code.
	Code *int64 `json:"code,omitempty" tf:"code,omitempty"`

	// client.
	// The name that will be used in dhcp-client.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) raw_value is computed from value.
	// raw_value is computed from value.
	RawValue *string `json:"rawValue,omitempty" tf:"raw_value,omitempty"`

	// client option
	// The dhcp-client option
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ClientOptionObservation struct {

	// client option code.
	// The dhcp-client option code.
	Code *int64 `json:"code,omitempty" tf:"code,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// client.
	// The name that will be used in dhcp-client.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) raw_value is computed from value.
	// raw_value is computed from value.
	RawValue *string `json:"rawValue,omitempty" tf:"raw_value,omitempty"`

	// client option
	// The dhcp-client option
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ClientOptionParameters struct {

	// client option code.
	// The dhcp-client option code.
	// +kubebuilder:validation:Optional
	Code *int64 `json:"code,omitempty" tf:"code,omitempty"`

	// client.
	// The name that will be used in dhcp-client.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) raw_value is computed from value.
	// raw_value is computed from value.
	// +kubebuilder:validation:Optional
	RawValue *string `json:"rawValue,omitempty" tf:"raw_value,omitempty"`

	// client option
	// The dhcp-client option
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// ClientOptionSpec defines the desired state of ClientOption
type ClientOptionSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ClientOptionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClientOptionInitParameters `json:"initProvider,omitempty"`
}

// ClientOptionStatus defines the observed state of ClientOption.
type ClientOptionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClientOptionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClientOption is the Schema for the ClientOptions API. <!-- schema generated by tfplugindocs --> ## Schema ### Required - `code` (Number) The dhcp-client option code. - `name` (String) The name that will be used in dhcp-client. ### Optional - `raw_value` (String) raw_value is computed from value. - `value` (String) The dhcp-client option ### Read-Only - `id` (String) The ID of this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type ClientOption struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.code) || (has(self.initProvider) && has(self.initProvider.code))",message="spec.forProvider.code is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ClientOptionSpec   `json:"spec"`
	Status ClientOptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClientOptionList contains a list of ClientOptions
type ClientOptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClientOption `json:"items"`
}

// Repository type metadata.
var (
	ClientOption_Kind             = "ClientOption"
	ClientOption_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClientOption_Kind}.String()
	ClientOption_KindAPIVersion   = ClientOption_Kind + "." + CRDGroupVersion.String()
	ClientOption_GroupVersionKind = CRDGroupVersion.WithKind(ClientOption_Kind)
)

func init() {
	SchemeBuilder.Register(&ClientOption{}, &ClientOptionList{})
}
