// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type L2TpClientInitParameters struct {

	// (Boolean) Whether to add L2TP remote address as a default route.
	// Whether to add L2TP remote address as a default route.
	AddDefaultRoute *bool `json:"addDefaultRoute,omitempty" tf:"add_default_route,omitempty"`

	// (Set of String) Allowed authentication methods.
	// Allowed authentication methods.
	// +listType=set
	Allow []*string `json:"allow,omitempty" tf:"allow,omitempty"`

	// (Boolean) Whether to allow FastPath processing. Must be disabled if IPsec tunneling is used.
	// Whether to allow FastPath processing. Must be disabled if IPsec tunneling is used.
	AllowFastPath *bool `json:"allowFastPath,omitempty" tf:"allow_fast_path,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// client`
	// Remote address of L2TP server (if the address is in VRF table, VRF should be specified) `/interface l2tp-client`
	// `add connect-to=192.168.88.1@vrf1 name=l2tp-out1 user=l2tp-client`.
	ConnectTo *string `json:"connectTo,omitempty" tf:"connect_to,omitempty"`

	// default-route is also selected.
	// Since v6.2, sets distance value applied to auto created default route, if add-default-route is also selected.
	DefaultRouteDistance *int64 `json:"defaultRouteDistance,omitempty" tf:"default_route_distance,omitempty"`

	// (Boolean) Connects only when outbound traffic is generated. If selected, then route with gateway address from `10.112.112.0/24` network will be added while connection is not established.
	// Connects only when outbound traffic is generated. If selected, then route with gateway address from `10.112.112.0/24` network will be added while connection is not established.
	DialOnDemand *bool `json:"dialOnDemand,omitempty" tf:"dial_on_demand,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// ipsec is enabled.
	// Preshared key used when use-ipsec is enabled.
	IpsecSecretSecretRef *v2.SecretKeySelector `json:"ipsecSecretSecretRef,omitempty" tf:"-"`

	// (Number) Since v6.0rc13, tunnel keepalive timeout in seconds.
	// Since v6.0rc13, tunnel keepalive timeout in seconds.
	KeepaliveTimeout *int64 `json:"keepaliveTimeout,omitempty" tf:"keepalive_timeout,omitempty"`

	// (String) Specify protocol version.
	// Specify protocol version.
	L2TpProtoVersion *string `json:"l2tpProtoVersion,omitempty" tf:"l2tp_proto_version,omitempty"`

	// (String) Set the virtual circuit identifier to bind the one end of the L2TPv3 control channel.
	// Set the virtual circuit identifier to bind the one end of the L2TPv3 control channel.
	L2Tpv3CircuitID *string `json:"l2tpv3CircuitId,omitempty" tf:"l2tpv3_circuit_id,omitempty"`

	// (Number) Configures an L2TPv3 pseudowire static session cookie.
	// Configures an L2TPv3 pseudowire static session cookie.
	L2Tpv3CookieLength *int64 `json:"l2tpv3CookieLength,omitempty" tf:"l2tpv3_cookie_length,omitempty"`

	// (String) Specifies which hash function to be used.
	// Specifies which hash function to be used.
	L2Tpv3DigestHash *string `json:"l2tpv3DigestHash,omitempty" tf:"l2tpv3_digest_hash,omitempty"`

	// (Number) Maximum Receive Unit. Max packet size that L2TP interface will be able to receive without packet fragmentation.
	// Maximum Receive Unit. Max packet size that L2TP interface will be able to receive without packet fragmentation.
	MaxMru *int64 `json:"maxMru,omitempty" tf:"max_mru,omitempty"`

	// (Number) Maximum Transmission Unit. Max packet size that L2TP interface will be able to send without packet fragmentation.
	// Maximum Transmission Unit. Max packet size that L2TP interface will be able to send without packet fragmentation.
	MaxMtu *int64 `json:"maxMtu,omitempty" tf:"max_mtu,omitempty"`

	// (String) Maximum packet size that can be received on the link. If a packet is bigger than tunnel MTU, it will be split into multiple packets, allowing full size IP or Ethernet packets to be sent over the tunnel.
	// Maximum packet size that can be received on the link. If a packet is bigger than tunnel MTU, it will be split into multiple packets, allowing full size IP or Ethernet packets to be sent over the tunnel.
	Mrru *string `json:"mrru,omitempty" tf:"mrru,omitempty"`

	// (String) Descriptive name of the interface.
	// Descriptive name of the interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) Password used for authentication.
	// Password used for authentication.
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) Specifies which PPP profile configuration will be used when establishing the tunnel.
	// Specifies which PPP profile configuration will be used when establishing the tunnel.
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// (Boolean)
	RandomSourcePort *bool `json:"randomSourcePort,omitempty" tf:"random_source_port,omitempty"`

	// (String) Specify source address.
	// Specify source address.
	SrcAddress *string `json:"srcAddress,omitempty" tf:"src_address,omitempty"`

	// ipsec and set static policies for clients with enabled `tunnel=yes`, `level=unique` settings.
	// When this option is enabled, dynamic IPSec peer configuration and policy (transport mode) is added to encapsulate L2TP connection into IPSec tunnel. Multiple L2tp/ipsec clients behind the same NAT will not work in this mode. To achieve such scenario, disable use-ipsec and set static policies for clients with enabled `tunnel=yes`, `level=unique` settings.
	UseIpsec *bool `json:"useIpsec,omitempty" tf:"use_ipsec,omitempty"`

	// (String) To use peer dns.
	// To use peer dns.
	UsePeerDNS *string `json:"usePeerDns,omitempty" tf:"use_peer_dns,omitempty"`

	// (String) User name used for authentication.
	// User name used for authentication.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type L2TpClientObservation struct {

	// (Boolean) Whether to add L2TP remote address as a default route.
	// Whether to add L2TP remote address as a default route.
	AddDefaultRoute *bool `json:"addDefaultRoute,omitempty" tf:"add_default_route,omitempty"`

	// (Set of String) Allowed authentication methods.
	// Allowed authentication methods.
	// +listType=set
	Allow []*string `json:"allow,omitempty" tf:"allow,omitempty"`

	// (Boolean) Whether to allow FastPath processing. Must be disabled if IPsec tunneling is used.
	// Whether to allow FastPath processing. Must be disabled if IPsec tunneling is used.
	AllowFastPath *bool `json:"allowFastPath,omitempty" tf:"allow_fast_path,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// client`
	// Remote address of L2TP server (if the address is in VRF table, VRF should be specified) `/interface l2tp-client`
	// `add connect-to=192.168.88.1@vrf1 name=l2tp-out1 user=l2tp-client`.
	ConnectTo *string `json:"connectTo,omitempty" tf:"connect_to,omitempty"`

	// default-route is also selected.
	// Since v6.2, sets distance value applied to auto created default route, if add-default-route is also selected.
	DefaultRouteDistance *int64 `json:"defaultRouteDistance,omitempty" tf:"default_route_distance,omitempty"`

	// (Boolean) Connects only when outbound traffic is generated. If selected, then route with gateway address from `10.112.112.0/24` network will be added while connection is not established.
	// Connects only when outbound traffic is generated. If selected, then route with gateway address from `10.112.112.0/24` network will be added while connection is not established.
	DialOnDemand *bool `json:"dialOnDemand,omitempty" tf:"dial_on_demand,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Since v6.0rc13, tunnel keepalive timeout in seconds.
	// Since v6.0rc13, tunnel keepalive timeout in seconds.
	KeepaliveTimeout *int64 `json:"keepaliveTimeout,omitempty" tf:"keepalive_timeout,omitempty"`

	// (String) Specify protocol version.
	// Specify protocol version.
	L2TpProtoVersion *string `json:"l2tpProtoVersion,omitempty" tf:"l2tp_proto_version,omitempty"`

	// (String) Set the virtual circuit identifier to bind the one end of the L2TPv3 control channel.
	// Set the virtual circuit identifier to bind the one end of the L2TPv3 control channel.
	L2Tpv3CircuitID *string `json:"l2tpv3CircuitId,omitempty" tf:"l2tpv3_circuit_id,omitempty"`

	// (Number) Configures an L2TPv3 pseudowire static session cookie.
	// Configures an L2TPv3 pseudowire static session cookie.
	L2Tpv3CookieLength *int64 `json:"l2tpv3CookieLength,omitempty" tf:"l2tpv3_cookie_length,omitempty"`

	// (String) Specifies which hash function to be used.
	// Specifies which hash function to be used.
	L2Tpv3DigestHash *string `json:"l2tpv3DigestHash,omitempty" tf:"l2tpv3_digest_hash,omitempty"`

	// (Number) Maximum Receive Unit. Max packet size that L2TP interface will be able to receive without packet fragmentation.
	// Maximum Receive Unit. Max packet size that L2TP interface will be able to receive without packet fragmentation.
	MaxMru *int64 `json:"maxMru,omitempty" tf:"max_mru,omitempty"`

	// (Number) Maximum Transmission Unit. Max packet size that L2TP interface will be able to send without packet fragmentation.
	// Maximum Transmission Unit. Max packet size that L2TP interface will be able to send without packet fragmentation.
	MaxMtu *int64 `json:"maxMtu,omitempty" tf:"max_mtu,omitempty"`

	// (String) Maximum packet size that can be received on the link. If a packet is bigger than tunnel MTU, it will be split into multiple packets, allowing full size IP or Ethernet packets to be sent over the tunnel.
	// Maximum packet size that can be received on the link. If a packet is bigger than tunnel MTU, it will be split into multiple packets, allowing full size IP or Ethernet packets to be sent over the tunnel.
	Mrru *string `json:"mrru,omitempty" tf:"mrru,omitempty"`

	// (String) Descriptive name of the interface.
	// Descriptive name of the interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies which PPP profile configuration will be used when establishing the tunnel.
	// Specifies which PPP profile configuration will be used when establishing the tunnel.
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// (Boolean)
	RandomSourcePort *bool `json:"randomSourcePort,omitempty" tf:"random_source_port,omitempty"`

	// (Boolean)
	Running *bool `json:"running,omitempty" tf:"running,omitempty"`

	// (String) Specify source address.
	// Specify source address.
	SrcAddress *string `json:"srcAddress,omitempty" tf:"src_address,omitempty"`

	// ipsec and set static policies for clients with enabled `tunnel=yes`, `level=unique` settings.
	// When this option is enabled, dynamic IPSec peer configuration and policy (transport mode) is added to encapsulate L2TP connection into IPSec tunnel. Multiple L2tp/ipsec clients behind the same NAT will not work in this mode. To achieve such scenario, disable use-ipsec and set static policies for clients with enabled `tunnel=yes`, `level=unique` settings.
	UseIpsec *bool `json:"useIpsec,omitempty" tf:"use_ipsec,omitempty"`

	// (String) To use peer dns.
	// To use peer dns.
	UsePeerDNS *string `json:"usePeerDns,omitempty" tf:"use_peer_dns,omitempty"`

	// (String) User name used for authentication.
	// User name used for authentication.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type L2TpClientParameters struct {

	// (Boolean) Whether to add L2TP remote address as a default route.
	// Whether to add L2TP remote address as a default route.
	// +kubebuilder:validation:Optional
	AddDefaultRoute *bool `json:"addDefaultRoute,omitempty" tf:"add_default_route,omitempty"`

	// (Set of String) Allowed authentication methods.
	// Allowed authentication methods.
	// +kubebuilder:validation:Optional
	// +listType=set
	Allow []*string `json:"allow,omitempty" tf:"allow,omitempty"`

	// (Boolean) Whether to allow FastPath processing. Must be disabled if IPsec tunneling is used.
	// Whether to allow FastPath processing. Must be disabled if IPsec tunneling is used.
	// +kubebuilder:validation:Optional
	AllowFastPath *bool `json:"allowFastPath,omitempty" tf:"allow_fast_path,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// client`
	// Remote address of L2TP server (if the address is in VRF table, VRF should be specified) `/interface l2tp-client`
	// `add connect-to=192.168.88.1@vrf1 name=l2tp-out1 user=l2tp-client`.
	// +kubebuilder:validation:Optional
	ConnectTo *string `json:"connectTo,omitempty" tf:"connect_to,omitempty"`

	// default-route is also selected.
	// Since v6.2, sets distance value applied to auto created default route, if add-default-route is also selected.
	// +kubebuilder:validation:Optional
	DefaultRouteDistance *int64 `json:"defaultRouteDistance,omitempty" tf:"default_route_distance,omitempty"`

	// (Boolean) Connects only when outbound traffic is generated. If selected, then route with gateway address from `10.112.112.0/24` network will be added while connection is not established.
	// Connects only when outbound traffic is generated. If selected, then route with gateway address from `10.112.112.0/24` network will be added while connection is not established.
	// +kubebuilder:validation:Optional
	DialOnDemand *bool `json:"dialOnDemand,omitempty" tf:"dial_on_demand,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// ipsec is enabled.
	// Preshared key used when use-ipsec is enabled.
	// +kubebuilder:validation:Optional
	IpsecSecretSecretRef *v2.SecretKeySelector `json:"ipsecSecretSecretRef,omitempty" tf:"-"`

	// (Number) Since v6.0rc13, tunnel keepalive timeout in seconds.
	// Since v6.0rc13, tunnel keepalive timeout in seconds.
	// +kubebuilder:validation:Optional
	KeepaliveTimeout *int64 `json:"keepaliveTimeout,omitempty" tf:"keepalive_timeout,omitempty"`

	// (String) Specify protocol version.
	// Specify protocol version.
	// +kubebuilder:validation:Optional
	L2TpProtoVersion *string `json:"l2tpProtoVersion,omitempty" tf:"l2tp_proto_version,omitempty"`

	// (String) Set the virtual circuit identifier to bind the one end of the L2TPv3 control channel.
	// Set the virtual circuit identifier to bind the one end of the L2TPv3 control channel.
	// +kubebuilder:validation:Optional
	L2Tpv3CircuitID *string `json:"l2tpv3CircuitId,omitempty" tf:"l2tpv3_circuit_id,omitempty"`

	// (Number) Configures an L2TPv3 pseudowire static session cookie.
	// Configures an L2TPv3 pseudowire static session cookie.
	// +kubebuilder:validation:Optional
	L2Tpv3CookieLength *int64 `json:"l2tpv3CookieLength,omitempty" tf:"l2tpv3_cookie_length,omitempty"`

	// (String) Specifies which hash function to be used.
	// Specifies which hash function to be used.
	// +kubebuilder:validation:Optional
	L2Tpv3DigestHash *string `json:"l2tpv3DigestHash,omitempty" tf:"l2tpv3_digest_hash,omitempty"`

	// (Number) Maximum Receive Unit. Max packet size that L2TP interface will be able to receive without packet fragmentation.
	// Maximum Receive Unit. Max packet size that L2TP interface will be able to receive without packet fragmentation.
	// +kubebuilder:validation:Optional
	MaxMru *int64 `json:"maxMru,omitempty" tf:"max_mru,omitempty"`

	// (Number) Maximum Transmission Unit. Max packet size that L2TP interface will be able to send without packet fragmentation.
	// Maximum Transmission Unit. Max packet size that L2TP interface will be able to send without packet fragmentation.
	// +kubebuilder:validation:Optional
	MaxMtu *int64 `json:"maxMtu,omitempty" tf:"max_mtu,omitempty"`

	// (String) Maximum packet size that can be received on the link. If a packet is bigger than tunnel MTU, it will be split into multiple packets, allowing full size IP or Ethernet packets to be sent over the tunnel.
	// Maximum packet size that can be received on the link. If a packet is bigger than tunnel MTU, it will be split into multiple packets, allowing full size IP or Ethernet packets to be sent over the tunnel.
	// +kubebuilder:validation:Optional
	Mrru *string `json:"mrru,omitempty" tf:"mrru,omitempty"`

	// (String) Descriptive name of the interface.
	// Descriptive name of the interface.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) Password used for authentication.
	// Password used for authentication.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) Specifies which PPP profile configuration will be used when establishing the tunnel.
	// Specifies which PPP profile configuration will be used when establishing the tunnel.
	// +kubebuilder:validation:Optional
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	RandomSourcePort *bool `json:"randomSourcePort,omitempty" tf:"random_source_port,omitempty"`

	// (String) Specify source address.
	// Specify source address.
	// +kubebuilder:validation:Optional
	SrcAddress *string `json:"srcAddress,omitempty" tf:"src_address,omitempty"`

	// ipsec and set static policies for clients with enabled `tunnel=yes`, `level=unique` settings.
	// When this option is enabled, dynamic IPSec peer configuration and policy (transport mode) is added to encapsulate L2TP connection into IPSec tunnel. Multiple L2tp/ipsec clients behind the same NAT will not work in this mode. To achieve such scenario, disable use-ipsec and set static policies for clients with enabled `tunnel=yes`, `level=unique` settings.
	// +kubebuilder:validation:Optional
	UseIpsec *bool `json:"useIpsec,omitempty" tf:"use_ipsec,omitempty"`

	// (String) To use peer dns.
	// To use peer dns.
	// +kubebuilder:validation:Optional
	UsePeerDNS *string `json:"usePeerDns,omitempty" tf:"use_peer_dns,omitempty"`

	// (String) User name used for authentication.
	// User name used for authentication.
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

// L2TpClientSpec defines the desired state of L2TpClient
type L2TpClientSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   L2TpClientParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider L2TpClientInitParameters `json:"initProvider,omitempty"`
}

// L2TpClientStatus defines the observed state of L2TpClient.
type L2TpClientStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               L2TpClientObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// L2TpClient is the Schema for the L2TpClients API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type L2TpClient struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   L2TpClientSpec   `json:"spec"`
	Status L2TpClientStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// L2TpClientList contains a list of L2TpClients
type L2TpClientList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []L2TpClient `json:"items"`
}

// Repository type metadata.
var (
	L2TpClient_Kind             = "L2TpClient"
	L2TpClient_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: L2TpClient_Kind}.String()
	L2TpClient_KindAPIVersion   = L2TpClient_Kind + "." + CRDGroupVersion.String()
	L2TpClient_GroupVersionKind = CRDGroupVersion.WithKind(L2TpClient_Kind)
)

func init() {
	SchemeBuilder.Register(&L2TpClient{}, &L2TpClientList{})
}
