// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WireguardInitParameters struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Number) Port for WireGuard service to listen on for incoming sessions.
	// Port for WireGuard service to listen on for incoming sessions.
	ListenPort *int64 `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// (String) Layer3 Maximum transmission unit ('auto', 0 .. 65535). Look for the exact minimum value in the MikroTik documentation
	// Layer3 Maximum transmission unit ('auto', 0 .. 65535). Look for the exact minimum value in the MikroTik documentation
	Mtu *string `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) Changing the name of this resource will force it to be recreated.
	// Changing the name of this resource will force it to be recreated
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) A base64 private key. If not specified, it will be automatically generated upon interface creation.
	// A base64 private key. If not specified, it will be automatically generated upon interface creation.
	PrivateKeySecretRef *v2.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`
}

type WireguardObservation struct {

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Port for WireGuard service to listen on for incoming sessions.
	// Port for WireGuard service to listen on for incoming sessions.
	ListenPort *int64 `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// (String) Layer3 Maximum transmission unit ('auto', 0 .. 65535). Look for the exact minimum value in the MikroTik documentation
	// Layer3 Maximum transmission unit ('auto', 0 .. 65535). Look for the exact minimum value in the MikroTik documentation
	Mtu *string `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) Changing the name of this resource will force it to be recreated.
	// Changing the name of this resource will force it to be recreated
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A base64 public key is calculated from the private key.
	// A base64 public key is calculated from the private key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (Boolean)
	Running *bool `json:"running,omitempty" tf:"running,omitempty"`
}

type WireguardParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Number) Port for WireGuard service to listen on for incoming sessions.
	// Port for WireGuard service to listen on for incoming sessions.
	// +kubebuilder:validation:Optional
	ListenPort *int64 `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// (String) Layer3 Maximum transmission unit ('auto', 0 .. 65535). Look for the exact minimum value in the MikroTik documentation
	// Layer3 Maximum transmission unit ('auto', 0 .. 65535). Look for the exact minimum value in the MikroTik documentation
	// +kubebuilder:validation:Optional
	Mtu *string `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// (String) Changing the name of this resource will force it to be recreated.
	// Changing the name of this resource will force it to be recreated
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) A base64 private key. If not specified, it will be automatically generated upon interface creation.
	// A base64 private key. If not specified, it will be automatically generated upon interface creation.
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef *v2.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`
}

// WireguardSpec defines the desired state of Wireguard
type WireguardSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   WireguardParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WireguardInitParameters `json:"initProvider,omitempty"`
}

// WireguardStatus defines the observed state of Wireguard.
type WireguardStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WireguardObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Wireguard is the Schema for the Wireguards API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,routeros}
type Wireguard struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.listenPort) || (has(self.initProvider) && has(self.initProvider.listenPort))",message="spec.forProvider.listenPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   WireguardSpec   `json:"spec"`
	Status WireguardStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WireguardList contains a list of Wireguards
type WireguardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Wireguard `json:"items"`
}

// Repository type metadata.
var (
	Wireguard_Kind             = "Wireguard"
	Wireguard_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Wireguard_Kind}.String()
	Wireguard_KindAPIVersion   = Wireguard_Kind + "." + CRDGroupVersion.String()
	Wireguard_GroupVersionKind = CRDGroupVersion.WithKind(Wireguard_Kind)
)

func init() {
	SchemeBuilder.Register(&Wireguard{}, &WireguardList{})
}
