name: Publish Provider Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag to publish (e.g. v0.1.0)"
        required: true
      go-version:
        description: 'Go version to use if building needs to be done'
        default: '1.26.5'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  publish-provider-package:
    uses: crossplane-contrib/provider-workflows/.github/workflows/publish-provider.yml@451c4dc6ad3691b0a702a997a0ac24e8bbc8bbaa # main
    with:
      repository: provider-routeros
      registry_org: sindrip
      version: ${{ inputs.version }}
      go-version: ${{ inputs.go-version }}
      cleanup-disk: true
      mirror: false
    secrets:
      GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
